[sel YESNO_SEL top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg KEYFREE_START_0411 [Dojima]]
[f 2 1][f 4 6 11 1 0 1]I'll wait here. Why don't you take a[n]walk and get some fresh air?[n][f 1 1][e]
[f 2 1]The shopping district is near the house,[n]so you should get to know where all the[n]stores are.[n][f 1 1][e]

[msg HELP_TEST_CALL_SYSTEM_SA]
[f 2 1]Press the [f 0 1 2]Command Menu button[f 0 1 0] to open the[n][f 0 1 2]System menu[f 0 1 0], where you can set options[n]and load saved games.[n][f 1 1][e]

[msg HELP_TEST_CALL_SYSTEM_SI]
[f 2 1]Press the [f 0 1 2]Sub Menu button[f 0 1 0] to open a menu [n]that will allow you to [f 0 1 2]move instantly to[n]selected locations[f 0 1 0] without walking.[n][f 1 1][e]

[msg HELP_TEST_SAVEPOINT]
[f 2 1]Examine the blue butterfly to save[n]your progress.[n][f 1 1][e]

[msg TEST_STOP_0411]
[f 2 1]> Dojima is waiting for you. You shouldn't[n]wander too far off...[n][f 1 1][e]

[msg GOINTO_HOME_STOP]
[f 2 1]> You recall that you were supposed to[n]meet up with Yosuke and Chie at the[n]Junes food court...[n][f 1 1][e]
[f 2 1]> Go to Junes?[n][f 1 1][e]

[msg ``1205_STOP``]
[f 2 1]> You have to gather information. [n]Try asking some of the nearby people...[n][f 1 1][e]

[msg ``0213_STOP``]
[f 2 1]> You have no reason to be here[n]right now...[n][f 1 1][e]
[f 2 1]> You should go to the mountain cabin[n]to save Marie.[n][f 1 1][e]

[msg EXIT_STREET_OK]
[f 2 1]> Leave the shopping district?[n][f 1 1][e]

[msg KEIJIBAN]
[f 2 1]> There is a bulletin board.[n][f 1 1][e]

[sel KEIJIBAN_SEL top]
[f 2 1]Look at the job openings[e]
[f 2 1]Look at the poster[e]
[f 2 1]Cancel[e]

[msg KEIJIBAN_POSTER]
[f 2 1]> "Samegawa Bojou: Misuzu Hiiragi"[n][f 1 1][e]

[msg KEIJIBAN_POSTER_1]
[f 2 1]> It's a poster of a famous enka singer...[n][f 1 1][e]

[msg KEIJIBAN_POSTER_2]
[f 2 1]> It's the same poster that was torn up[n]inside the TV...[n][f 1 1][e]

[msg KEIJIBAN_MAECH]
[f 2 1]> There are no job openings at the[n]moment.[n][f 1 1][e]

[msg KEIJIBAN_BYTE]
[f 2 1]> There are several job openings[n]posted.[n][f 1 1][e]

[msg KEIJIBAN_BYTE2]
[f 2 1]> Which one do you want to read?[n][f 1 1][e]

[sel KEIJIBAN_BYTE_SEL1 top]
[f 2 1]Envelope constructor[e]
[f 2 1]Translator[e]
[f 2 1]Origami crane folder[e]
[f 2 1]See others[e]
[f 2 1]Done looking[e]

[sel KEIJIBAN_BYTE_SEL2 top]
[f 2 1]Assistant day care caretaker[e]
[f 2 1]Pub dishwasher[e]
[f 2 1]Hospital janitor[e]
[f 2 1]Tutor[e]
[f 2 1]See others[e]
[f 2 1]Done looking[e]

[sel KEIJIBAN_BYTE_SEL3 top]
[f 2 1]Assistant day care caretaker[e]
[f 2 1](Coming soon)[e]
[f 2 1](Coming soon)[e]
[f 2 1](Coming soon)[e]
[f 2 1]See others[e]
[f 2 1]Done looking[e]

[sel KEIJIBAN_BYTE_SEL4 top]
[f 2 1]Junes stocker[e]
[f 2 1]Pub dishwasher[e]
[f 2 1]See others[e]
[f 2 1]Done looking[e]

[msg KEIJIBAN_BYTE_MADA]
[f 2 1]> It reads, "New jobs will be posted[n]on 5/25."[n][f 1 1][e]

[msg KEIJIBAN_HUUTOU]
[f 2 1]●●Envelope constructor●●[n][f 0 1 3]Daily Salary[f 0 1 0]: 1,000+ yen[n][f 0 1 3]Benefit[f 0 1 0]: Good for raising [f 0 1 1]Diligence[f 0 1 0]![n][f 1 1][e]

[msg KEIJIBAN_HUUTOU2]
[f 2 1]> Take this job?[n][f 1 1][e]

[sel HUUTOU_YESNO top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg KEIJIBAN_HUUTOU3]
[f 2 1]> You have taken the job constructing[n]envelopes.[n][f 1 1][e]
[f 2 1]> You can make envelopes [f 0 1 2]on the work[n]desk in your room[f 0 1 0].[n][f 1 1][e]

[msg KEIJIBAN_HUUTOU4]
[f 2 1]> You've already accepted this job.[n][f 1 1][e]
[f 2 1]> You can make envelopes [f 0 1 2]on the work[f 0 1 0][n][f 0 1 2]desk in your room[f 0 1 0].[n][f 1 1][e]

[msg KEIJIBAN_HONYAKU]
[f 2 1]●●Translator●●[n][f 0 1 3]Daily Salary[f 0 1 0]: 1,500+ yen[n][f 0 1 3]Requirements[f 0 1 0]: Some [f 0 1 1]Knowledge[f 0 1 0] required.[n][f 0 1 3]Benefit[f 0 1 0]: Perfect for raising [f 0 1 1]Expression[f 0 1 0]![n][f 1 1][e]

[msg KEIJIBAN_HONYAKU2]
[f 2 1]> Take this job?[n][f 1 1][e]

[sel HONYAKU_YESNO top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg KEIJIBAN_HONYAKU3]
[f 2 1]> You have taken the translation job.[n][f 1 1][e]
[f 2 1]> You can translate [f 0 1 2]on the work desk[f 0 1 0][n][f 0 1 2]in your room[f 0 1 0].[n][f 1 1][e]

[msg KEIJIBAN_HONYAKU4]
[f 2 1]> You've already accepted this job.[n][f 1 1][e]
[f 2 1]> You can translate [f 0 1 2]on the work desk[f 0 1 0][n][f 0 1 2]in your room[f 0 1 0].[n][f 1 1][e]

[msg KEIJIBAN_TURUORI]
[f 2 1]●●Origami crane folder●●[n][f 0 1 3]Daily Salary[f 0 1 0]: 0 yen (Volunteer)[n][f 0 1 3]Requirements[f 0 1 0]: Some [f 0 1 1]Diligence[f 0 1 0] required.[n][f 0 1 3]Benefit[f 0 1 0]: Deftly raises [f 0 1 1]Understanding[f 0 1 0]![n][f 1 1][e]

[msg KEIJIBAN_TURUORI2]
[f 2 1]> Take this job?[n][f 1 1][e]

[sel TURUORI_YESNO top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg KEIJIBAN_TURUORI3]
[f 2 1]> You have taken a volunteer job[n]folding origami cranes.[n][f 1 1][e]
[f 2 1]> You can fold cranes [f 0 1 2]on the work desk[f 0 1 0][n][f 0 1 2]in your room[f 0 1 0].[n][f 1 1][e]

[msg KEIJIBAN_TURUORI4]
[f 2 1]> You've already accepted this job.[n][f 1 1][e]
[f 2 1]> You can fold cranes [f 0 1 2]on the work desk[f 0 1 0][n][f 0 1 2]in your room[f 0 1 0].[n][f 1 1][e]

[msg KEIJIBAN_HOIKU]
[f 2 1]●●Assistant day care caretaker●●[n][f 0 1 3]Daily Salary[f 0 1 0]: 4,000+ yen[n][f 0 1 3]Work Days[f 0 1 0]: Mon/Fri/Sat (Not raining)[n][f 0 1 3]Requirements[f 0 1 0]: [f 0 1 1]Understanding[f 0 1 0] required.[n][f 1 1][e]

[msg KEIJIBAN_HOIKU2]
[f 2 1]> Take this job?[n][f 1 1][e]

[sel HOIKU_YESNO top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg HOIKU_YES]
[f 2 1]> You have enough [f 0 1 1]Understanding[f 0 1 0] to do the job.[n][f 1 1][e]
[f 2 1]> You have taken the assistant day care[n]caretaker job.[n][f 1 1][e]

[msg HOIKU_YES2]
[f 2 1]> You have taken the assistant day care[n]caretaker job.[n][f 1 1][e]
[f 2 1]> Take [f 0 1 2]the bus in the shopping district[f 0 1 0][n][f 0 1 2]to the hill overlooking town[f 0 1 0] if it's [f 0 1 2]not[f 0 1 0][n][f 0 1 2]raining on Monday, Friday, or Saturday[f 0 1 0].[n][f 1 1][e]

[msg HOIKU_TARINAI]
[f 2 1]> ...But you noticed there was more.[n][f 1 1][e]
[f 2 1]> In order to meet this job's requirements,[n]your [f 0 1 1]Understanding[f 0 1 0] must be [f 0 1 1]Saintly[f 0 1 0].[n][f 1 1][e]
[f 2 1]> You decided to improve your [f 0 1 1]Understanding[f 0 1 0][n]before taking the job...[n][f 1 1][e]

[msg KEIJIBAN_HOIKU4]
[f 2 1]> You've already accepted this job.[n][f 1 1][e]
[f 2 1]> Take [f 0 1 2]the bus in the shopping district[f 0 1 0][n][f 0 1 2]to the hill overlooking town[f 0 1 0] if it's [f 0 1 2]not[f 0 1 0][n][f 0 1 2]raining on Monday, Friday, or Saturday[f 0 1 0].[n][f 1 1][e]

[msg KEIJIBAN_BYOUIN]
[f 2 1]●●Hospital janitor●●[n][f 0 1 3]Daily Salary[f 0 1 0]: 5,000+ yen[n][f 0 1 3]Requirements[f 0 1 0]: Some [f 0 1 1]Diligence[f 0 1 0] required.[n][f 0 1 3]Work Days[f 0 1 0]: Wed/Thur/Fri (Night)[n][f 0 1 3]Benefit[f 0 1 0]: Gives you a shot of [f 0 1 1]Courage[f 0 1 0]![n][f 1 1][e]

[msg KEIJIBAN_BYOUIN2]
[f 2 1]> Take this job?[n][f 1 1][e]

[sel BYOUIN_YESNO top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg BYOUIN_YES]
[f 2 1]> You feel that your [f 0 1 1]Diligence[f 0 1 0] is[n]sufficient for the hospital job.[n][f 1 1][e]

[msg BYOUIN_YES2]
[f 2 1]> You have taken the hospital janitor[n]job.[n][f 1 1][e]
[f 2 1]>  Leave from the bus stop in the shopping district[n]on [f 0 1 2]Wednesday, Thursday, or[f 0 1 0] [f 0 1 2]Friday nights[f 0 1 0].[n][f 1 1][e]

[msg BYOUIN_TARINAI]
[f 2 1]> In order to meet this job's[n]requirements, your [f 0 1 1]Diligence[f 0 1 0] must at[n]least be [f 0 1 1]Strong[f 0 1 0].[n][f 1 1][e]
[f 2 1]> You decided to improve your [f 0 1 1]Diligence[f 0 1 0][n]before taking the job...[n][f 1 1][e]

[msg KEIJIBAN_BYOUIN4]
[f 2 1]> You've already accepted this job.[n][f 1 1][e]
[f 2 1]> Leave from the bus stop in the shopping district[n]on [f 0 1 2]Wednesday, Thursday, or[f 0 1 0] [f 0 1 2]Friday nights[f 0 1 0].[n][f 1 1][e]

[msg KEIJIBAN_SEITO]
[f 2 1]●●Tutor●●[n][f 0 1 3]Daily Salary[f 0 1 0]: 10,000 yen[n][f 0 1 3]Requirements[f 0 1 0]: Requires high [f 0 1 1]Understanding[f 0 1 0].[n][f 0 1 3]Work Days[f 0 1 0]: Tue/Thur/Sat (Night)[n][f 0 1 3]Benefit[f 0 1 0]: Boosts your [f 0 1 1]Expression[f 0 1 0]![n][f 1 1][e]

[msg KEIJIBAN_SEITO2]
[f 2 1]> Take this job?[n][f 1 1][e]

[sel SEITO_YESNO top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg SEITO_YES]
[f 2 1]> You feel that your [f 0 1 1]Understanding[f 0 1 0] is[n]sufficient for this job.[n][f 1 1][e]

[msg SEITO_YES2]
[f 2 1]> You have taken the tutoring job.[n][f 1 1][e]
[f 2 1]> Leave from the bus stop in the shopping district[n]on [f 0 1 2]Tuesday, Thursday, or Saturday night[f 0 1 0].[n][f 1 1][e]

[msg SEITO_TARINAI]
[f 2 1]> In order to meet this job's requirements,[n]your [f 0 1 1]Understanding[f 0 1 0] must be [f 0 1 1]Saintly[f 0 1 0].[n][f 1 1][e]
[f 2 1]> You decided to improve your [f 0 1 1]Understanding[f 0 1 0][n]before taking the job...[n][f 1 1][e]

[msg KEIJIBAN_SEITO4]
[f 2 1]> You've already accepted this job.[n][f 1 1][e]
[f 2 1]> Leave from the bus stop in the shopping district[n]on [f 0 1 2]Tuesday, Thursday, or Saturday night[f 0 1 0].[n][f 1 1][e]

[msg KEIJIBAN_JUNES]
[f 2 1]●●Junes Stocker●●[n][f 0 1 3]Daily Salary[f 0 1 0]: 5,000+ yen[n][f 0 1 3]Work Days[f 0 1 0]: Sun/Mon/Wed (Night)[n][f 0 1 3]Benefit[f 0 1 0]: A workplace that feels like home! (mostly)[n][f 1 1][e]

[msg KEIJIBAN_JUNES2]
[f 2 1]> Take this job?[n][f 1 1][e]

[sel JUNES_YESNO top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg JUNES_YES]
[f 2 1]> You feel that your [f 0 1 1]Diligence[f 0 1 0] is[n]sufficient for the Junes job.[n][f 1 1][e]

[msg JUNES_YES2]
[f 2 1]> You have taken the Junes stocker job.[n][f 1 1][e]
[f 2 1]> Go to Junes from your house on[n][f 0 1 2]Sunday, Monday or Wednesday nights[f 0 1 0].[n][f 1 1][e]

[msg JUNES_TARINAI]
[f 2 1]> In order to meet this job's requirements,[n]your [f 0 1 1]Diligence[f 0 1 0] must be [f 0 1 1]Strong[f 0 1 0].[n][f 1 1][e]
[f 2 1]> You decided to improve your [f 0 1 1]Diligence[f 0 1 0][n]before taking the job...[n][f 1 1][e]

[msg KEIJIBAN_JUNES4]
[f 2 1]> You've already accepted this job.[n][f 1 1][e]
[f 2 1]> Go to Junes from your house on[n][f 0 1 2]Sunday, Monday or Wednesday nights[f 0 1 0].[n][f 1 1][e]

[msg KEIJIBAN_SNACK]
[f 2 1]●●Shiroku Pub Dishwasher●●[n][f 0 1 3]Daily Salary[f 0 1 0]: 1,500+ yen[n][f 0 1 3]Requirements[f 0 1 0]: Some [f 0 1 1]Understanding[f 0 1 0].[n][f 0 1 3]Work Days[f 0 1 0]: Any day at night[n][f 0 1 3]Benefit[f 0 1 0]: Boosts your [f 0 1 1]Diligence[f 0 1 0]![n][f 1 1][e]

[msg KEIJIBAN_SNACK2]
[f 2 1]> Take this job?[n][f 1 1][e]

[sel SNACK_YESNO top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg SNACK_YES]
[f 2 1]> You have enough [f 0 1 1]Understanding[f 0 1 0] to do the job.[n][f 1 1][e]

[msg SNACK_YES2]
[f 2 1]> You have taken the Shiroku Pub dishwasher[n]job.[n][f 1 1][e]
[f 2 1]> Go to Shiroku Pub at [f 0 1 2]night[f 0 1 0].[n][f 1 1][e]

[msg SNACK_TARINAI]
[f 2 1]> In order to meet this job's requirements,[n]your [f 0 1 1]Understanding[f 0 1 0] must be [f 0 1 1]Kindly[f 0 1 0].[n][f 1 1][e]
[f 2 1]> You decided to improve your [f 0 1 1]Understanding[f 0 1 0][n]before taking the job...[n][f 1 1][e]

[msg KEIJIBAN_SNACK469]
[f 2 1]> You've already accepted this job.[n][f 1 1][e]
[f 2 1]> Go to Shiroku Pub at [f 0 1 2]night[f 0 1 0].[n][f 1 1][e]

[msg HONYAKU_TARINAI]
[f 2 1]> In order to meet this job's[n]requirements, your [f 0 1 1]Knowledge[f 0 1 0] must at[n]least be [f 0 1 1]Informed[f 0 1 0].[n][f 1 1][e]
[f 2 1]> You decided to improve your [f 0 1 1]Knowledge[f 0 1 0][n]before taking the job...[n][f 1 1][e]

[msg TURUORI_TARINAI]
[f 2 1]> In order to meet this job's[n]requirements, your [f 0 1 1]Diligence[f 0 1 0] must at[n]least be [f 0 1 1]Persistent[f 0 1 0].[n][f 1 1][e]
[f 2 1]> You decided to improve your [f 0 1 1]Diligence[f 0 1 0][n]before taking the job...[n][f 1 1][e]

[msg BAS_MES]
[f 2 1]> It's the bus stop. You have no reason[n]to use the bus right now.[n][f 1 1][e]

[msg BAS_MES_NIGHT]
[f 2 1]> It's the bus stop. Today's service[n]has ended.[n][f 1 1][e]

[msg BAS_MES2]
[f 2 1]> It's the bus stop.[n][f 1 1][e]
[f 2 1]> Where do you want to go?[n][f 1 1][e]

[sel BAS_SEL top]
[f 2 1]Tutoring[e]
[f 2 1]Quit[e]

[msg BAS_MES_KATEI]
[f 2 1][f 5 8 0 10]> You decided to go to the residential[n]area for your tutoring job.[n][f 1 1][e]

[msg BAS_MES_BAITO_NG]
[f 2 1]> It's the bus stop.[n][f 1 1][e]

[msg BAS_MES_KATEI_NG]
[f 2 1]> The tutoring job is on [f 0 1 2]Tuesdays,[n]Thursdays,[f 0 1 0] [f 0 1 2]and Saturdays[f 0 1 0].[n][f 1 1][e]

[msg BAS_MES_BYOUIN_NG]
[f 2 1]> The hospital janitor job is on [f 0 1 2]Wednesdays,[n]Thursdays,[f 0 1 0] [f 0 1 2]and Fridays[f 0 1 0].[n][f 1 1][e]

[msg BAS_MES_GOJITUDAN]
[f 2 1]> It's the bus stop.[n][f 1 1][e]
[f 2 1]> Where do you want to go?[n][f 1 1][e]

[sel BAS_GOJI_SEL top]
[f 2 1]Inaba Municipal Hospital[e]
[f 2 1]Hill overlooking town[e]
[f 2 1]Amagi Inn[e]
[f 2 1]Quit[e]

[msg BAS_GOJI]
[f 2 1]> You have no reason to use the bus[n]right now.[n][f 1 1][e]

[msg BAS_GOJI2]
[f 2 1]> You have no reason to use the bus[n]right now.[n][f 1 1][e]

[msg BAS_GOJI3]
[f 2 1]> You have no reason to use the bus[n]right now.[n][f 1 1][e]

[msg BAS_MES_GAKUDOU_NG]
[f 2 1]> It's the bus stop.[n][f 1 1][e]
[f 2 1]> You can work at the day care center[n]on [f 0 1 2]Monday, Friday, or Saturday[f 0 1 0] when[n]it's [f 0 1 2]not raining[f 0 1 0].[n][f 1 1][e]

[msg BAS_MES_NEWYEAR]
[f 2 1]> It's the bus stop.[n][f 1 1][e]
[f 2 1]> Where do you want to go?[n][f 1 1][e]

[sel BAS_NEWYEAR_SEL top]
[f 2 1]Inaba Municipal Hospital[e]
[f 2 1]Quit[e]

[msg MSG_BOOKSTORE_0411]
[f 2 1]> This is the bookstore.[n][f 1 1][e]
[f 2 1]> It is fairly empty inside.[n][f 1 1][e]

[msg NO_ERRAND]
[f 2 1]> You have no business here.[n][f 1 1][e]

[msg FIND_BOOK_01]
[f 2 1]> This bookstore may have the book[n]with amazing recipes...[n][f 1 1][e]
[f 2 1]> You decide to look for it.[n][f 1 1][e]

[msg FIND_BOOK_02]
[f 2 1]> You found the book with amazing[n]recipes![n][f 1 1][e]

[msg BUY_BOOK_00_START]
[f 2 1]> There's a poster.[n][f 1 1][e]
[f 2 1]> The following books are being released[n]on [f 2 4 10]/[f 2 4 11]![n][f 1 1][e]

[msg BUY_BOOK_00_1_START]
[f 2 1]> There's a poster.[n][f 1 1][e]
[f 2 1]> The following books are being released[n]on [f 2 4 12]/[f 2 4 13]![n][f 1 1][e]

[msg BUY_BOOK_01_START]
[f 2 1]> There's a poster.[n][f 1 1][e]
[f 2 1]> "Now on sale!"[n][f 1 1][e]

[msg BUY_BOOK_INFO]
[f 2 1]> "[f 2 4 0]" [f 2 4 1] yen[n] [f 2 4 2][n][f 1 1][e]

[msg BUY_BOOK_00_END]
[f 2 1]> ...That's what it says.[n][f 1 1][e]

[msg BUY_BOOK_01_END]
[f 2 1]> ...That's what it says.[n][f 1 1][e]
[f 2 1]> You have yet to buy any of these books.[n][f 1 1][e]

[msg BUY_BOOK_02]
[f 2 1]> You have [f 2 4 20] yen. [n]Do you want to buy a book?[n][f 1 1][e]

[sel BOOK_BUY_SEL top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg BUY_BOOK_03]
[f 2 1]> Purchased [f 2 4 0].[n][f 1 1][e]

[msg BUY_BOOK_0506]
[f 2 1]> Purchased [f 4 4 3 1 1259].[n][f 1 1][e]

[msg BUY_BOOK_0531]
[f 2 1]> Purchased [f 4 4 3 1 1264].[n][f 1 1][e]

[msg BUY_BOOK_0627]
[f 2 1]> Purchased [f 4 4 3 1 1260].[n][f 1 1][e]

[msg BUY_BOOK_0714]
[f 2 1]> Purchased [f 4 4 3 1 1265].[n][f 1 1][e]

[msg BUY_BOOK_0803]
[f 2 1]> Purchased [f 4 4 3 1 1261].[n][f 1 1][e]

[msg BUY_BOOK_0823]
[f 2 1]> Purchased [f 4 4 3 1 1266].[n][f 1 1][e]

[msg BUY_BOOK_0919]
[f 2 1]> Purchased [f 4 4 3 1 1262].[n][f 1 1][e]

[msg BUY_BOOK_1008]
[f 2 1]> Purchased [f 4 4 3 1 1267].[n][f 1 1][e]

[msg BUY_BOOK_1031]
[f 2 1]> Purchased [f 4 4 3 1 1263].[n][f 1 1][e]

[msg BUY_BOOK_1124]
[f 2 1]> Purchased [f 4 4 3 1 1268].[n][f 1 1][e]

[msg BUY_BOOK_03_2]
[f 2 1]> You can read the book [f 0 1 2]on the sofa in[n][f 0 1 2]your room[f 0 1 0].[n][f 1 1][e]

[msg BUY_BOOK_04]
[f 2 1]> You can't afford that book.[n][f 1 1][e]

[msg BUY_BOOK_05]
[f 2 1]> The price is 1,000 yen.[n]Do you want to buy the book?[n][f 1 1][e]

[msg BUY_BOOK_06]
[f 2 1]> You already have this book.[n][f 1 1][e]

[msg BUY_BOOK_07]
[f 2 1]> There's a poster.[n][f 1 1][e]
[f 2 1]> It reads, "Due to the possible damage[n]to our books by the fog, we have[n]temporarily halted new book sales."[n][f 1 1][e]
[f 2 1]> It seems they will not be getting[n]anything new...[n][f 1 1][e]

[msg BUY_BOOK_08]
[f 2 1]> None of the books grab your interest.[n][f 1 1][e]

[msg BUY_BOOK_09]
[f 2 1]> There's a poster.[n][f 1 1][e]
[f 2 1]> There's nothing of interest written[n]on it.[n][f 1 1][e]

[msg MSG_BOOK_CLOSED_NIGHT]
[f 2 1]> The store has closed for today...[n][f 1 1][e]

[msg UNDOUBU_GOJI]
[f 2 1]> You hear Daisuke and Kou's voices[n]coming from inside the restaurant...[n][f 1 1][e]

[sel UNDOU_SEL_GOJI top]
[f 2 1]Enter[e]
[f 2 1]Don't enter[e]

[msg TYUUKA_STOP]
[f 2 1]> You recall that you were supposed to[n]meet up with Yosuke and Chie at the[n]Junes food court...[n][f 1 1][e]
[f 2 1]> There's no time to waste here.[n][f 1 1][e]

[msg TYUUKA_STOP_NIGHT_0417]
[f 2 1]> There is a notice: "We have closed[n]in preparation for tomorrow."[n][f 1 1][e]
[f 2 1]> It seems they have closed for today...[n][f 1 1][e]

[msg TYUUKA_STOP_NIGHT_RAIN]
[f 2 1]> There is a notice: "Due to the popularity[n]of the Rainy Day Mega Beef Bowl, we have[n]run out of ingredients."[n][f 1 1][e]
[f 2 1]> It seems they have closed for today...[n][f 1 1][e]

[msg TYUUKA_STOP_NIGHT_SNOW]
[f 2 1]> There is a notice: "Due to the popularity[n]of the Winter Mega Beef Bowl, we have[n]run out of ingredients."[n][f 1 1][e]
[f 2 1]> It seems they have closed for today...[n][f 1 1][e]

[msg AIYA_STOP]
[f 2 1]> It seems this is a Chinese restaurant...[n][f 1 1][e]
[f 2 1]> You can smell the appetizing scent of[n]food from here...[n][f 1 1][e]

[msg TYUUKA1]
[f 2 1]> This is the Chinese Diner, Aiya.[n][f 1 1][e]

[msg TYUUKA_EAT_NIGHT]
[f 2 1]> Maybe you should stop by tonight...[n][f 1 1][e]

[sel EAT_SEL top]
[f 2 1]Go inside[e]
[f 2 1]Leave[e]

[msg TYUUKA_MENU_KONKI]
[f 2 1]> A sign reads, "Today's special is the[n]Chow Mein set. Only 800 yen."[n][f 1 1][e]
[f 2 1]> "Try our authentic noodles! We won't[n]make them until you order them!"[n][f 1 1][e]
[f 2 1]> You feel waiting for this dish will raise your[n][f 0 1 1]Diligence[f 0 1 0]...[n][f 1 1][e]

[msg TYUUKA_MENU_KANYOUSA]
[f 2 1]> A sign reads, "Today's special is the[n]Aiya Steak Bowl. Only 800 yen."[n][f 1 1][e]
[f 2 1]> "You will not leave with an empty[n]stomach!"[n][f 1 1][e]
[f 2 1]> You feel finishing this dish will raise[n]your [f 0 1 1]Understanding[f 0 1 0]...[n][f 1 1][e]

[msg TYUUKA_MENU_YUUKI]
[f 2 1]> A sign reads, "Today's special is the[n]Mabo Tofu Combo. 800 yen."[n][f 1 1][e]
[f 2 1]> "3 different types of Mabo Tofu:[n]Hot, ultra-hot, and heatdiculous!"[n][f 1 1][e]
[f 2 1]> You feel this meal may raise your[n][f 0 1 1]Courage[f 0 1 0]...[n][f 1 1][e]

[msg TYUUKA_MENU_AME]
[f 2 1]> Aiya seems to be having some kind of[n]promotion today.[n][f 1 1][e]
[f 2 1]> A sign reads, "Rainy day challenge,[n]3,000 yen Mega Beef Bowl! If you finish [n]this quintuple-sized bowl, it's free!"[n][f 1 1][e]
[f 2 1]> You feel taking on this dish will help[n]raise several "characteristics."[n][f 1 1][e]

[msg TYUUKA_MENU_SNOW_INFO]
[f 2 1]> There's a notice posted out front.[n][f 1 1][e]
[f 2 1]> "It doesn't rain in the winter, so[n]every Friday is Mega Beef Bowl day."[n][f 1 1][e]

[msg TYUUKA_MENU_SNOW]
[f 2 1]> Aiya seems to be having some kind of[n]promotion today.[n][f 1 1][e]
[f 2 1]> A sign reads, "Winter challenge,[n]3,000 yen Mega Beef Bowl! If you finish [n]this quintuple-sized bowl, it's free!"[n][f 1 1][e]
[f 2 1]> You feel taking on this dish will help[n]raise several "characteristics."[n][f 1 1][e]

[sel TYUUKA_Q_SEL top]
[f 2 1]Spend time here[e]
[f 2 1]Not today[e]

[msg TYUUKA2]
[f 2 1]> You currently have [f 2 4 20] yen.[n]Spend time here?[n][f 1 1][e]

[msg TYUUKA22]
[f 2 1]> You currently have [f 2 4 20] yen.[n]Spend time here?[n][f 1 1][e]

[msg TYUUKA23]
[f 2 1]> You currently have [f 2 4 20] yen.[n]Spend time here?[n][f 1 1][e]

[msg TYUUKA]
[f 2 1]> This is the Chinese Diner, Aiya.[n][f 1 1][e]
[f 2 1]> The sign reads, "Please come in if[n]you think a deliciously prepared meal[n]is worth a little patience."[n][f 1 1][e]

[msg TYUUKA_TAIKU]
[f 2 1]> You hear Daisuke and Kou's voices[n]coming from inside the restaurant.[n]Eat here?[n][f 1 1][e]

[msg TYUUKA_SUGOSU]
[f 2 1]> You decided to spend time here.[n][f 1 1][e]

[msg TYUUKA_MONEY_TARINAI]
[f 2 1]> ...Unfortunately, you don't have[n]enough money.[n][f 1 1][e]

[msg TYUUKA_DUNGEONGO]
[f 2 1]> The restaurant is filled with[n]customers...[n][f 1 1][e]
[f 2 1]> It's probably too late to eat here. [n]You should come earlier next time.[n][f 1 1][e]

[msg TYUUKA_READ30_BONUS]
[f 2 1]> Plus, you have read "[f 2 4 10]."[n]You feel you can raise it by more.[n][f 1 1][e]

[msg BYTE_TUTORIAL]
[f 2 1]Working a part-time job will earn you[n]money.[n][f 1 1][e]
[f 2 1]You may be able to increase your[n][f 0 1 1]Knowledge[f 0 1 0], [f 0 1 1]Diligence[f 0 1 0], [f 0 1 1]Understanding[f 0 1 0],[n][f 0 1 1]Expression[f 0 1 0], or [f 0 1 1]Courage[f 0 1 0] by taking a job.[n][f 1 1][e]
[f 2 1]When these various qualities reach[n]certain points, you may unlock quests,[n]meet new people, or earn a raise.[n][f 1 1][e]

[msg TUBUSI_TUTORIAL]
[f 2 1]You can raise your [f 0 1 1]Knowledge[f 0 1 0], [f 0 1 1]Diligence[f 0 1 0],[n][f 0 1 1]Understanding[f 0 1 0], [f 0 1 1]Expression[f 0 1 0], or [f 0 1 1]Courage[f 0 1 0][n]by participating in some activities.[n][f 1 1][e]
[f 2 1]When these various qualities reach[n]certain levels, you may meet new[n]people or unlock quests.[n][f 1 1][e]

[msg TATUMIYA_NO]
[f 2 1]> It's the textile shop.[n][f 1 1][e]
[f 2 1]> There's no reason for you to be here[n]right now.[n][f 1 1][e]

[msg TATUMIYA]
[f 2 1]> Kanji seems to be home.[n][f 1 1][e]

[msg TATUMIYA_02]
[f 2 1]> Spend time with Kanji?[n][f 1 1][e]

[sel TATUMIYA_SEL top]
[f 2 1]Yes[e]
[f 2 1]Check Social Link rank[e]
[f 2 1]No[e]

[msg TATUMIYA_YES]
[f 2 1][f 5 8 0 10]> You decided to spend time with Kanji.[n][f 1 1][e]

[msg KANJI_JYOUHOU]
[f 2 1]> Kanji seems to be home.[n][f 1 1][e]
[f 2 1][f 1 5]Kanji[n][f 4 6 6 1 1 1]What's up?[n][f 1 1][e]
[f 2 1]Any progress with the investigation?[n][f 1 1][e]
[f 2 1]It'd be so much easier if we had some[n]clues...[n][f 1 1][e]
[f 2 1]Hey, maybe you can ask your uncle[n]about it.[n][f 1 1][e]
[f 2 1][f 1 5] [n][f 4 7 0]> Dojima may have a clue...[n][f 1 1][e]

[msg TATUMIYA_CLOSE]
[f 2 1]> It's the textile shop.[n][f 1 1][e]
[f 2 1]> It appears that it's closed today.[n][f 1 1][e]

[msg TATUMIYA_OPEN]
[f 2 1]> It's the textile shop.[n][f 1 1][e]
[f 2 1]> Kanji's mother is standing in front[n]of the store. You decided to ask her[n]about Kanji...[n][f 1 1][e]

[msg TATUMIYA_MOHOU [Dye shop lady]]
[f 2 1]Hello, [f 4 2]-kun.  Can I help you?[n][f 1 1][e]
[f 2 1]> You asked if there was a student[n]working part-time here.[n][f 1 4][e]
[f 2 1]No. We don't hire part-timers here.[n][f 1 1][e]
[f 2 1]The work would be much easier if my son[n]would help me out a bit.[n][f 1 1][e]
[f 2 1]Can you ask him to help me out,[n][f 4 2]-kun?[n][f 1 1][e]
[f 2 1]> It appears that the student you're[n]looking for didn't work here...[n][f 1 4][e]

[msg TOUHUYA_NO]
[f 2 1]> It's the Marukyu tofu shop.[n][f 1 1][e]
[f 2 1]> An old woman is tending the store.[n][f 1 1][e]

[msg TOUHUYA_NO_NIGHT]
[f 2 1]> It's the Marukyu tofu shop.[n]It looks like it's closed at night.[n][f 1 1][e]

[msg TOUHUYA]
[f 2 1]> Rise is tending the store.[n][f 1 1][e]

[msg TOUHUYA_02]
[f 2 1]> Spend time with Rise?[n][f 1 1][e]

[sel TOUHUYA_SEL top]
[f 2 1]Yes[e]
[f 2 1]Check Social Link rank[e]
[f 2 1]No[e]

[msg TOUHUYA_YES]
[f 2 1][f 5 8 0 10]> You decided to spend time with Rise.[n][f 1 1][e]

[msg TOUHUYA_SOUSA_01 [Rise's grandmother]]
[f 2 1]Oh, you're the boy from the other day.[n]Looking for Rise?[n][f 1 1][e]
[f 2 1]Sometimes she leaves the house without[n]telling me... I hope she's okay...[n][f 1 1][e]
[f 2 1]I've heard that some person with a[n]camera has been wandering around[n]recently.[n][f 1 1][e]
[f 2 1]I think that person was called[n]a "papa rat" or something...[n][f 1 1][e]
[f 2 1]The people in this district try their[n]best to get rid of that person but he[n]just keeps coming back...[n][f 1 1][e]
[f 2 1]I heard that he's often at the[n]flood plain.[n][f 1 1][e]
[f 2 1]> There seems to be a paparazzo who's[n]been snooping on Rise.[n][f 1 4][e]
[f 2 1]> Maybe he knows something about Rise's[n]disappearance...[n][f 1 4][e]

[msg TOUHUYA_SOUSA_02 [Rise's grandmother]]
[f 2 1]I heard that he's often seen at the[n]flood plain.[n][f 1 1][e]
[f 2 1]The people in this district try their[n]best to get rid of that person but he[n]just keeps coming back...[n][f 1 1][e]
[f 2 1]> There seems to be a paparazzo who's[n]been snooping on Rise.[n][f 1 4][e]
[f 2 1]> Maybe he knows something about Rise's[n]disappearance...[n][f 1 4][e]

[msg TOUHUYA_MOHOU [Rise's grandmother]]
[f 2 1]Hm? You must be Rise's friend...[n][f 1 1][e]
[f 2 1]Rise is not home yet.[n][f 1 1][e]
[f 2 1]> You asked if a student was working[n]part-time here.[n][f 1 4][e]
[f 2 1]A student? No, I am the only one who[n]has been working here this entire time.[n][f 1 1][e]
[f 2 1]Thank goodness Rise has come back. [n]She's been very helpful.[n][f 1 1][e]
[f 2 1]> It appears that the student you're[n]looking for didn't work here...[n][f 1 4][e]

[msg MSG_FLD_DEBUG_MENU]
[f 2 1]> Pick a debug function.[n](Press the cancel button to exit)[n][f 1 1][e]

[sel SEL_FLD_DEBUG_MENU_PG1 top]
[f 2 1]Unlock fishing[e]
[f 2 1]Fishing bait +10[e]
[f 2 1]Unlock bug catching[e]
[f 2 1]Bug bait +10 (each)[e]
[f 2 1]Unlock plastic model[e]
[f 2 1]Unlock fortune[e]
[f 2 1]Next[e]

[msg MSG_FLD_DEBUG_MENU_PG1_1]
[f 2 1]> Obtained [f 2 5 3 13 0].[n][f 1 1][e]
[f 2 1]> Obtained [f 2 5 3 13 1] x 10.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG1_2]
[f 2 1]> Obtained [f 2 5 3 13 1] x 10.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG1_3]
[f 2 1]> Obtained [f 2 5 3 13 0].[n][f 1 1][e]
[f 2 1]> Obtained [f 2 5 3 13 1], [f 2 5 3 13 2][n]and [f 2 5 3 13 3] x 10 each.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG1_4]
[f 2 1]> Obtained [f 2 5 3 13 1], [f 2 5 3 13 2][n]and [f 2 5 3 13 3] x 10 each.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG1_5]
[f 2 1]> The plastic model store at the north[n]shopping district will now be open in[n]the evening.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG1_6]
[f 2 1]> You will now be able to draw fortunes[n]at the shrine.[n][f 1 1][e]

[sel SEL_FLD_DEBUG_MENU_PG2 top]
[f 2 1]Unlock gardening[e]
[f 2 1]Unlock Junes job[e]
[f 2 1]Unlock Shiroku Pub job[e]
[f 2 1]Get books[e]
[f 2 1]Next[e]

[msg MSG_FLD_DEBUG_MENU_PG2_1]
[f 2 1]> You will now be able to grow vegetables[n]from the living room at the house.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG2_2]
[f 2 1]> You can now take on the Junes job from[n]the door leaving your house. It's a[n]nighttime gig, though.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG2_3]
[f 2 1]> You will now be able to work at[n]Shiroku Pub in the south shopping[n]district at night.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG2_4]
[f 2 1]> All books unlocked. Read them at the[n]couch in your room in Dojima's house.[n][f 1 1][e]

[sel SEL_FLD_DEBUG_MENU_PG3 top]
[f 2 1]Unlock Okina City[e]
[f 2 1]Unlock Okina and Shichiri Beach[e]
[f 2 1]Unlock Mountain Cabin[e]
[f 2 1]Next[e]

[msg MSG_FLD_DEBUG_MENU_PG3_1]
[f 2 1]> Okina City has been added to the[n]large map.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG3_2]
[f 2 1]> Okina City and Shichiri Beach have[n]been added to the large map.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG3_3]
[f 2 1]> Mountain Cabin has been added to the[n]large map.[n][f 1 1][e]

[sel SEL_FLD_DEBUG_MENU_PG4 top]
[f 2 1]Kill all quests[e]
[f 2 1]Revive all quests[e]
[f 2 1]Able to fish the Guardian[e]
[f 2 1]Unable to fish the Guardian[e]
[f 2 1]Able to fish Sea Guardian[e]
[f 2 1]Unable to fish Sea Guardian[e]
[f 2 1]Cancel[e]

[msg MSG_FLD_DEBUG_MENU_PG4_1]
[f 2 1]> All quests are now marked as completed.[n]This might fiddle with some other things,[n]though, so watch out.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG4_2]
[f 2 1]> All quests are now marked as not complete.[n]This might fiddle with some other things,[n]though, so watch out.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG4_3]
[f 2 1]> You now can fish for the Guardian.[n][f 1 1][e]
[f 2 1]> Obtained [f 4 4 3 1 1057]![n][f 1 1][e]
[f 2 1]> Obtained [f 4 4 3 1 1016] x 10.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG4_4]
[f 2 1]> You are now unable to fish for the[n]Guardian.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG4_5]
[f 2 1]> You now can fish for the Sea Guardian.[n][f 1 1][e]
[f 2 1]> Obtained [f 4 4 3 1 1016] x 10.[n][f 1 1][e]

[msg MSG_FLD_DEBUG_MENU_PG4_6]
[f 2 1]> You are now unable to fish for the[n]Sea Guardian.[n][f 1 1][e]

[msg JINJYA_IN_NG_000]
[f 2 1]> The shrine is enveloped in darkness,[n]as still and silent as death itself...[n][f 1 1][e]

[msg JINJYA_IN_NG_010]
[f 2 1]> You feel a chill run down your spine...[n][f 1 1][e]
[f 2 1]> You feel your [f 0 1 1]Courage[f 0 1 0][n]needs to be at least [f 0 1 1]Reliable[f 0 1 0][n]to set foot in here...[n][f 1 1][e]

[msg HLP_KITUNE]
[f 2 1][f 0 1 2]Calling the fox after fulfilling an ema's[n]wish will strengthen the bond you share[f 0 1 0].[n]However, time will pass...[n][f 1 1][e]

[msg JINJYA]
[f 2 1]> It's the shrine.[n][f 1 1][e]
[f 2 1]> There's no need to enter.[n][f 1 1][e]

[msg JINJYA_MATURI_NG]
[f 2 1]> It's the shrine.[n][f 1 1][e]
[f 2 1]> Many people have gathered here for the[n]summer festival. It looks crowded...[n][f 1 1][e]
[f 2 1]> ...It may be better not to enter the[n]shrine right now.[n][f 1 1][e]

[msg ZINZYA_EXEC]
[f 2 1]> This is the shrine's main building.[n]What will you do?[n][f 1 1][e]

[sel SEL_ZINZYA top]
[f 2 1]Call the fox[e]
[f 2 1]Pray[e]
[f 2 1]Check Social Link rank[e]
[f 2 1]Nothing[e]

[sel SEL_ZINZYA_UKERU top]
[f 2 1]Accept the ema's request[e]
[f 2 1]Pray[e]
[f 2 1]Check Social Link rank[e]
[f 2 1]Nothing[e]

[sel SEL_ZINZYA_GOJITU top]
[f 2 1]Call the fox[e]
[f 2 1]Nothing[e]

[sel SEL_ZINZYA_NEWYEAR top]
[f 2 1]Call the fox[e]
[f 2 1]Nothing[e]

[msg JINJYA_IRAIOK]
[f 2 1]> This is the shrine's main building.[n][f 1 1][e]
[f 2 1]> You should report to the fox about[n]making the wish on the ema come true...[n][f 1 1][e]

[msg JINJYA_IRAINO1]
[f 2 1]> This is the shrine's main building.[n][f 1 1][e]
[f 2 1]> You are in the process of fulfilling[n]a wish written on an ema.[n][f 1 1][e]
[f 2 1]> The wish on the ema was...[n][f 1 1][e]
[f 2 1][f 1 5]Ema[n]I want things to go well with the[n]person I like![n][f 1 1][e]
[f 2 1][f 1 5] [n]> You should report to the fox once the[n]wish on the ema has been fulfilled...[n][f 1 1][e]

[msg JINJYA_IRAINO2]
[f 2 1]> This is the shrine's main building.[n][f 1 1][e]
[f 2 1]> You are in the process of fulfilling[n]a wish written on an ema.[n][f 1 1][e]
[f 2 1]> The wish on the ema was...[n][f 1 1][e]
[f 2 1][f 1 5]Ema[n]I want to clear my mind of snacks.[n]I want to hate them.[n][f 1 1][e]
[f 2 1][f 1 5] [n]> You should report to the fox once the[n]wish on the ema has been fulfilled...[n][f 1 1][e]

[msg JINJYA_IRAINO3]
[f 2 1]> This is the shrine's main building.[n][f 1 1][e]
[f 2 1]> You are in the process of fulfilling[n]a wish written on an ema.[n][f 1 1][e]
[f 2 1]> The wish on the ema was...[n][f 1 1][e]
[f 2 1][f 1 5]Ema[n]We want Koro to come back![n]Please, god.[n]                         -Saito[n][f 1 1][e]
[f 2 1][f 1 5] [n]> You should report to the fox once the[n]wish on the ema has been fulfilled...[n][f 1 1][e]

[msg JINJYA_IRAINO4]
[f 2 1]> This is the shrine's main building.[n][f 1 1][e]
[f 2 1]> You are in the process of fulfilling[n]a wish written on an ema.[n][f 1 1][e]
[f 2 1]> The wish on the ema was...[n][f 1 1][e]
[f 2 1][f 1 5]Ema[n]God, please give me some friends.[n]                         Yoshitaka[n][f 1 1][e]
[f 2 1][f 1 5] [n]> You should report to the fox once the[n]wish on the ema has been fulfilled...[n][f 1 1][e]

[msg JINJYA_IRAINO5]
[f 2 1]> This is the shrine's main building.[n][f 1 1][e]
[f 2 1]> You are in the process of fulfilling[n]a wish written on an ema.[n][f 1 1][e]
[f 2 1]> The wish on the ema was...[n][f 1 1][e]
[f 2 1][f 1 5]Ema[n]I have nothing to live for. I want to[n]recapture the joy of life.[n][f 1 1][e]
[f 2 1][f 1 5] [n]> You should report to the fox once the[n]wish on the ema has been fulfilled...[n][f 1 1][e]

[msg JINJYA_IRAINO6]
[f 2 1]> This is the shrine's main building.[n][f 1 1][e]
[f 2 1]> You are in the process of fulfilling[n]a wish written on an ema.[n][f 1 1][e]
[f 2 1]> The wish on the ema was...[n][f 1 1][e]
[f 2 1][f 1 5]Ema[n]I want to be able to converse better.[n]I don't want to hurt people with the[n]rude things I say when I'm nervous.[n][f 1 1][e]
[f 2 1][f 1 5] [n]> You should report to the fox once the[n]wish on the ema has been fulfilled...[n][f 1 1][e]

[msg JINJYA_IRAINO7]
[f 2 1]> This is the shrine's main building.[n][f 1 1][e]
[f 2 1]> You are in the process of fulfilling[n]a wish written on an ema.[n][f 1 1][e]
[f 2 1]> The wish on the ema was...[n][f 1 1][e]
[f 2 1][f 1 5]Ema[n]I'm scared of them, but I must get used[n]to them. I don't even want to write the[n]word... C A T S.[n][f 1 1][e]
[f 2 1][f 1 5] [n]> You should report to the fox once the[n]wish on the ema has been fulfilled...[n][f 1 1][e]

[msg JINJYA_IRAINO8]
[f 2 1]> This is the shrine's main building.[n][f 1 1][e]
[f 2 1]> You are in the process of fulfilling[n]a wish written on an ema[n][f 1 1][e]
[f 2 1]> The wish on the ema was...[n][f 1 1][e]
[f 2 1][f 1 5]Ema[n]My wallet is gone.[n]It vanished in the dense fog.[n]I yearn for some food.[n][f 1 1][e]
[f 2 1]I wish my wallet would return.[n][f 1 1][e]
[f 2 1][f 1 5] [n]> You should report to the fox once the[n]wish on the ema has been fulfilled...[n][f 1 1][e]

[msg JINJYA_IRAINO9]
[f 2 1]> This is the shrine's main building.[n][f 1 1][e]
[f 2 1]> You are in the process of fulfilling[n]a wish written on an ema.[n][f 1 1][e]
[f 2 1]> The wish on the ema was...[n][f 1 1][e]
[f 2 1][f 1 5]Ema[n]I want to see the legendary Guardian[n]of Shichiri Beach before I die.[n][f 1 1][e]
[f 2 1][f 1 5] [n]> You should report to the fox once the[n]wish on the ema has been fulfilled...[n][f 1 1][e]

[msg JINJYA_IRAIMATI]
[f 2 1]> ...The fox doesn't seem to be around.[n][f 1 1][e]
[f 2 1]> There doesn't seem to be any wishes on[n]the emas either...[n][f 1 1][e]
[f 2 1]> You decide to come back another[n]time...[n][f 1 1][e]

[msg JINJYA_NIGHT_KITSUNE]
[f 2 1]> ...The fox doesn't seem to be around.[n][f 1 1][e]
[f 2 1]> You decide to come back during the day...[n][f 1 1][e]

[msg ZINZYA_TUTORIAL]
[f 2 1]When you pray at the shrine, you can[n]strengthen the bonds you share with your[n]friends, or repair a relationship.[n][f 1 1][e]

[msg KITUNE_NG]
[f 2 1]> There's no need to be here...[n][f 1 1][e]

[msg KITUNE_NO]
[f 2 1]> There's no need to be here...[n][f 1 1][e]

[msg JINJYA_KITSUNE_KAIKINMAE]
[f 2 1]> This looks like the shrine's main[n]building.[n][f 1 1][e]
[f 2 1]> You have no business here.[n][f 1 1][e]

[msg JINJYA_KITSUNE_YOBU]
[f 2 1]> You made sure there was no one around[n]and called for the fox...[n][f 1 1][e]

[msg MSG_JINJYA_SAISENBAKO_AC]
[f 2 1]> ...It's the shrine's main building.[n][f 1 1][e]
[f 2 1]> Maybe you should pray...[n][f 1 1][e]

[msg MSG_JINJYA_SAISENBAKO_AC_2]
[f 2 1]> ...The fox doesn't seem to be around.[n]It appears that it doesn't come to the[n]shrine at night...[n][f 1 1][e]
[f 2 1]> ...[n][f 1 1][e]
[f 2 1]> Maybe you should pray...[n][f 1 1][e]

[msg MSG_JINJYA_OMAIRI_RESULT]
[f 2 1]> You calm yourself and clasp your hands[n]together...[n][f 1 1][e]
[f 2 1]> ...[n][f 1 1][e]
[f 2 1]> ......[n][f 1 1][e]
[f 2 1]> .........[n][f 1 1][e]

[msg TOIRE_TEST]
[f 2 1]> Tests are coming up soon.[n][f 1 1][e]
[f 2 1]> Maybe you should study so you're[n]well-prepared...[n][f 1 1][e]

[msg TOIRE_HONYAKU]
[f 2 1]> You feel your [f 0 1 1]Knowledge[f 0 1 0][n]has improved recently.[n][f 1 1][e]
[f 2 1][f 0 1 1]> Maybe you should look for a part-time[n]job that requires [f 0 1 1]Knowledge[f 0 1 0].[n][f 1 1][e]

[msg TOIRE_ORIDURU]
[f 2 1]> You feel your [f 0 1 1]Diligence[f 0 1 0][n]has improved recently.[n][f 1 1][e]
[f 2 1]> Maybe you should look for a part-time[n]job that requires [f 0 1 1]Diligence[f 0 1 0].[n][f 1 1][e]

[msg TOIRE_BYOUIN]
[f 2 1]> You feel that your [f 0 1 1]Diligence[f 0 1 0][n]is higher than average.[n][f 1 1][e]
[f 2 1]> Maybe you should look for a part-time[n]job that requires [f 0 1 1]Diligence[f 0 1 0].[n][f 1 1][e]

[msg TOIRE_KATEI]
[f 2 1]> You feel that your [f 0 1 1]Understanding[f 0 1 0][n]is exceptionally high.[n][f 1 1][e]
[f 2 1]> Maybe you should look for a part-time[n]job that requires [f 0 1 1]Understanding[f 0 1 0].[n][f 1 1][e]

[msg TOIRE_KITUNE]
[f 2 1]> You wonder how the fox at the shrine[n]is doing...[n][f 1 1][e]
[f 2 1]> Maybe you should pay it a visit...[n][f 1 1][e]

[msg TOIRE_KITUNE2]
[f 2 1]> You wonder how the fox at the shrine[n]is doing...[n][f 1 1][e]
[f 2 1]> It may have another request for you...[n][f 1 1][e]

[msg JINJYA_KITUNE]
[f 2 1]> You wonder how the fox at the shrine[n]is doing...[n][f 1 1][e]
[f 2 1]> Maybe you should pay it a visit during[n]the day...[n][f 1 1][e]

[msg JINJYA_KITUNE2]
[f 2 1]> You wonder how the fox at the shrine[n]is doing...[n][f 1 1][e]
[f 2 1]> It may have another request for you...[n]Maybe you should pay it a visit during[n]the day...[n][f 1 1][e]

[msg TOIRE_TUUHAN]
[f 2 1]> You remember that the home-shopping[n]program is on Sunday afternoons...[n][f 1 1][e]
[f 2 1]> What kind of merchandise is going to[n]be on sale this time...?[n][f 1 1][e]

[msg TOIRE_NAOTO]
[f 2 1]> You don't seem to have many chances to[n]converse with Naoto.[n][f 1 1][e]
[f 2 1]> Perhaps your relationship could grow[n]stronger if there was a catalyst...[n][f 1 1][e]

[msg TOIRE_KANJI]
[f 2 1]> You don't seem to have many chances to[n]converse with Kanji.[n][f 1 1][e]
[f 2 1]> Perhaps your relationship could grow[n]stronger if there was a catalyst...[n][f 1 1][e]

[msg TOIRE_UNDOUBU]
[f 2 1]> You are able to join a sports team.[n]You remembered that the clubs offer[n]tours to potential members.[n][f 1 1][e]

[msg TOIRE_BUNKABU]
[f 2 1]> You are able to join a cultural club.[n]You remembered that the clubs offer[n]tours to potential members.[n][f 1 1][e]

[msg TOIRE_MANAGER]
[f 2 1]> You don't seem to have many chances to[n]converse with your manager, Ai Ebihara.[n][f 1 1][e]
[f 2 1]> Perhaps your relationship could grow[n]stronger if you were more [f 0 1 1]courageous[f 0 1 0]...[n][f 1 1][e]

[msg TOIRE_OTOUTO]
[f 2 1]> You don't seem to have many chances to[n]converse with Saki Konishi's little[n]brother.[n][f 1 1][e]
[f 2 1]> Perhaps your relationship could grow[n]stronger if you were more [f 0 1 1]understanding[f 0 1 0]...[n][f 1 1][e]

[msg TOIRE_YUK]
[f 2 1]> In order to become more intimate with[n]someone, you realize you'll have to work[n]on your [f 0 1 1]Courage[f 0 1 0]...[n][f 1 1][e]

[msg TOIRE_DEN]
[f 2 1]> You realize that to mend your[n]relationship, you may need to learn how[n]to [f 0 1 1]express[f 0 1 0] yourself better...[n][f 1 1][e]

[msg TOIRE_NANAKO]
[f 2 1]> In order to become better friends with[n]Nanako, you realize you may have to work[n]on your [f 0 1 1]Expression[f 0 1 0]...[n][f 1 1][e]

[msg TOIRE_DOUJIMA]
[f 2 1]> In order to become better friends with[n]your uncle, you realize you may have to[n]work on your [f 0 1 1]Expression[f 0 1 0]...[n][f 1 1][e]

[msg TOIRE_TURI]
[f 2 1]> You wonder how the old fisherman is[n]doing...[n][f 1 1][e]

[msg TOIRE_HUUTOU_OK]
[f 2 1]> Is there a knack to envelop constructing?[n][f 1 1][e]

[msg TOIRE_HONYAKU_OK]
[f 2 1]> Is there a knack to translating?[n][f 1 1][e]

[msg TOIRE_ORIDURU_OK]
[f 2 1]> You remembered that you haven't[n]finished making the paper cranes...[n][f 1 1][e]
[f 2 1]> You get excited as you wonder who is[n]going to receive them...[n][f 1 1][e]

[msg TOIRE_GETABAKO_INFO]
[f 2 1]> You can't help but think that you[n]became a little more popular after you[n]scored so highly on the last exam.[n][f 1 1][e]
[f 2 1]> You wonder if maybe there's something[n]in your shoe locker...[n][f 1 1][e]

[msg TOIRE_BIKE_NEAR]
[f 2 1]> You realize that you haven't ridden[n]your scooter that much, despite getting[n]your license.[n][f 1 1][e]
[f 2 1]> Perhaps you should take your scooter[n]out for a ride around town...[n][f 1 1][e]

[msg TOIRE_BIKE_FAR_1]
[f 2 1]> You realize that you haven't ridden[n]your scooter that much, despite getting[n]your license.[n][f 1 1][e]
[f 2 1]> Perhaps you should go for a long ride[n]on your scooter...[n][f 1 1][e]

[msg TOIRE_BIKE_FAR_2]
[f 2 1]> You feel like you need more [f 0 1 1]courage[f 0 1 0][n]before you can take your bike out on[n]a long ride...[n][f 1 1][e]

[msg TOIRE_FARM_NO_PLANT]
[f 2 1]> You realize that you're not doing[n]anything with your garden.[n][f 1 1][e]
[f 2 1]> Maybe you should try growing[n]something...[n][f 1 1][e]

[msg TOIRE_FARM_SEEDLING]
[f 2 1]> You remember that you're growing[n]something in the garden. You should[n]tend to it sometime...[n][f 1 1][e]

[msg TOIRE_FARM_NUTS]
[f 2 1]> Come to think of it, the vegetables[n]you are growing should be ripe soon.[n][f 1 1][e]
[f 2 1]> You should harvest them...[n][f 1 1][e]

[msg TOIRE_FARM_SEASONEND_SOO]
[f 2 1]> Come to think of it, the vegetables[n]you are growing should have ripened a[n]while ago.[n][f 1 1][e]
[f 2 1]> You should harvest them before you[n]forget...[n][f 1 1][e]

[msg TOIRE_MUSITORI]
[f 2 1]> Come to think of it, you have yet to[n]collect bugs today...[n][f 1 1][e]

[msg TOIRE_GOTO_SEA]
[f 2 1]> You remember that you can take long[n]rides on your scooter.[n][f 1 1][e]
[f 2 1]> Maybe you should visit the beach one[n]day...[n][f 1 1][e]

[msg TOIRE_DOKUSYO]
[f 2 1]> You recall that you haven't finished[n]your book yet. Maybe you can read a[n]little when you get home...[n][f 1 1][e]

[msg TOIRE_REIZOU]
[f 2 1]> You wonder what kind of food is in the[n]fridge back home...[n][f 1 1][e]

[msg TOIRE_HANYOU]
[f 2 1]> No one is home again today...[n][f 1 1][e]
[f 2 1]> ......[n][f 1 1][e]
[f 2 1]> What are you going to do today...?[n][f 1 1][e]

[msg JINJYA_ITEM_01]
[f 2 1]> ...?[n][f 1 1][e]
[f 2 1]> You found something unusual...[n][f 1 1][e]
[f 2 1]> Obtained [f 2 5 3 65535 0] x 1.[n][f 1 1][e]

[msg JINJYA_ITEM_02]
[f 2 1]> ...?[n][f 1 1][e]
[f 2 1]> You found something sitting on the[n]side. It seems someone left it there...[n][f 1 1][e]
[f 2 1]> Obtained [f 2 5 3 65535 0] x 1.[n][f 1 1][e]

[msg JINJYA_ITEM_03]
[f 2 1]> ...?[n][f 1 1][e]
[f 2 1]> You found something sitting on the[n]side. It seems someone left it there...[n][f 1 1][e]
[f 2 1]> Obtained [f 2 5 3 65535 0] x 1.[n][f 1 1][e]

[msg MSG_JINJYA_YASHIRO]
[f 2 1]> It's a small shrine.[n][f 1 1][e]
[f 2 1]> There's a fortune box sitting there,[n]but there's nothing inside...[n][f 1 1][e]

[msg MSG_JINJYA_YASHIRO_RAIN]
[f 2 1]> It's a small shrine.[n][f 1 1][e]
[f 2 1]> There's a fortune box sitting there,[n]but there's nothing inside...[n][f 1 1][e]
[f 2 1]> It seems the fortunes are put away on[n]rainy days...[n][f 1 1][e]

[msg MSG_JINJYA_OMIKUZI_DRAW]
[f 2 1]> It's a small shrine. It looks like you[n]can draw matchmaking fortunes.[n][f 1 1][e]
[f 2 1]> It costs 200 yen. You have [f 2 4 20][n]yen on you. What should you do...?[n][f 1 1][e]

[sel SEL_JINJYA_OMIKUZI_DRAW top]
[f 2 1]Draw a fortune[e]
[f 2 1]Nothing[e]

[msg MSG_JINJYA_OMIKUZI_NOMON]
[f 2 1]> But you don't have enough money...[n][f 1 1][e]

[msg JINJYA_EMA]
[f 2 1]> It's an ema stand.[n][f 1 1][e]
[f 2 1]> Emas with various wishes written on[n]them are hung up here.[n][f 1 1][e]

[msg MSG_JINJYA_EMA_TEST]
[f 2 1]> Make a selection.[n][f 1 1][e]

[sel SELJINJYA_EMA_TEST top]
[f 2 1]Selection 1[e]
[f 2 1]Selection 2[e]
[f 2 1]Selection 3[e]
[f 2 1]Selection 4[e]
[f 2 1]Selection 5[e]
[f 2 1]Selection 6[e]
[f 2 1]Selection 7[e]
[f 2 1]Selection 8[e]

[msg JINJYA_MIKUZIKAKE]
[f 2 1]> There is a fortune stand.[n][f 1 1][e]
[f 2 1]> Old fortunes are tied to it.[n][f 1 1][e]

[msg MSG_NPC_OMIKUZI_MAN_00 [Old man]]
[f 2 1]Oh, aren't you the young man who gave[n]me that leaf?[n][f 1 1][e]
[f 2 1]I'm now able to visit my grandson thanks[n]to you![n][f 1 1][e]
[f 2 1]I thank the god of this shrine for[n]bringing the two of us together![n][f 1 1][e]
[f 2 1]I want to start restoring the shrine,[n]but it's just in such disrepair...[n][f 1 1][e]
[f 2 1]It'd like to make it a much better[n]shrine, but I don't have the money[n]to do any work on it.[n][f 1 1][e]
[f 2 1]So, I've decided to sell matchmaking[n]fortunes in the hopes of offsetting[n]some of the costs involved.[n][f 1 1][e]
[f 2 1]Usually I only set them out on special[n]occasions like New Year's, but this is[n]for the good of the shrine![n][f 1 1][e]
[f 2 1]I got these matchmaking fortunes from[n]a famous shrine, so they work wonders![n][f 1 1][e]
[f 2 1]You should try it sometime. I'm sure it'll[n]get you closer to the girl of your dreams![n][f 1 1][e]
[f 2 1]Oh, but I put the fortunes away on rainy[n]days, so watch out for that.[n][f 1 1][e]
[f 2 1]Now, I need to go see my grandson today![n]Bye now, my boy![n][f 1 1][e]

[msg MSG_NPC_OMIKUZI_MAN_00_M [Old man]]
[f 2 1]Oh, aren't you the young man who gave[n]me that leaf?[n][f 1 1][e]
[f 2 1]I'm now able to visit my grandson thanks[n]to you![n][f 1 1][e]
[f 2 1]I thank the god of this shrine for[n]bringing the two of us together![n][f 1 1][e]
[f 2 1]I've started restoring the shrine, but[n]I need to make it even better than it[n]was before![n][f 1 1][e]
[f 2 1]However... I don't have have the money[n]to start yet.[n][f 1 1][e]
[f 2 1]So, I've decided to sell matchmaking[n]fortunes in the hopes of offsetting[n]some of the costs involved.[n][f 1 1][e]
[f 2 1]Usually I only set them out on special[n]occasions like New Year's, but this is[n]for the good of the shrine![n][f 1 1][e]
[f 2 1]I got these matchmaking fortunes from[n]a famous shrine, so they work wonders![n][f 1 1][e]
[f 2 1]You should try it sometime. I'm sure it'll[n]get you closer to the girl of your dreams![n][f 1 1][e]
[f 2 1]Oh, but I put the fortunes away on rainy[n]days, so watch out for that.[n][f 1 1][e]
[f 2 1]Now, I need to go see my grandson today![n]Bye now, my boy![n][f 1 1][e]

[msg MSG_NPC_OMIKUZI_MAN_01]
[f 2 1]> The old man leaves energetically.[n][f 1 1][e]

[msg HELP_OMIKUZI]
[f 2 1]You can now draw fortunes.[n][f 1 1][e]
[f 2 1]By drawing a fortune while thinking about[n]a Social Link you wish to strengthen, [f 0 1 2]you[n]can deepen your relationship just a bit[f 0 1 0].[n][f 1 1][e]
[f 2 1][f 0 1 2]Spending time with the person will deepen[n]the relationship more than a fortune[f 0 1 0]. Use[n]fortunes to improve relationships with[n]people who are currently unavailable.[n][f 1 1][e]

[msg BAITO_HOIKU]
[f 2 1]> It's the bus stop. You can work at[n]the day care center today.[n][f 1 1][e]

[msg BAITO_HOIKU2]
[f 2 1]> Take the bus to the hill overlooking[n]town for day care work?[n][f 1 1][e]

[msg BAITO_HOIKU_YES_KAIKINMA]
[f 2 1]> You decided to go to the day care[n]center.[n][f 1 1][e]

[msg BAITO_HOIKU_YES]
[f 2 1][f 5 8 0 10]> You decided to work at the day care[n]center.[n][f 1 1][e]

[msg BAITO_HOIKU_NO]
[f 2 1]> You decided not to go.[n][f 1 1][e]

[msg BAITO_HOIKU_MAX]
[f 2 1]> Eri and Yuuta are no longer at the [n]day care center. Go to work anyway?[n][f 1 1][e]

[msg BAITO_HOIKU_RANKUP_OK]
[f 2 1]> You feel your relationship with Eri[n]will deepen...[n][f 1 1][e]

[msg BAITO_HOIKU_RANKUP_MADA]
[f 2 1]> You feel your relationship with Eri[n]won't deepen just yet...[n][f 1 1][e]

[msg EXIT_NIGHT_HOUSE_OK]
[f 2 1]> What will you do at night?[n][f 1 1][e]

[msg EXIT_NIGHT_STREET_OK]
[f 2 1]> Where will you go?[n][f 1 1][e]

[sel SEL_NIGHT_PLACE top]
[f 2 1]Shopping District[e]
[f 2 1]Shopping District North[e]
[f 2 1]Shopping District South[e]
[f 2 1]Shrine[e]
[f 2 1]Riverbank[e]
[f 2 1]Return home[e]

[msg SEL_ORDER_NIGHT_PLAY]
[f 2 1]Which part-time job will you go to?[n][f 1 1][e]

[msg GO_NIGHT_JOB]
[f 2 1]> Which part-time job will you go to?[n][f 1 1][e]

[sel BAITO_WANT2GO_YESNO_KAIK top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[sel BAITO_WANT2GO_YESNO top]
[f 2 1]Yes[e]
[f 2 1]Check Social Link rank[e]
[f 2 1]No[e]

[sel SEL_NIGHT_JOB top]
[f 2 1]Tutoring[e]
[f 2 1]Hospital janitor[e]
[f 2 1]Junes stocker[e]
[f 2 1]Don't go[e]

[msg HLP_COMMU_NEW]
[f 2 1][f 4 7 0]> Come to think of it...[n][f 1 1][e]
[f 2 1]> You recall Igor's words...[n][f 1 1][e]
[f 2 1][f 1 5]Igor[n][f 4 6 33 1 0 1]> "As you form bonds by becoming involved[n]with others, your own Social Links will[n]gradually develop.[n][f 1 1][e]
[f 2 1]> "The power of these Social Links is[n]what will determine your Persona's[n]abilities."[n][f 1 1][e]
[f 2 1][f 1 5] [n][f 4 7 0]> ...You wonder if you can create a[n]Social Link here...[n][f 1 1][e]

[msg COMU_PERSONA_DOUZOKUSEI]
[f 2 1]> Since you have [f 0 1 1][f 2 4 5][f 0 1 0],[n]a Persona of the [f 2 4 2] Arcana,[n]you two might get along well...[n][f 1 1][e]

[msg COMU_PERSONA_ZOKUSEI]
[f 2 1]> [f 2 4 0]...[n][f 2 4 1] Social Link,[n]rank [f 0 1 2][f 2 4 4][f 0 1 0].[n][f 1 1][e]
[f 2 1]> You will discover Personas with an[n]affinity for the [f 2 4 2] Arcana...[n]the [f 2 4 3][n][f 1 1][e]
[f 2 1]> You can see the power of Personas of[n]the [f 2 4 2] Arcana...[n][f 1 1][e]

[msg PER_KOE]
[f 2 1] [f 2 4 1], Level [f 2 4 0][n] [n] Available skills:[n]  [f 2 4 2][n]  [f 2 4 3][n]  [f 2 4 4][n][f 1 1][e]

[msg ZOKUSEI_NOMORE]
[f 2 1]> All of the Personas of this Arcana have[n]been unlocked...[n][f 1 1][e]

[msg ZOKUSEI_NOTYET]
[f 2 1]> There seems to be some kind of power[n]still hidden...[n][f 1 1][e]

[msg BAITO_JUNES_KOKUTI]
[f 2 1]> You can work at Junes today.[n][f 1 1][e]

[msg BAITO_JUNES_INFO]
[f 2 1]> If you work at Junes, you might become[n]closer to Yosuke.[n][f 1 1][e]

[msg BAITO_JUNES]
[f 2 1]> Go work at Junes?[n][f 1 1][e]

[msg BAITO_JUNES_YES]
[f 2 1]> You decided to work at Junes.[n][f 1 1][e]

[msg BAITO_JUNES_NO]
[f 2 1]> You decided to skip it.[n][f 1 1][e]

[msg BAITO_KATEI_KOKUTI]
[f 2 1]> You can work as a tutor today...[n][f 1 1][e]

[msg BAITO_KATEI2]
[f 2 1]> Tutor today?[n][f 1 1][e]

[msg BAITO_KATEI_YES_KAIKINMA]
[f 2 1]> You decided to work as a tutor today.[n][f 1 1][e]

[msg BAITO_KATEI_YES]
[f 2 1][f 5 8 0 10]> You decided to work as a tutor today.[n][f 1 1][e]

[msg BAITO_KATEI_NO]
[f 2 1]> You decided to skip tutoring.[n][f 1 1][e]

[msg YUUKI_DRINK_HAVE]
[f 2 1]> You remember that you have a juice that[n]might help develop [f 0 1 1]Courage[f 0 1 0].[n][f 1 1][e]

[msg KONKI_DRINK_HAVE]
[f 2 1]> You remember that you have a juice that[n]might help develop [f 0 1 1]Diligence[f 0 1 0].[n][f 1 1][e]

[msg DENTATU_DRINK_HAVE]
[f 2 1]> You remember that you have a juice tha[n] might help develop [f 0 1 1]Expression[f 0 1 0].[n][f 1 1][e]

[msg KANYOUSA_DRINK_HAVE]
[f 2 1]> You remember that you have a juice that[n]might help develop [f 0 1 1]Understanding[f 0 1 0].[n][f 1 1][e]

[msg AIYA_DRINK_HAVE]
[f 2 1]> You remember that you have a juice that[n]makes you hungry.[n][f 1 1][e]

[sel SEL_DRINK top]
[f 2 1]Drink [f 2 4 0][e]
[f 2 1]Drink [f 2 4 1][e]
[f 2 1]Don't drink anything[e]

[sel SEL_DRINK_2 top]
[f 2 1]Drink [f 2 4 0][e]
[f 2 1]Don't drink anything[e]

[msg DRINK_1]
[f 2 1]> You drank [f 2 4 0].[n][f 1 1][e]

[msg DRINK_2]
[f 2 1]> You drank [f 2 4 1].[n][f 1 1][e]

[msg NOT_DRINK]
[f 2 1]> You decided not to drink anything.[n][f 1 1][e]

[msg BAITO_KATEI_RANKUP_OK]
[f 2 1]> You feel your relationship with Shu[n]will deepen...[n][f 1 1][e]

[msg BAITO_KATEI_RANKUP_MADA]
[f 2 1]> You feel your relationship with Shu[n]won't deepen just yet...[n][f 1 1][e]

[msg BAITO_BYOUIN_KOKUTI]
[f 2 1]> You can work as a janitor at the[n]hospital today.[n][f 1 1][e]

[msg BAITO_BYOUIN2]
[f 2 1]> Go work at the hospital?[n][f 1 1][e]

[msg BAITO_BYOUIN_YES_KAIKINM]
[f 2 1]> You decided to work at the hospital.[n][f 1 1][e]

[msg BAITO_BYOUIN_YES]
[f 2 1][f 5 8 0 10]> You decided to work at the hospital.[n][f 1 1][e]

[msg BAITO_BYOUIN_MAX]
[f 2 1]> Sayoko is no longer at the hospital...[n]Do you want to go to work there anyway?[n][f 1 1][e]

[msg BAITO_BYOUIN_NO_KAIKINMA]
[f 2 1]> You decide to skip it.[n][f 1 1][e]

[msg BAITO_BYOUIN_NO]
[f 2 1]> You decide to skip it.[n][f 1 1][e]

[msg BAITO_BYOUIN_RANKUP_OK]
[f 2 1]> You feel your relationship with[n]Sayoko will deepen...[n][f 1 1][e]

[msg BAITO_BYOUIN_RANKUP_MADA]
[f 2 1]> You feel your relationship with Sayoko[n]won't deepen just yet...[n][f 1 1][e]

[msg TURI_EXEC]
[f 2 1]> You decided to go fishing tonight.[n][f 1 1][e]

[msg TURI_ESA_HAZIKI]
[f 2 1]> ...You didn't have [n][f 4 4 3 1 1016], though.[n][f 1 1][e]

[msg SIGEMI]
[f 2 1]> You see something on the ground...[n][f 1 1][e]
[f 2 1]> It's a wallet.[n][f 1 1][e]
[f 2 1]> Obtained [f 4 4 3 1 1231].[n][f 1 1][e]

[msg POST_NONE]
[f 2 1]> It's the mailbox...[n][f 1 1][e]

[msg POST_OUBO_OK_00]
[f 2 1]> It's the mailbox.[n][f 1 1][e]

[msg POST_OUBO_OK_01]
[f 2 1]> You have sufficient number of[n][f 4 4 3 1 849]s for a redemption.[n]You recall...[n][f 1 1][e]
[f 2 1]> You can choose either the "Plentiful[n]Combo" or the "Rare Combo."[n][f 1 1][e]
[f 2 1]> Both combos require 3 [f 4 4 3 1 849]s[n]each. Which do you want to order?[n][f 1 1][e]

[sel TUUHAN_OUBO_SEL top]
[f 2 1]Plentiful Combo[e]
[f 2 1]Rare Combo[e]
[f 2 1]Never mind[e]

[msg POST_OUBO_OK_COURSE_1]
[f 2 1]> You decided to choose the "Plentiful[n]Combo."[n][f 1 1][e]
[f 2 1]> You can hardly wait for it to arrive.[n][f 1 1][e]

[msg POST_OUBO_OK_COURSE_2]
[f 2 1]> You decided to choose the "Rare[n]Combo."[n][f 1 1][e]
[f 2 1]> You can hardly wait for it to arrive.[n][f 1 1][e]

[msg POST_OUBO_NG]
[f 2 1]> You are saving up your [f 4 4 3 1 849]s[n]to redeem a combo.[n][f 1 1][e]

[msg POST_OUBO_TARINAI]
[f 2 1]> You recall that you can redeem a[n]combo by collecting 3 [f 4 4 3 1 849]s.[n][f 1 1][e]

[msg POST_CANT_USE_SOON]
[f 2 1]> It's the mailbox. There's a notice[n]near the mail slot...[n][f 1 1][e]
[f 2 1]> "Due to changes in the collection[n]system, this mailbox will temporarily be[n]out of service beginning on the 10th."[n][f 1 1][e]
[f 2 1]> "Please deposit any mail [f 0 1 2]by the 5th[n]of the month[f 0 1 0]."[n][f 1 1][e]
[f 2 1]> It appears you won't be able to use[n]the mailbox soon...[n][f 1 1][e]

[msg POST_CANT_USE]
[f 2 1]> It's the mailbox. There's a notice[n]near the mail slot...[n][f 1 1][e]
[f 2 1]> "Due to changes in the collection[n]system, this mailbox is currently out[n]of use."[n][f 1 1][e]
[f 2 1]> "Please visit the post office to turn[n]in any mail you have for delivery. We[n]apologize for the inconvenience."[n][f 1 1][e]
[f 2 1]> It appears you won't be able to use[n]the mailbox for a while...[n][f 1 1][e]

[msg POST_GOJITU]
[f 2 1]> It's the mailbox.[n][f 1 1][e]
[f 2 1]> There's no reason for you to use it[n]right now.[n][f 1 1][e]

[msg GOJITUDAN_ALLSUMI]
[f 2 1]> You have said goodbye to all the[n]people you have formed close bonds[n]with...[n][f 1 1][e]
[f 2 1]> You should return to your house to[n]prepare for tomorrow...[n][f 1 1][e]

[msg GOJITUDAN_MADA]
[f 2 1]> There are others you share a close[n]bond with...[n][f 1 1][e]
[f 2 1]> You should go say goodbye to them...[n][f 1 1][e]

[msg GOJITUDAN_ALLSUMI_GUIDE]
[f 2 1]> You still feel a bit reluctant...[n][f 1 1][e]
[f 2 1]> Perhaps it may be best to stop by[n][f 0 1 2]the place you spent time with your[n]friends[f 0 1 0] one last time.[n][f 1 1][e]

[msg SAKAYA]
[f 2 1]> It's a liquor store.[n][f 1 1][e]
[f 2 1]> Cases of various alcohols are stacked[n]on top of each other...[n][f 1 1][e]

[msg SOUZAI_STOP]
[f 2 1]> A bunch of appetizing dishes are out[n]on display...[n][f 1 1][e]
[f 2 1]> But the owner is nowhere to be found...[n][f 1 1][e]

[msg SOUZAI]
[f 2 1]> It's Souzai Daigaku.[n][f 1 1][e]
[f 2 1][f 1 5]Lady[n]Welcome! Our food is freshly made and[n]tastes incredibly great![n][f 1 1][e]
[f 2 1][f 1 5] [n]> What do you want to buy?[n][f 1 1][e]

[msg SOUZAI_NIGHT]
[f 2 1]> It seems the store has closed for[n]today...[n][f 1 1][e]

[sel SEL_SOUZAI top]
[f 2 1]Super croquette[e]
[f 2 1]Grilled steak croquette[e]
[f 2 1]Steak skewer[e]
[f 2 1]Don't buy anything[e]

[sel SEL_SOUZAI2 top]
[f 2 1]Buy[e]
[f 2 1]Leave[e]

[msg SOUZAI_NO]
[f 2 1]> You can't afford that.[n][f 1 1][e]

[msg SOUZAI1_NEDAN_RAIN [Lady]]
[f 2 1]The [f 2 4 0] is 100 yen. You're[n]lucky that we have some left! It's[n]probably because it's raining.[n][f 1 1][e]

[msg SOUZAI1_NEDAN_SNOW [Lady]]
[f 2 1]The [f 2 4 0] is 100 yen. You're[n]lucky that we have some left! It's[n]probably because it's snowing.[n][f 1 1][e]

[msg SOUZAI1_NEDAN [Lady]]
[f 2 1]The ingredients are a secret, but I'm[n]sure you'll love it![n][f 1 1][e]
[f 2 1]> You currently have [f 2 4 20] yen.[n]Buy [f 2 5 3 65535 1]?[n][f 1 4][e]

[msg SOUZAI2_NEDAN [Lady]]
[f 2 1]The [f 2 4 0] is 150 yen.[n][f 1 1][e]
[f 2 1]I like the combination of diced meat[n]and potato.[n][f 1 1][e]
[f 2 1]> You currently have [f 2 4 20] yen.[n]Buy [f 2 5 3 65535 1]?[n][f 1 4][e]

[msg SOUZAI3_NEDAN [Lady]]
[f 2 1]Our [f 2 4 0] is 320 yen. [n][f 1 1][e]
[f 2 1]This is our signature dish here![n]It tastes the best![n][f 1 1][e]
[f 2 1]> You currently have [f 2 4 20] yen.[n]Buy [f 2 5 3 65535 1]?[n][f 1 4][e]

[msg SOUZAI_URI [Lady]]
[f 2 1]You just bought the last one. Thanks[n]for shopping at Souzai Daigaku.[n][f 1 1][e]

[msg SOUZAI_URI_KORO [Lady]]
[f 2 1]Sorry, but that's sold out already.[n]It's really popular.[n][f 1 1][e]

[msg SOUZAI_URI_KORO_RAIN [Lady]]
[f 2 1]There's less competition on rainy days,[n]you know.[n][f 1 1][e]

[msg SOUZAI_URI_KORO_SNOW [Lady]]
[f 2 1]There's less competition on snowy days,[n]you know.[n][f 1 1][e]

[msg SOUZAI1 [Lady]]
[f 2 1]Thank you! Have a nice day.[n][f 1 1][e]
[f 2 1]> Purchased [f 4 4 3 1 850].[n][f 1 4][e]

[msg SOUZAI2 [Lady]]
[f 2 1]Thank you! Have a nice day.[n][f 1 1][e]
[f 2 1]> Purchased [f 4 4 3 1 851].[n][f 1 4][e]

[msg SOUZAI3 [Lady]]
[f 2 1]Thank you! Have a nice day.[n][f 1 1][e]
[f 2 1]> Purchased [f 4 4 3 1 852].[n][f 1 4][e]

[msg SOUZAI_GOJITU]
[f 2 1]> It's Souzai Daigaku.[n][f 1 1][e]
[f 2 1][f 1 5]Lady[n]I'm sorry, but we are sold out of[n]everything today.[n][f 1 1][e]
[f 2 1]Please come back another day.[n][f 1 1][e]

[msg SOUZAI_MOHOU]
[f 2 1]> It's Souzai Daigaku.[n][f 1 1][e]
[f 2 1]> You asked if a student was working[n]here part-time.[n][f 1 1][e]
[f 2 1][f 1 5]Lady[n]Wh-Where'd you hear that from? I told him[n]not to tell anyone...[n][f 1 1][e]
[f 2 1]...Anyway. Yes, he did work here for a[n]short time.[n][f 1 1][e]
[f 2 1]But this was a while ago. I had him[n]cutting the meat, but he got bored with[n]the work very quickly.[n][f 1 1][e]
[f 2 1]Hmm... I remember he had black eyes.[n][f 1 1][e]
[f 2 1]And what else...[n][f 1 1][e]
[f 2 1]...Oh yeah. He said the person who[n]worked here before him was his[n]classmate during middle school...[n][f 1 1][e]
[f 2 1]I see that kid--his classmate--around[n]here sometimes. Maybe you should talk[n]to him when you see him.[n][f 1 1][e]
[f 2 1]I don't know if you'll find him today,[n]but he recently dyed his hair golden[n]brown, so he should be easy to spot.[n][f 1 1][e]
[f 2 1]> You've obtained a lead about the boy.[n][f 1 4][e]
[f 2 1]> If you can find his golden brown-[n]haired classmate, you'll probably[n]obtain information about the boy...[n][f 1 4][e]

[msg SOUZAI_MOHOU_2 [Lady]]
[f 2 1]He was so gloomy. He never talked to[n]anyone. He never even said hello.[n][f 1 1][e]
[f 2 1]He grew up around here, so if you want[n]to know what he looks like, why don't[n]you ask someone for a yearbook?[n][f 1 1][e]
[f 2 1]> You may obtain more information about[n]the boy if you ask the local students...[n][f 1 4][e]
[f 2 1]Well then, what would you like? Our food is[n]freshly made and tastes incredibly great![n][f 1 1][e]
[f 2 1]> What do you want to buy?[n][f 1 4][e]

[msg MARGARET_GOJITUDAN_01 [Margaret]]
[f 2 1][f 4 6 34 1 0 1]Oh... Hello.[n][f 1 1][e]

[msg MSG_0320_AFTER_E428002]
[f 2 1]> It began raining...[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED]
[f 2 1]> There's no reason for you to be here...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO]
[f 2 1]> You feel that you haven't finished[n]saying farewell to everyone...[n][f 1 1][e]
[f 2 1]> Return home and prepare for tomorrow...?[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL]
[f 2 1]> You feel that you have said farewell to[n]everyone precious to you.[n][f 1 1][e]
[f 2 1]> Return home and prepare for tomorrow...?[n][f 1 1][e]

[msg MSG_0320_RETURN_HOME]
[f 2 1]> Return home and prepare for tomorrow...?[n][f 1 1][e]

[msg MSG_0320_DOUJIMA_SEARCH]
[f 2 1]> You should look for Dojima and Nanako...[n][f 1 1][e]

[msg JIHAN_STOP]
[f 2 1]> It's a beverage vending machine.[n][f 1 1][e]
[f 2 1]> However, all the drinks are sold out.[n]There's nothing for you to buy...[n][f 1 1][e]

[msg JIHAN_LOT_STOP]
[f 2 1]> It's a beverage vending machine with[n]a roulette game.[n][f 1 1][e]
[f 2 1]> However, all the drinks are sold out.[n]There's nothing for you to buy...[n][f 1 1][e]

[msg JIHAN]
[f 2 1]> This vending machine sells drinks for[n]120 yen each. You have [f 2 4 20] yen.[n]What would you like to buy?[n][f 1 1][e]

[msg JIHAN_LOT]
[f 2 1]> This vending machine sells drinks for[n]120 yen each. You have [f 2 4 20] yen.[n]What would you like to buy?[n][f 1 1][e]

[msg JIHAN_URIKIRE_RE]
[f 2 1]> It is currently out of drinks...[n]It should be restocked next week.[n][f 1 1][e]

[msg JIHAN_URIKIRE]
[f 2 1]> It looks like all the drinks are[n]sold out...[n][f 1 1][e]

[sel SEL_JIHAN top]
[f 0 5 65278][f 2 1]Dr. Salt NEO[e]
[f 0 5 65278][f 2 1]Second Maid[e]
[f 0 5 65278][f 2 1]The Natural[e]
[f 0 5 65278][f 2 1]Buy everything[e]
[f 0 5 65278][f 2 1]Leave[e]

[sel SEL_JIHAN2 top]
[f 2 1]Orange Smash[e]
[f 2 1]TaP Soda[e]
[f 2 1]Cancel[e]

[msg JIHAN_NO]
[f 2 1]> You can't afford that...[n][f 1 1][e]

[msg MOTENAI]
[f 2 1]> You can't carry any more...[n][f 1 1][e]

[msg JIHAN_LOT_HAZURE]
[f 2 1]> It seems you didn't win anything...[n][f 1 1][e]

[msg JIHAN_ATARI]
[f 2 1]> You've won a prize![n][f 1 1][e]
[f 2 1]> You've won another drink from the[n]roulette machine. Which one will you[n]pick?[n][f 1 1][e]

[msg JIHAN_ATARI_CONTINUE]
[f 2 1]> You've won yet another prize![n][f 1 1][e]
[f 2 1]> You've won another drink from the[n]roulette machine. Which one will you[n]pick?[n][f 1 1][e]

[msg JIHAN_HAZURE]
[f 2 1]> The roulette has ended...[n][f 1 1][e]

[msg JIHAN_GET_JUICE]
[f 2 1]> Purchased [f 2 5 3 65535 0].[n][f 1 1][e]

[msg JIHAN_GET_ATARI]
[f 2 1]> Obtained [f 2 5 3 65535 0] for free.[n][f 1 1][e]

[msg JITEN]
[f 2 1]> It's a bicycle store, but the shutters[n]are closed.[n][f 1 1][e]
[f 2 1]> There's a notice saying, "The shop is[n]closed."[n][f 1 1][e]

[msg TOKOYA]
[f 2 1]> The sign says "Nishino Barber," but[n]the shutters are closed.[n][f 1 1][e]
[f 2 1]> There's a notice saying, "The shop is[n]closed."[n][f 1 1][e]

[msg MOKEI]
[f 2 1]> It's a hobby shop, but the shutters[n]are closed.[n][f 1 1][e]

[msg MOKEI_NIGHT_1STMESSAGE [Hobby shop owner]]
[f 2 1]> This seems to be a hobby shop.[n]...You can hear someone's voice from[n]inside.[n][f 1 4][e]
[f 2 1]Oh, it's you. Thanks for that last time.[n][f 1 1][e]
[f 2 1]I'm sorting out the leftover models,[n]now that the store's closed.[n][f 1 1][e]
[f 2 1]Do you want another one? I know you'll[n]at least put it together, so you can[n]have one for free if you want.[n][f 1 1][e]

[msg MOKEI_NIGHT [Hobby shop owner]]
[f 2 1]Ah, it's you. I just found something good.[n][f 1 1][e]

[sel SEL_MOKEI_GET top]
[f 2 1]Get a new model[e]
[f 2 1]Turn down[e]

[msg MOKEI_NIGHT_MODEL_MAKING [Hobby shop owner]]
[f 2 1]Huh? Did you finish the last one?[n][f 1 1][e]
[f 2 1]When you're done with the one you're[n]working on, I'll give you this. Let[n]me know when you come back later.[n][f 1 1][e]

[msg MOKEI_NIGHT_GET]
[f 2 1]> Obtained [f 2 5 3 65535 0].[n][f 1 1][e]

[sel SEL_MOKEI_WHICH top]
[f 2 1]Take a model robot[e]
[f 2 1]Take a model scooter[e]
[f 2 1]Don't take anything[e]

[msg MOKEI_NIGHT_BYE [Hobby shop owner]]
[f 2 1]I see. Well, come back again.[n][f 1 1][e]

[msg MOKEI_NIGHT_MODEL_NOTPUR [Hobby shop owner]]
[f 2 1]That last one I gave you was the last[n]of the robots. Thanks for making them[n]all![n][f 1 1][e]

[msg MOKEI_NIGHT_MODEL_NOTBIK [Hobby shop owner]]
[f 2 1]That last one I gave you was the last[n]of the scooter models. Thanks for making[n]them all![n][f 1 1][e]

[msg MOKEI_NIGHT_MODEL_NOTSEL [Hobby shop owner]]
[f 2 1]Ah, it's you. to tell you the truth...[n]I don't have anything more to give you.[n][f 1 1][e]
[f 2 1]I gave some away to local kids and some[n]hardcore fans. All I have left are a[n]few I'm going to build myself.[n][f 1 1][e]
[f 2 1]Seeing you made me realize that in the[n]end, models give my life meaning.[n][f 1 1][e]
[f 2 1]I may have closed up the shop, but I[n]don't have to cut them out of my life.[n]You're my final customer. Thank you.[n][f 1 1][e]

[msg MOKEI_NIGHT_MODEL_NOTSEL_2 [Hobby shop owner]]
[f 2 1]Ah, good evening. Are you treating[n]the models you made right?[n][f 1 1][e]
[f 2 1]Just knowing that you're lining them[n]up on your shelf and admiring them once[n]in a while makes me feel better.[n][f 1 1][e]
[f 2 1]If only my daughter was skilled in[n]crafts...[n][f 1 1][e]

[msg MOKEI_NIGHT_BUY [Hobby shop owner]]
[f 2 1]I'll look for another model to give you,[n]so come back when you're done with that.[n][f 1 1][e]

[msg MOKEI_GET_SHU_BIKE [Hobby shop owner]]
[f 2 1]There aren't many varieties of this model.[n]This is a domestic brand, so there's no[n]need to fill in any cracks![n][f 1 1][e]
[f 2 1]It's round all over, making it fun to[n]sand. Man, I'd just polish it clean[n]every day![n][f 1 1][e]
[f 2 1]But if you sand too much, you'll end up[n]not just shaving the seams, but the molds[n]as well, and then you'll want to reshape--[n][f 1 1][e]
[f 2 1]...Huh? Oh, that's enough? All right...[n]Anyway, I'm looking forward to seeing[n]you finish it![n][f 1 1][e]

[msg MOKEI_GET_YOU_BIKE [Hobby shop owner]]
[f 2 1]This model makes scooter buffs drool![n]The smaller parts can snap easily, so[n]you'll have to be gentle with it.[n][f 1 1][e]
[f 2 1]The single-piece frame is what makes this[n]model so great. Just don't get too excited[n]about buffing and scratches on the edges![n][f 1 1][e]
[f 2 1]Now, to make the edges stand out, you'll[n]want to wrap your sandpaper around a[n]Topsicle stick, or else you'll warp the--[n][f 1 1][e]
[f 2 1]What? Oh, so you've got it? I see...[n]Well, I'm looking forward to seeing[n]how it turns out for you![n][f 1 1][e]

[msg MOKEI_GET_CHI_BIKE [Hobby shop owner]]
[f 2 1]This model's based on a bike with some[n]real history. It's an all-purpose machine[n]used for many different jobs![n][f 1 1][e]
[f 2 1]Because it's such a beloved icon of[n]industry, it's worth doing a real[n]quality job. I'm talking putty and filler![n][f 1 1][e]
[f 2 1]Now, once you've filled any cracks with[n]putty, use a knife to shave it away, then[n]polish until it looks like a single piece--[n][f 1 1][e]
[f 2 1]What's that? You know already? Well, all[n]right... But I expect to see that knowledge[n]put to use building this one![n][f 1 1][e]

[msg MOKEI_GET_YUK_BIKE [Hobby shop owner]]
[f 2 1]Now THIS is an elusive model! My shop[n]might be the only one in a hundred[n]miles to have one in stock.[n][f 1 1][e]
[f 2 1]It's a classic, so it has a lot of parts.[n]That's when you start getting fancy with[n]painting![n][f 1 1][e]
[f 2 1]Getting that deep luster of the real paint[n]while keeping the mirror finish is very[n]impressive. Here's what you do: take some--[n][f 1 1][e]
[f 2 1]Huh? Oh, so you'll figure it out on your[n]own, eh? I wish you luck, then! Don't[n]mess this special model up![n][f 1 1][e]

[msg MOKEI_GET_RIS_BIKE [Hobby shop owner]]
[f 2 1]This is a cute one, eh? Honestly, the[n]real thing is like a plastic model...[n]I just want to customize it![n][f 1 1][e]
[f 2 1]It's a simple build, but it has a lot[n]of parts, so follow the instructions[n]when you're cutting it from the frame.[n][f 1 1][e]
[f 2 1]That moment of ecstacy when you get that[n]unique cowling rounded after hours of[n]patient sanding, the symmetry just right--[n][f 1 1][e]
[f 2 1]Oh, yeah. I'm sure you'll do just fine[n]with it. I'm looking forward to seeing[n]how you do![n][f 1 1][e]

[msg MOKEI_GET_NAO_BIKE [Hobby shop owner]]
[f 2 1]This might look like a Japanese scooter,[n]but it's actually an import! It's used[n]by the police in its home country.[n][f 1 1][e]
[f 2 1]This is a foreign model kit, too, but[n]don't worry about the instructions.[n]They're all wrong and don't match anyway![n][f 1 1][e]
[f 2 1]These are actually the most fun kind of[n]model to make! You just look at the parts[n]and imagine how to put them together, so--[n][f 1 1][e]
[f 2 1]...Zoning out already? Aw, all right.[n]Anyway, I'm looking forward to seeing[n]what your imagination does to this.[n][f 1 1][e]

[msg MOKEI_GET_PURAMO3 [Hobby shop owner]]
[f 2 1]This mecha is from the same series as[n]the other one I gave you. This one got[n]classified as "universal destruction"-grade![n][f 1 1][e]
[f 2 1]The joints use poly-caps, so it's posable![n]It's fun to display the completed machine![n][f 1 1][e]
[f 2 1]Poly-caps are limited only by your[n]imagination, but there's that feeling of[n]despair when you lose one or it pops out--[n][f 1 1][e]
[f 2 1]...Huh? Oh, never mind. Okay, well, I[n]want to see how this one turns out![n][f 1 1][e]

[msg MOKEI_GET_PURAMO4 [Hobby shop owner]]
[f 2 1]This is another mecha from the same series.[n]It's bright, it's cute, and it can shoot[n]down fighter jets![n][f 1 1][e]
[f 2 1]It's fairly simple to build, and the[n]coloring makes adding details to it[n]a real blast![n][f 1 1][e]
[f 2 1]But if you sand too hard, you'll have to[n]redetail, and it'll get dirtier, and you'll[n]have to pass that off as weathering, which--[n][f 1 1][e]
[f 2 1]...Huh? What? Hey, are you even listening?[n]I see... Anyway, you go ahead and do a[n]good job on this one, okay?[n][f 1 1][e]

[msg MOKEI_GET_PURAMO5 [Hobby shop owner]]
[f 2 1]This is another mecha from that same[n]series. It's an amphibious powerhouse[n]that can combine with other machines![n][f 1 1][e]
[f 2 1]Models these days are so good. Just[n]putting them together is enough to make[n]them look like the real thing.[n][f 1 1][e]
[f 2 1]That's why the true mark of a skilled[n]modelbuilder is battle damage! Bullet[n]holes, precision dents and welds...[n][f 1 1][e]
[f 2 1]What's that? You've heard enough?[n]I see... All right, you do what you can[n]with this, and we'll see how good you are![n][f 1 1][e]

[msg MOKEI_GET_PURAMO6 [Hobby shop owner]]
[f 2 1]This is the last mecha in the line I've[n]been giving you. This machine is tough[n]and sturdy, like an earth goddess![n][f 1 1][e]
[f 2 1]It's a simple build, but each part is big,[n]making painting a chore! Having an airbrush[n]will save you a ton of time![n][f 1 1][e]
[f 2 1]Man, that little compressor hiss and[n]seeing that perfect spray of color, then[n]gently stroking the paint back and forth--[n][f 1 1][e]
[f 2 1]...Huh? What? Look, I wouldn't be saying[n]this if I didn't think you felt the same[n]way! Anyway, let's see how you do![n][f 1 1][e]

[msg MSG_0103_TALK_ABOUT_MARI]
[f 2 1]> Maybe you should ask about Marie...[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED2]
[f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_NO_2]
[f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 2 1]> You have yet to speak with some of[n]the people who are close to you.[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL_2]
[f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 2 1]> You now have said goodbye to everyone[n]who is close to you.[n][f 1 1][e]
[f 2 1]> It's time for you to go back home to[n]prepare for tomorrow...[n][f 1 1][e]

[msg MSG_0320_RETURN_HOME2]
[f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 2 1]> It's time for you to go back home to[n]prepare for tomorrow...[n][f 1 1][e]

[msg MSG_0320_NOMORE_NEED3]
[f 2 1]> There's no reason for you to be here...[n][f 1 1][e]

[msg MSG_0320_GO_HOME_COMU_AL_3]
[f 2 1]> You should have no reason to come[n]here anymore...[n][f 1 1][e]
[f 2 1]> You now have said goodbye to everyone[n]who is close to you.[n][f 1 1][e]
[f 2 1]> Is there something that you still[n]have to do here...?[n][f 1 1][e]

[msg MSG_0417_VELVET_DONOTENT]
[f 2 1]> You have no need to enter here...[n][f 1 1][e]

[msg YAKUTEN]
[f 2 1]> The sign says "Nakanishi Drugs," but[n]the shutters are closed.[n][f 1 1][e]
[f 2 1]> There's a notice saying, "The shop is[n]closed."[n][f 1 1][e]

[msg SIMATTA]
[f 2 1]> It's a store, but the shutters are[n]closed.[n][f 1 1][e]

[msg DENKI]
[f 2 1]> The sign says "Ichikawa Electronics,"[n]but the shutters are closed.[n][f 1 1][e]
[f 2 1]> There's an old notice that reads,[n]"Going out of business sale!"[n][f 1 1][e]

[msg EQUIP_SHOP_STOP]
[f 2 1]> A fierce-looking man is single-mindedly[n]pounding on something in the back of the[n]store...[n][f 1 1][e]
[f 2 1]> You decide not to enter...[n][f 1 1][e]

[msg EQUIP_SHOP_CLOSED]
[f 2 1]> The store has closed for today...[n][f 1 1][e]

[msg MSG_SPOT_NPC_02_BEFORE_0 [Mr. Morooka]]
[f 2 1][f 4 6 16 1 0 1]You! You're finally here![n][f 1 1][e]
[f 2 1]Here, this is the school track suit.[n][f 1 1][e]
[f 2 1][f 4 7 0]> Received [f 2 5 3 65535 0].[n][f 1 4][e]
[f 2 1][f 4 6 16 1 0 1]Don't forget to thank me! Now take it[n]and scram![n][f 1 1][e]
[f 2 1][f 4 7 0]> Your business with Mr. Morooka is[n]finished. You should go home...[n][f 1 4][e]

[msg MSG_SPOT_NPC_02_AFTER_00 [Mr. Morooka]]
[f 2 1][f 4 6 16 1 0 1]Now, then, I'm off the clock, so I'll[n]just have myself a drink...[n][f 1 1][e]
[f 2 1]Hrm? You're still here?[n][f 1 1][e]
[f 2 1]Don't tell me you're trying to get[n]yourself a drink here, are you!?[n][f 1 1][e]
[f 2 1]You're never getting in as long as I[n]draw breath! Now scram![n][f 1 1][e]
[f 2 1][f 4 7 0]> Your business with Mr. Morooka is[n]finished. You should go home...[n][f 1 4][e]

[msg HELP_COSTUME_HOWTO_USE]
[f 2 1]You can equip costumes you have obtained[n]and wear them while exploring dungeons.[n]Select "Equip" from the menu.[n][f 1 1][e]

[msg MSG_ITEMSHOP_0411]
[f 2 1]> A variety of products lines the[n]shelves...[n][f 1 1][e]
[f 2 1]> A friendly-looking old lady sits behind[n]the counter...[n][f 1 1][e]

[msg GATYA_NOTRAIN]
[f 2 1]> There's a line of old capsule[n]vending machines.[n][f 1 1][e]
[f 2 1]> But the dials are rusted in place;[n]you cannot turn them...[n][f 1 1][e]

[msg GATYA_RAIN]
[f 2 1]> There's a line of old capsule[n]vending machines.[n][f 1 1][e]
[f 2 1]> ......!?[n][f 1 1][e]
[f 2 1]> Did the rain loosen the dial...?[n][f 1 1][e]
[f 2 1]> By some minor miracle, you can turn[n]the dial.[n][f 1 1][e]
[f 2 1]> One capsule costs 200 yen, and you[n]currently have [f 2 4 20] yen.[n]Do you want to spend some time here?[n][f 1 1][e]

[msg GATYA_SNOW]
[f 2 1]> There's a line of old capsule[n]vending machines.[n][f 1 1][e]
[f 2 1]> ......!?[n][f 1 1][e]
[f 2 1]> Did the snow loosen the dial...?[n][f 1 1][e]
[f 2 1]> By some minor miracle, you can turn[n]the dial.[n][f 1 1][e]
[f 2 1]> One capsule costs 200 yen, and you[n]currently have [f 2 4 20] yen.[n]Do you want to spend some time here?[n][f 1 1][e]

[msg GATYA_RAIN_3_20]
[f 2 1]> There's a line of old capsule[n]vending machines.[n][f 1 1][e]
[f 2 1]> ......!?[n][f 1 1][e]
[f 2 1]> Someone has apparently twisted the[n]dial too hard.[n][f 1 1][e]
[f 2 1]> ...It's broken.[n][f 1 1][e]

[msg GATYA_NO]
[f 2 1]> You can't afford that...[n][f 1 1][e]

[sel SEL_GATYA top]
[f 2 1]Play[e]
[f 2 1]Don't play[e]

[msg GATYA_WAITTING]
[f 2 1]> ......[n][f 1 2 30][f 1 1][e]
[f 2 1]> .........[n][f 1 2 30][f 1 1][e]
[f 2 1]> ............[n][f 1 2 30][f 1 1][e]

[msg GATYA_GET_ITEM_0]
[f 2 1]> Obtained [f 4 4 3 1 806]![n][f 1 1][e]
[f 2 1]> Turning the dial took some time...[n][f 1 1][e]
[f 2 1]> It's time to go home...[n][f 1 1][e]

[msg GATYA_GET_ITEM_1]
[f 2 1]> Obtained [f 4 4 3 1 808]![n][f 1 1][e]
[f 2 1]> Turning the dial took some time...[n][f 1 1][e]
[f 2 1]> It's time to go home...[n][f 1 1][e]

[msg GATYA_GET_ITEM_2]
[f 2 1]> Obtained [f 4 4 3 1 810]![n][f 1 1][e]
[f 2 1]> Turning the dial took some time...[n][f 1 1][e]
[f 2 1]> It's time to go home...[n][f 1 1][e]

[msg GATYA_GET_ITEM_3]
[f 2 1]> Obtained [f 4 4 3 1 812]![n][f 1 1][e]
[f 2 1]> Turning the dial took some time...[n][f 1 1][e]
[f 2 1]> It's time to go home...[n][f 1 1][e]

[msg GATYA_GET_ITEM_4]
[f 2 1]> Obtained [f 4 4 3 1 807]![n][f 1 1][e]
[f 2 1]> Turning the dial took some time...[n][f 1 1][e]
[f 2 1]> It's time to go home...[n][f 1 1][e]

[msg GATYA_GET_ITEM_5]
[f 2 1]> Obtained [f 4 4 3 1 809]![n][f 1 1][e]
[f 2 1]> Turning the dial took some time...[n][f 1 1][e]
[f 2 1]> It's time to go home...[n][f 1 1][e]

[msg GATYA_GET_ITEM_6]
[f 2 1]> Obtained [f 4 4 3 1 811]![n][f 1 1][e]
[f 2 1]> Turning the dial took some time...[n][f 1 1][e]
[f 2 1]> It's time to go home...[n][f 1 1][e]

[msg GATYA_GET_ITEM_7]
[f 2 1]> Obtained [f 4 4 3 1 813]![n][f 1 1][e]
[f 2 1]> Turning the dial took some time...[n][f 1 1][e]
[f 2 1]> It's time to go home...[n][f 1 1][e]

[msg GATYA_TUMARI]
[f 2 1]> ...Hm!?[n][f 1 1][e]
[f 2 1]> Your prize is stuck. Call the lady[n]in Shiroku?[n][f 1 1][e]

[msg GATYA_TUMARI_NIGHT]
[f 2 1]> ...Hm!?[n][f 1 1][e]
[f 2 1]> Your prize is stuck. Call the hostess[n]in Shiroku?[n][f 1 1][e]

[sel SEL_GATYA_TUMARI top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg GATYA_TUMARI_KAERI]
[f 2 1]> ...It'll probably come out if you[n]just jostle it a bit.[n][f 1 1][e]
[f 2 1]> You decided to fix it by yourself.[n][f 1 1][e]

[msg GATYA_TUMARI_YOBI [Old Lady Shiroku]]
[f 2 1][f 4 6 20 1 0 1]Hmm? Did you break it? You know, my[n]late husband built these machines[n]himself...[n][f 1 1][e]
[f 2 1]For some reason, they only work on days[n]when the weather is nasty, like rain.[n]I remember it rained when he made them...[n][f 1 1][e]
[f 2 1]Oops, I'm sorry for such a morbid[n]story. Let me get you your prize, son.[n]It'll just take a second.[n][f 1 1][e]

[msg GATYA_TUMARI_YOBI_NIGHT [Shiroku hostess]]
[f 2 1][f 4 6 20 10 0 1]Hmm? Did you break it? You know, these[n]machines were built by my late[n]husband...[n][f 1 1][e]
[f 2 1]For some reason, they only work on days[n]when the weather is nasty, like rain.[n]I remember it rained when he made them...[n][f 1 1][e]
[f 2 1]Oops, I'm sorry for such a morbid[n]story. Let me get you your prize, son.[n]It'll just take a second.[n][f 1 1][e]

[msg GATYA_TUMARI_YOBI_SNOW [Old Lady Shiroku]]
[f 2 1][f 4 6 20 1 0 1]Hmm? Did you break it? You know, my[n]late husband built these machines[n]himself...[n][f 1 1][e]
[f 2 1]For some reason, they only work on days[n]when the weather is nasty, like rain.[n]I remember it rained when he made them...[n][f 1 1][e]
[f 2 1]Oops, I'm sorry for such a morbid[n]story. Let me get you your prize, son.[n]It'll just take a second.[n][f 1 1][e]

[msg GATYA_TUMARI_YOBI_SNOW_N [Shiroku hostess]]
[f 2 1][f 4 6 20 10 0 1]Hmm? Did you break it? You know, my[n]late husband built these machines[n]himself...[n][f 1 1][e]
[f 2 1]For some reason, they only work on days[n]when the weather is nasty, like rain.[n]I remember it rained when he made them...[n][f 1 1][e]
[f 2 1]Oops, I'm sorry for such a morbid[n]story. Let me get you your prize, son.[n]It'll just take a second.[n][f 1 1][e]

[msg GATYA_TUMARI_GET_ITEM_0]
[f 2 1][f 4 7 0]> ...[n][f 1 1][e]
[f 2 1]> ......[n][f 1 1][e]
[f 2 1]> ......Obtained [f 4 4 3 1 806]![n][f 1 1][e]

[msg GATYA_TUMARI_GET_ITEM_1]
[f 2 1][f 4 7 0]> ...[n][f 1 1][e]
[f 2 1]> ......[n][f 1 1][e]
[f 2 1]> ......Obtained [f 4 4 3 1 808]![n][f 1 1][e]

[msg GATYA_TUMARI_GET_ITEM_2]
[f 2 1][f 4 7 0]> ...[n][f 1 1][e]
[f 2 1]> ......[n][f 1 1][e]
[f 2 1]> ......Obtained [f 4 4 3 1 810]![n][f 1 1][e]

[msg GATYA_TUMARI_GET_ITEM_3]
[f 2 1][f 4 7 0]> ...[n][f 1 1][e]
[f 2 1]> ......[n][f 1 1][e]
[f 2 1]> ......Obtained [f 4 4 3 1 812]![n][f 1 1][e]

[msg GATYA_TUMARI_GET_ITEM_4]
[f 2 1][f 4 7 0]> ...[n][f 1 1][e]
[f 2 1]> ......[n][f 1 1][e]
[f 2 1]> ......Obtained [f 4 4 3 1 807]![n][f 1 1][e]

[msg GATYA_TUMARI_GET_ITEM_5]
[f 2 1][f 4 7 0]> ...[n][f 1 1][e]
[f 2 1]> ......[n][f 1 1][e]
[f 2 1]> ......Obtained [f 4 4 3 1 809]![n][f 1 1][e]

[msg GATYA_TUMARI_GET_ITEM_6]
[f 2 1][f 4 7 0]> ...[n][f 1 1][e]
[f 2 1]> ......[n][f 1 1][e]
[f 2 1]> ......Obtained [f 4 4 3 1 811]![n][f 1 1][e]

[msg GATYA_TUMARI_GET_ITEM_7]
[f 2 1][f 4 7 0]> ...[n][f 1 1][e]
[f 2 1]> ......[n][f 1 1][e]
[f 2 1]> ......Obtained [f 4 4 3 1 813]![n][f 1 1][e]

[msg GATYA_TUMARI_GET_ITEM_EN [Old Lady Shiroku]]
[f 2 1][f 4 6 20 1 0 1]Sorry for the wait. Take this as a[n]token of my apology.[n][f 1 1][e]
[f 2 1][f 4 7 0]> Obtained [f 4 4 3 1 833] x 2![n][f 1 4][e]
[f 2 1]> It's time to go home...[n][f 1 4][e]

[msg GATYA_TUMARI_GET_ITEM_EN_2 [Shiroku hostess]]
[f 2 1][f 4 6 20 10 0 1]Sorry for the wait. Take this as a[n]token of my apology.[n][f 1 1][e]
[f 2 1][f 4 7 0]> Obtained [f 4 4 3 1 833] x 2![n][f 1 4][e]
[f 2 1]> It's time to go home...[n][f 1 4][e]

[msg GATYA_TUMARI_GET_ITEM_EN_3 [Old Lady Shiroku]]
[f 2 1][f 4 6 20 1 0 1]Sorry for the wait. Take this as a[n]token of my apology.[n][f 1 1][e]
[f 2 1][f 4 7 0]> Obtained [f 4 4 3 1 833]![n][f 1 4][e]
[f 2 1]> It's time to go home...[n][f 1 4][e]

[msg GATYA_TUMARI_GET_ITEM_EN_4 [Shiroku hostess]]
[f 2 1][f 4 6 20 10 0 1]Sorry for the wait. Take this as a[n]token of my apology.[n][f 1 1][e]
[f 2 1][f 4 7 0]> Obtained [f 4 4 3 1 833]![n][f 1 4][e]
[f 2 1]> It's time to go home...[n][f 1 4][e]

[msg GATYA_TUMARI_GET_ITEM_EN_5]
[f 2 1]> It took a while getting the stuck[n]prize out...[n][f 1 1][e]
[f 2 1]> It's time to go home...[n][f 1 1][e]

[msg MSG_FACI_0103_HAJIKI]
[f 2 1]> You have no reason to be here[n]right now...[n][f 1 1][e]

[msg MSG_FACI_0103_COMU_NOEND]
[f 2 1]> New year's greetings take priority[n]today...[n][f 1 1][e]

[msg MSG_FACI_0103_COMU_ALLEN]
[f 2 1]> You're tired from going around greeting[n]everyone. You should return home...[n][f 1 1][e]

[msg NEWYEAR_ALLSUMI]
[f 2 1]> You have greeted all the people that[n]you have become acquainted with over the[n]last year...[n][f 1 1][e]
[f 2 1]> Return to your home?[n][f 1 1][e]

[msg NEWYEAR_MADA]
[f 2 1]> There are others with whom you have[n]become acquainted over the past year...[n][f 1 1][e]
[f 2 1]> You should greet them...[n][f 1 1][e]

[msg MUSI_JINJYA_A_01]
[f 2 1]Obtained [f 2 5 3 65535 0]![n][f 1 1][e]

[msg MSG_MUSI_GET_5]
[f 2 1]> Caught [f 2 5 3 65535 2] x 3![n]  Caught [f 2 5 3 65535 3] x 3![n][f 1 1][e]
[f 2 1]> Caught [f 2 5 3 65535 4] x 2![n]  Caught [f 2 5 3 65535 5] x 2![n][f 1 1][e]
[f 2 1]> Caught [f 2 5 3 65535 6] x 1![n][f 1 1][e]

[msg MSG_MUSI_GET_4]
[f 2 1]> Caught [f 2 5 3 65535 2] x 3![n]  Caught [f 2 5 3 65535 3] x 2![n][f 1 1][e]
[f 2 1]> Caught [f 2 5 3 65535 4] x 1![n]  Caught [f 2 5 3 65535 5] x 1![n][f 1 1][e]

[msg MSG_MUSI_GET_3]
[f 2 1]> Caught [f 2 5 3 65535 2] x 2![n]  Caught [f 2 5 3 65535 3] x 2![n][f 1 1][e]
[f 2 1]> Caught [f 2 5 3 65535 4] x 1![n][f 1 1][e]

[msg MSG_MUSI_GET_2]
[f 2 1]> Caught [f 2 5 3 65535 2] x 2![n]  Caught [f 2 5 3 65535 3] x 1![n][f 1 1][e]

[msg MSG_MUSI_GET_1]
[f 2 1]> Caught [f 2 5 3 65535 2] x 2![n][f 1 1][e]

[msg MSG_MUSI_SPAWN_END]
[f 2 1]> ...It seems there aren't any more bugs[n]to catch around here.[n][f 1 1][e]

[msg MSG_MUSI_ESA_PUT]
[f 2 1]> The bait is already set. You should[n]check back tomorrow.[n][f 1 1][e]

[msg MSG_MUSI_ESA_READY]
[f 2 1]> There is an indentation in the ground,[n]perfect to set the [f 2 4 0].[n][f 1 1][e]
[f 2 1]> You probably could catch some bugs here.[n][f 1 1][e]

[msg MSG_MUSI_ESA_NOHAVE]
[f 2 1]> However, you don't have [n]any [f 2 5 3 13 0]...[n][f 1 1][e]

[msg MSG_MUSI_ESA_READY_YN]
[f 2 1]> Set [f 2 4 0] here?[n][f 1 1][e]

[msg MSG_MUSI_ESA_READY_HOWMA]
[f 2 1]> How much [f 2 4 0] will you set?[n]([f 2 5 3 13 0] in possesion: [f 2 4 1])[n][f 1 1][e]

[sel SEL_MUSI_ESA_HOWMANY top]
[f 2 1]5[e]
[f 2 1]4[e]
[f 2 1]3[e]
[f 2 1]2[e]
[f 2 1]1[e]
[f 2 1]Next[e]
[f 2 1]Don't set any[e]

[msg MSG_MUSI_ESA_NOTENOUGH]
[f 2 1]> You don't have enough [f 2 5 3 13 0]...[n][f 1 1][e]

[msg MSG_MUSI_ESA_DONE]
[f 2 1]> You have set the [f 2 4 0].[n]You should check back tomorrow.[n][f 1 1][e]

[msg MSG_MUSI_PLACE]
[f 2 1]> Because it's in the shade, the air[n]here is moist...[n][f 1 1][e]

[msg MSG_MUSI_PLACE_RAIN]
[f 2 1]> There are no signs of insects around...[n]Perhaps this is due to the rain.[n][f 1 1][e]

[msg MSG_MUSI_PLACE_WINTER_1]
[f 2 1]> All the leaves of the tree have fallen[n]off...[n][f 1 1][e]

[msg MSG_MUSI_PLACE_WINTER_2]
[f 2 1]> Now is not the best time of year for[n]catching bugs...[n][f 1 1][e]

[msg MSG_MUSI_PLACE_NOMUSI]
[f 2 1]> There are no more signs of insects.[n]It would seem that you have caught all[n]the bugs that are around for now...[n][f 1 1][e]

[sel MUSI_SEL top]
[f 2 1]Catch bugs[e]
[f 2 1]Don't catch bugs[e]

[msg MSG_GOJITUDAN_GUIDE_YUKI]
[f 2 1]> Come to think of it, you have yet[n]to say goodbye to Yukiko...[n][f 1 1][e]
[f 2 1]> You should visit the Amagi Inn...[n][f 1 1][e]
[f 2 1]> You can get to the [f 0 1 2]Amagi Inn[n]from the bus stop at the shopping district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_ENGE]
[f 2 1]> Come to think of it, you have yet[n]to say goodbye to Yumi...[n][f 1 1][e]
[f 2 1]> You should visit the drama club...[n][f 1 1][e]
[f 2 1]> [f 0 1 2]The drama club is in the meeting[n]room on the first floor of the[n]Practice Building[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_SUIS]
[f 2 1]> Come to think of it, you have yet[n]to say goodbye to Ayane...[n][f 1 1][e]
[f 2 1]> You should visit the band room...[n][f 1 1][e]
[f 2 1]> [f 0 1 2]The band meets in the music room[n]on the first floor of the[n]Practice Building[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_BASK]
[f 2 1]> Come to think of it, you have yet[n]to say goodbye to Kou and Daisuke...[n][f 1 1][e]
[f 2 1]> You remember how you went to Aiya[n]with them...[n][f 1 1][e]
[f 2 1]> You should visit [f 0 1 2]Aiya in the[n]shopping district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_SOCC]
[f 2 1]> Come to think of it, you have yet[n]to say goodbye to Daisuke and Kou...[n][f 1 1][e]
[f 2 1]> You remember how you went to Aiya[n]with them...[n][f 1 1][e]
[f 2 1]> You should visit [f 0 1 2]Aiya in the[n]shopping district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_KITU]
[f 2 1]> Come to think of it, what has happened[n]to the fox...?[n][f 1 1][e]
[f 2 1]> You should summon the fox at the[n][f 0 1 2]main building of the shrine[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_NAOT]
[f 2 1]> Come to think of it, you have yet[n]to say goodbye to Naoto...[n][f 1 1][e]
[f 2 1]> Naoto was always standing around at the[n][f 0 1 2]first floor hallway of the school's[n]Classroom Building[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_ROUH]
[f 2 1]> Come to think of it, what has happened[n]to Hisano...?[n][f 1 1][e]
[f 2 1]> You should visit the place where you[n]spent time with her...[n][f 1 1][e]
[f 2 1]> Hisano was always standing around the[n][f 0 1 2]riverbank of Samegawa Flood Plain[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_HAHA]
[f 2 1]> Come to think of it, you have yet[n]to say goodbye to Eri...[n][f 1 1][e]
[f 2 1]> You should visit the hill where you[n]met her...[n][f 1 1][e]
[f 2 1]> You can get to the [f 0 1 2]hill from the[n]bus stop at the shopping district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_NURS]
[f 2 1]> Come to think of it, what has happened[n]to Sayoko...?[n][f 1 1][e]
[f 2 1]> You should visit the place where you spent[n]time with her...[n][f 1 1][e]
[f 2 1]> You can get to [f 0 1 2]Inaba Municipal[n]Hospital from the bus stop at the shopping[n]district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_YOUS]
[f 2 1]> Come to think of it, you have yet[n]to say goodbye to Yosuke and Kuma...[n][f 1 1][e]
[f 2 1]> You should visit the [f 0 1 2]Junes[n]food court[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_DOUJ]
[f 2 1]> You should say goodbye to Dojima...[n][f 1 1][e]
[f 2 1]> You should visit the[n][f 0 1 2]Dojima residence[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_NANA]
[f 2 1]> You should say hello to Nanako...[n][f 1 1][e]
[f 2 1]> You should visit the[n][f 0 1 2]Dojima residence[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_DOUJ_2]
[f 2 1]> You should say hello to[n]Dojima and Nanako...[n][f 1 1][e]
[f 2 1]> You should visit the[n][f 0 1 2]Dojima residence[f 0 1 0]...[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_AI]
[f 2 1]> Come to think of it, you have yet[n]to say goodbye to Ai...[n][f 1 1][e]
[f 2 1]> Ai was always standing around at the[n][f 0 1 2]first floor hallway of the school's[n]Classroom Building[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI]
[f 2 1]> Come to think of it, what has happened[n]to the fox...?[n][f 1 1][e]
[f 2 1]> You should summon the fox at the[n][f 0 1 2]main building of the shrine[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_2]
[f 2 1]> Come to think of it, you have yet[n]to greet Sayoko...[n][f 1 1][e]
[f 2 1]> You can get to [f 0 1 2]Inaba Municipal[n]Hospital from the bus stop at the shopping[n]district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_3]
[f 2 1]> Come to think of it, you have yet[n]to greet Sayoko...[n][f 1 1][e]
[f 2 1]> Though she has left the hospital, you[n]should visit the place where you spent[n]time with her...[n][f 1 1][e]
[f 2 1]> You can get to [f 0 1 2]Inaba Municipal[n]Hospital from the bus stop at the shopping[n]district[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_4]
[f 2 1]> Come to think of it, you have yet[n]to greet Hisano...[n][f 1 1][e]
[f 2 1]> You should visit the [f 0 1 2]riverbank[n]of Samegawa Flood Plain[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_5]
[f 2 1]> Come to think of it, you have yet[n]to greet Hisano...[n][f 1 1][e]
[f 2 1]> Though she has moved away, you should[n]visit the place where you spent time with[n]her...[n][f 1 1][e]
[f 2 1]> You should visit the [f 0 1 2]riverbank[n]of Samegawa Flood Plain[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_6]
[f 2 1]> Come to think of it, you have yet[n]to greet Eri...[n][f 1 1][e]
[f 2 1]> You remember the day she was at the[n]flood plain...[n][f 1 1][e]
[f 2 1]> You should visit the [f 0 1 2]riverbank[n]of Samegawa Flood Plain[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_7]
[f 2 1]> Come to think of it, you have yet[n]to greet Naoto...[n][f 1 1][e]
[f 2 1]> You remember the days you spent with her...[n][f 1 1][e]
[f 2 1]> You should visit the [f 0 1 2]riverbank[n]of Samegawa Flood Plain[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_8]
[f 2 1]> Come to think of it, you have yet[n]to greet Yosuke...[n][f 1 1][e]
[f 2 1]> If you visit [f 0 1 2]Junes[f 0 1 0],[n]will you be able to meet him...?[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_9]
[f 2 1]> Come to think of it, you have yet[n]to greet Yosuke...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_10]
[f 2 1]> Come to think of it, you have yet[n]to greet Kuma...[n][f 1 1][e]
[f 2 1]> If you visit [f 0 1 2]Junes[f 0 1 0],[n]will you be able to meet him...?[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_11]
[f 2 1]> Come to think of it, you have yet[n]to greet Kuma...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_12]
[f 2 1]> Come to think of it, you have yet[n]to greet Marie and Margaret...[n][f 1 1][e]
[f 2 1]> You should visit the [f 0 1 2]Velvet Room[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_13]
[f 2 1]> Come to think of it, you have yet[n]to greet Margaret...[n][f 1 1][e]
[f 2 1]> You should visit the [f 0 1 2]Velvet Room[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_14]
[f 2 1]> Come to think of it, you have yet[n]to greet Marie...[n][f 1 1][e]
[f 2 1]> You should visit the [f 0 1 2]Velvet Room[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_15]
[f 2 1]> Come to think of it, you have yet to [n]greet the residents of the Velvet Room...[n][f 1 1][e]
[f 2 1]> You should visit the [f 0 1 2]Velvet Room[f 0 1 0]...[n][f 1 1][e]

[msg MSG_MARIE_VELVET_IN [Marie]]
[f 2 1][f 4 6 60 1 0 1]Oh, you're going in? Then I'll go, too.[n][f 1 1][e]

[msg HELP_EVE_SKIP]
[f 2 1]During events, press [f 0 1 2]Backlog button[f 0 1 0] to see[n]the log and [f 0 1 2]Skip Event button[f 0 1 0] to skip the event[n]entirely.[n][f 1 1][e]

[msg MOTENAI2]
[f 0 5 65278][f 2 1]> You won't be able to carry all of that...[n][f 1 1][e]

