[msg NANA0120_0121 [Nanako]]
[f 0 5 65278][f 2 1][f 4 6 10 1 65535 1]Kuma was here while I was gone?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Aww, lucky. I wanted to play with him.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 10 2 65535 1]Let's go see him at Junes, big bro![n][f 1 1][e]

[msg NANA0128_0129 [Nanako]]
[f 0 5 65278][f 2 1][f 4 6 10 2 65535 1]We made snowmen at school the other day.[n]Everyone made a Kumaman![n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_YOUS]
[f 0 5 65278][f 2 1]> You recall that you haven't seen Yosuke[n]and Kuma yet...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> Maybe you should go to the [f 0 1 2]food court[n]at Junes[f 0 1 0]...[n][f 1 1][e]