[msg RISE_DUNGEON_KIKANGAI [Rise]]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 259][f 4 6 5 1 65535 1]Senpai! Wanna go see Kuma today?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Even if we don't really have a reason[n]to go there now, I still can't just[n]stand here...[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Let's go, okay?[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_YOUS]
[f 0 5 65278][f 2 1]> You recall that you haven't seen Yosuke[n]and Kuma yet...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> Maybe you should go to the [f 0 1 2]food court[n]at Junes[f 0 1 0]...[n][f 1 1][e]