[msg KUMA_COME_02_NPC_02 [Student]]
[f 0 5 65278][f 2 1]This sense of total disappointment as soon[n]as he opens his mouth... It's just as bad[n]as Yosuke.[n][f 1 1][e]
[f 0 5 65278][f 2 1]He said his name's "Kuma." But he's not[n]a foreign exchange student or anything...[n][f 1 1][e]

[msg KUMA_COME_03_NPC_02 [Male student]]
[f 0 5 65278][f 2 1]Hey, did you hear? That Hanako's laying down[n]the law with the other girls.[n][f 1 1][e]
[f 0 5 65278][f 2 1]She said, "You better not go near Kuma."[n]What the hell did this guy do?[n][f 1 1][e]