[msg YOUSUKE_DUNGEON_YUK01_01 [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 202][f 4 6 2 1 65535 1]Yo, [f 4 2]. [n]Wanna head over to Kuma's?[n][f 1 1][e]

[msg YOUSUKE_SASOI_01_MOH03_B [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 2 65535 1][f 3 1 3 0 6 213]That reminds me, the girls said they're going[n]to take the motorcycle license exam soon.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's go to the beach as soon as they pass![n][f 1 1][e]
[f 0 5 65278][f 2 1]The only thing in our way is figuring out[n]what to do about Kuma...[n][f 1 1][e]