[msg MSG_000]
[f 0 5 65278][f 2 1]> Kuma message dummy[n][f 1 1][e]

[msg MSG_KUMA_BIKE_SASOI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]The people here are so nice! Every time[n]I come, they give me snacks![n][f 1 1][e]
[f 0 5 65278][f 2 1]Like just now, they said, "I'll give you[n]this if you just go away!"[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Where am I supposed to go, though? Do you[n]want to go somewhere with me?[n][f 1 1][e]

[msg MSG_KUMA_BIKE_SASOI_SEA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1][f 3 1 3 0 6 936]The beach...! Sensei... you're determined to[n]enjoy your youth![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]Okay! I just loaded up on snacks, so I'll[n]go anywhere with you![n][f 1 1][e]
[f 0 5 65278][f 2 1]I memorized the smell of the ocean the last[n]time we went, so follow my nose![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> You decided to go out with Kuma.[n][f 1 4][e]

[msg MSG_KUMA_BIKE_SASOI_ONSE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Ooh, the hot springs! That sounds like[n]a very mature kind of trip.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 966]After we get out of the bath, we have to[n]do a toast with fruit milk and Topsicles,[n]of course![n][f 1 1][e]
[f 0 5 65278][f 2 1]It'll be nice and toasty with you, Sensei![n]I can't wait.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> You decided to go out with Kuma.[n][f 1 4][e]

[msg MSG_KUMA_BIKE_SASOI_SKI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Oh wow, we're going skiing!?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 964]Alright, I'm gonna give it a hundred percent[n]and leave some beautiful ski tracks with you![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> You decided to go out with Kuma.[n][f 1 4][e]

[msg MSG_KUMA_BIKE_SASOI_MATA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 3 0 6 940]Are you busy, Sensei? Okay! Then I'll stay[n]here and keep scrounging for snacks![n][f 1 1][e]

[msg MSG_KUMA_BIKE_SASOI_2ND [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 3 0 6 962]Senseiiii. I'm boooooored.[n][f 1 1][e]

[msg MSG_KUMA_BIKE_SASOI_SYS]
[f 0 5 65278][f 2 1]> ...Kuma seems bored. Invite Kuma to[n]go out somewhere?[n][f 1 4][e]

[msg KUMA_SASOI_10_SINKA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 3 0 6 885]Oh, Sensei! You came![n][f 1 1][e]
[f 0 5 65278][f 2 1]What I wanted to talk to you about was,[n]umm... Nooo! I can't say it here![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]The mood's all wrong![n][f 1 1][e]
[f 0 5 65278][f 2 1]The best place for what I want to say would[n]be... the ocean! Let's go there, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> Kuma seems to want to go to the ocean...[n][f 1 4][e]

[msg KUMA_SASOI_HOUKAGO]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> Will you spend the afternoon with[n]Kuma?[n][f 1 1][e]

[msg KUMA_SASOI_GOGO]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> Will you spend the day with Kuma?[n][f 1 1][e]

[sel KUMA_MAX_SINKA top]
[f 0 5 65278][f 2 1]Spend time with Kuma[e]
[f 0 5 65278][f 2 1]Cancel[e]

[msg KUMA_YES_10_SINKA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 964]Woohoo! Thanks, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]Well then, let's go! Strike while the iron[n]is hot to trot![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> You decided to go to the ocean with[n]Kuma...[n][f 1 4][e]

[msg KUMA_NO_10_SINKA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1][f 3 1 3 0 6 940]Are you busy, Sensei? Oh well...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> Kuma seems a bit sad...[n][f 1 4][e]

[msg KUMA_COME_01_00 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Yo, 'sup, Sensei? Are ya on your way home?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> Kuma is sitting there with exaggerated[n]nonchalance...[n][f 1 4][e]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Man, I get all excited when school's over.[n]This feeling of freedom is like, such a rush.[n][f 1 1][e]

[msg KUMA_COME_01_01 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]I'm visiting! I want to see what it's like[n]to be a student.[n][f 1 1][e]

[msg KUMA_COME_01_02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]I'm acting like a student! It's a pretty[n]good impression, right?[n][f 1 1][e]

[msg KUMA_COME_01_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Hrm? Even Sensei can't tell who I am? Looks[n]like my act was TOO convincing...[n][f 1 1][e]

[msg KUMA_COME_01_04 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]I wanted to know more about this school[n]thing that everyone goes to.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 965]And it's much more fun than I thought it[n]would be! One day won't be enough... Heehee.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 7 0 0 0]> It seems Kuma plans to keep coming to[n]school from here on out.[n][f 1 4][e]
[f 0 5 65278][f 2 1]> You hope this doesn't cause any problems...[n][f 1 4][e]

[msg KUMA_COME_01_05 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Left, right, everywhere I look, I see[n]girls in uniforms...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 965]Hee! No wonder people go to school![n][f 1 1][e]

[msg KUMA_COME_01_06 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]I'm busier than most of you, so I can't[n]come every morning.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]I mean, I have to eat breakfast, go back[n]to bed, eat lunch, watch some TV...[n][f 1 1][e]
[f 0 5 65278][f 2 1]And that's not even counting time for snacks![n][f 1 1][e]
[f 0 5 65278][f 2 1]You might not think so, but coming here is[n]pretty tough to fit into my schedule.[n][f 1 1][e]

[msg KUMA_COME_02_00 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]No matter where I look, I see girls, girls,[n]and more girls... School is heaven![n][f 1 1][e]
[f 0 5 65278][f 2 1]There's a certain freshness you don't find[n]at Junes! Every day's great indeed.[n][f 1 1][e]
[f 0 5 65278][f 2 1]By the way, between sailor uniforms and[n]blazers... Which is more your speed?[n][f 1 1][e]

[msg KUMA_COME_02_01 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]The ribbon on the chest... The square collar[n]that flaps in the wind...[n][f 1 1][e]
[f 0 5 65278][f 2 1]You get it, Sensei! Sailor uniforms are[n]a perfect symbol of youth![n][f 1 1][e]

[msg KUMA_COME_02_02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]A young girl draped in mature clothing,[n]walking by with the coolest of expressions...[n][f 1 1][e]
[f 0 5 65278][f 2 1]You've got your own taste after all, Sensei![n]I'm touched![n][f 1 1][e]

[msg KUMA_COME_02_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]M-My...! That didn't even cross my mind...![n]A lovely girl dressed in a manly uniform...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Now that's my Sensei! Always with the ideas[n]the common man would never consider![n][f 1 1][e]

[msg KUMA_COME_02_04 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 965]Man, uniforms are awesome.[n][f 1 1][e]

[msg KUMA_COME_02_05 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Hmm, I keep sensing someone staring at me.[n]Has everyone fallen for the utterly adorable[n]Kuma?[n][f 1 1][e]
[f 0 5 65278][f 2 1]There's no need for anyone to be shy. I'm up[n]for talking with anyone![n][f 1 1][e]

[msg KUMA_COME_02_06 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]As soon as I enter the school grounds,[n]all eyes are on me.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 965]I have a monopoly on their love... What a[n]wicked bear I am![n][f 1 1][e]

[msg KUMA_COME_03_00 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Sensei, do you know the secret of hitting[n]on girls? I hear it's an eternal debate[n]amongst boys![n][f 1 1][e]
[f 0 5 65278][f 2 1]They say it's all in the first impressions.[n]How would you handle it?[n][f 1 1][e]

[msg KUMA_COME_03_01 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Hmhm, so as not to reveal your ulterior[n]motives. Now that's my Sensei! You're[n]quite the tactician![n][f 1 1][e]

[msg KUMA_COME_03_02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]So you just take your chances? Now that's[n]my Sensei! What a man![n][f 1 1][e]

[msg KUMA_COME_03_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Ooh, so you wait for the girl to make the[n]first move? Now that's my Sensei! Playing[n]the waiting game![n][f 1 1][e]

[msg KUMA_COME_03_04 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 965]When I come to school, I get to hear so many[n]different stories. It's all part of the[n]charm of this place![n][f 1 1][e]

[msg KUMA_COME_03_05 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 965]Lately when I come to school, I can sense[n]this strange, heated gaze.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I bet some adorably shy girl is waiting for[n]her chance to talk to me![n][f 1 1][e]

[msg KUMA_COME_03_06 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]...Hrmm.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 965]I sense that intense gaze today too. Could I[n]possibly have a secret admirer!?[n][f 1 1][e]

[msg KUMA_COME_04_00 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]Aaah! Sensei! I'm scared! There's something[n]scary![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1]My Kuma sense is detecting danger...[n]It's a red alert![n][f 1 1][e]
[f 0 5 65278][f 2 1]But it's almost time for work, and I can't[n]leave without passing through here... Hrghh...[n][f 1 1][e]
[f 0 5 65278][f 2 1]What should I do!?[n][f 1 1][e]

[msg KUMA_COME_04_01 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]Eep! Don't tell me you're putting all this[n]in my hands!?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Sensei... that's a heavy burden you're[n]putting on me...[n][f 1 1][e]

[msg KUMA_COME_04_02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1]All right! I won't hold back an inch![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Wait, so what am I supposed to do? I still[n]don't get it...[n][f 1 1][e]

[msg KUMA_COME_04_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]Are you saying what I think you're saying!?[n]Is this going to be so bad that I'll[n]come out the worse for bear!?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]If I knew this would happen, I would've[n]brought my Kuma fur...[n][f 1 1][e]

[msg KUMA_COME_04_04 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1][f 3 1 3 0 6 959]But man, this feels worse than a Shadow...[n]Hrghhh, how awful...![n][f 1 1][e]

[msg KUMA_COME_04_05 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 959]The important thing is, we need to think[n]about getting home safe![n][f 1 1][e]
[f 0 5 65278][f 2 1]If I can just get through this... I'll eat[n]Topsicles until I burst![n][f 1 1][e]

[msg KUMA_COME_04_06 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Uhh, don't look now, but I think someone's[n]trying to ambush me again today.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1]It must be an assassin, sent because I know[n]too much now that I go to school...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 943]If I live through this, I'd better stay away[n]from school for a while...[n][f 1 1][e]

[msg KUMA_AFTER_MARIE_RANK5_W [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Ooh, what's up, Sensei!?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Hrm? What's with that face? Did I do that[n]wrong somehow?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Kanji told me that's how you're supposed to[n]say hi to people at school.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]By the way, Sensei, how is Emmy-chan doing?[n][f 1 1][e]
[f 0 5 65278][f 2 1]You can't keep her all to herself, you know![n][f 1 1][e]
[f 0 5 65278][f 2 1]Make sure you tell her next time you see her[n]that I want to go on a date![n][f 1 1][e]

[msg MSG_DOUJIMAKE_001 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 965]Living together with Sensei... Heeheehee,[n]what a heart-pounding experience![n][f 1 1][e]

[msg MSG_DOUJIMAKE_002 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]*sniff* *sniff* This musty smell... So this[n]is life in a house with tatami mats.[n][f 1 1][e]

[msg MSG_DOUJIMAKE_003 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]I did some cleaning up, Sensei! Doesn't[n]everything feel a little sparklier?[n][f 1 1][e]

[msg MSG_DOUJIMAKE_004 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]I washed the dishes, Sensei! If it looks[n]like a few are chipped, you're probably[n]seeing things.[n][f 1 1][e]

[msg MSG_DOUJIMAKE_005 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]I did the laundry, Sensei! My Kuma fur[n]shrunk a little in the wash...[n][f 1 1][e]

[msg MSG_DOUJIMAKE_006 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]I was sleeping on the sofa and had a dream[n]about Nana-chan and Pops.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I hope they get better soon...[n][f 1 1][e]

[msg MSG_DOUJIMAKE_007 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1]I'm going to look after this house, for[n]Nana-chan and Pops' sake![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'll guard it with my life![n][f 1 1][e]

[msg MSG_DOUJIMAKE_008 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1][f 3 1 3 0 6 961]I hope Yosuke isn't lonely. What if he's[n]calling out for me even as we speak...?[n][f 1 1][e]

[msg MSG_DOUJIMAKE_009 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1]*snore* I'm... not sleepy... I wanna...[n]talk more... with... Sensei...[n][f 1 1][e]

[msg MSG_DOUJIMAKE_010 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1]A suspicious person was just here![n][f 1 1][e]
[f 0 5 65278][f 2 1]He said, "I have a delivery for Dojima-san!"[n]I told him that this was Pops' house and[n]sent him packing![n][f 1 1][e]

[msg MSG_DOUJIMAKE_0104 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]I'll stay with you until Nana-chan and Pops[n]come home![n][f 1 1][e]
[f 0 5 65278][f 2 1]Now you won't be lonely, Sensei![n][f 1 1][e]

[msg MSG_DOUJIMAKE_0104_01 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Oh no, thank you! Since I'm not alone[n]anymore now...[n][f 1 1][e]
[f 0 5 65278][f 2 1]This is just my way of returning the favor![n][f 1 1][e]

[msg MSG_DOUJIMAKE_0104_02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]What do you mean by "anything funny"?[n]Oh, do you mean my morning Kumarobics?[n][f 1 1][e]

[msg MSG_DOUJIMAKE_0105 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]I got an email from Yosuke! We're gonna go on[n]a ski trip in two days![n][f 1 1][e]
[f 0 5 65278][f 2 1]A silver white world of beaming smiles,[n]as a couple warms their numb fingers...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Heeheehee! I can't wait![n][f 1 1][e]

[msg MSG_DOUJIMAKE_0106 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Sensei, are you ready for the ski trip[n]tomorrow? I know I am![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1]But I'm still trying to decide if I should[n]bring Topsicles or not. Would they melt in[n]my luggage?[n][f 1 1][e]

[msg MSG_DOUJIMAKE_0109_DUNGE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1][f 3 1 3 0 6 896]Welcome home! I'm home, too![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm gonna go into the TV world for a while.[n]Rise-chan and I are going to snoop around[n]in there![n][f 1 1][e]

[msg MSG_DOUJIMAKE_0109_DUNGE_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Hey, Sensei. Rise-chan and I went to check[n]the TV world.[n][f 1 1][e]
[f 0 5 65278][f 2 1]It was a little weird, though... I'll tell[n]you about it tomorrow when everyone's around![n][f 1 1][e]

[msg MSG_DOUJIMAKE_0109 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 896]Welcome home! I'm home, too![n][f 1 1][e]
[f 0 5 65278][f 2 1]Heeheehee, the ski trip was so much fun![n]Next time, I'll make my ski tracks draw[n]a heart![n][f 1 1][e]

[msg MSG_DOUJIMAKE_0115 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Huh? Nana-chan's coming back from the[n]hospital!? Woohoo! Woooohooooooo![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'll be the best guard bear you've ever seen[n]until the day they come back![n][f 1 1][e]

[msg MSG_DOUJIMAKE_0115_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Until Nana-chan comes back from the hospital,[n]I'll be the best guard bear you've ever seen![n][f 1 1][e]

[msg MSG_DOUJIMAKE_0116_0118 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Nana-chan will be back from the hospital[n]soon! Pops, too![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 965]Heeheehee... How should I welcome them back?[n]I can't wait to see Nana-chan's smiling[n]face again![n][f 1 1][e]

[msg MSG_DOUJIMAKE_0119 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Nana-chan's coming back from the hospital[n]tomorrow! I could jump for joy![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1]But today's the last day I'll be staying[n]here... *sniff* That's a little sad.[n][f 1 1][e]

[msg MSG_DOUJIMAKE_MARIE_DUNG [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]We did it, Sensei! We rescued Emmy-chan![n][f 1 1][e]
[f 0 5 65278][f 2 1]We got a little shocked along the way...[n]But I can live with that![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 965]Heeheehee, I'll be sleeping soundly tonight![n][f 1 1][e]

