[msg MSG_000 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 3 0 6 876]Ooh, Sensei! Happy New Year![n][f 1 1][e]
[f 0 5 65278][f 2 1]I got New Year's gifts! Yosuke's mom and dad[n]gave them to me![n][f 1 1][e]
[f 0 5 65278][f 2 1]Now I can buy tons of snacks... or so I[n]thought, but I might save it for a while.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]I'm gonna use it to buy presents for[n]Nana-chan so we can all have fun together![n][f 1 1][e]
[f 0 5 65278][f 2 1]May this year be as great as the last one![n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_10]
[f 0 5 65278][f 2 1]> You recall that you haven't seen[n]Kuma yet...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> If you stop by [f 0 1 2]Junes[f 0 1 0], will he be there...?[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_11]
[f 0 5 65278][f 2 1]> You recall that you haven't seen[n]Kuma yet...[n][f 1 1][e]