[msg COStalk_YOU_14_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Yosuke, they look great on you. All the[n]trendy girls will love your style.[n][f 1 1][e]

[msg COStalk_YOU_14_Dialo01_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Hahaha, no matter how mad you are, you[n]can't possibly look scary in those[n]glasses. That's why they're great![n][f 1 1][e]

[msg COStalk_YOU_20_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 65535 1]Your voice is too small and weak![n]You gotta use your diaphragm, Yosuke![n][f 1 1][e]

[msg COStalk_YOU_20_Dialo01_3 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 15 65535 1]Shut up, Kuma! Don't yell right in my[n]ear![n][f 1 1][e]

[msg COStalk_YOU_22_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Hehe... You have finally come across THE[n]legendary overalls, whose non-stick[n]treatment allows them to repel all evil...[n][f 1 1][e]

[msg COStalk_YOU_14_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]Yosuke, you look great in those.[n]All the trendy girls are gonna love your[n]new look.[n][f 1 1][e]

[msg COStalk_YOU_14_Dialo01_4_2 [Kuma]]
[f 0 5 65278][f 2 1]Hehe, no matter how mad you get, you[n]don't look scary. That's why I love[n]when you wear those glasses.[n][f 1 1][e]

[msg COStalk_YOU_20_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]Your voice is too small and weak![n]You gotta use your diaphragm, Yosuke![n][f 1 1][e]

[msg COStalk_YOU_22_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]Hehe... You have finally found THE[n]legendary overalls, whose non-stick[n]treatment allows them to repel all evil...[n][f 1 1][e]

[msg COStalk_CHI_09_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 6 65535 1]*catcall* Rowrr![n]Looking amazing, Chie-chan![n]Sensei, I like the way you roll![n][f 1 1][e]

[msg COStalk_CHI_09_Dialo01_3 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 12 65535 1]Shut up, Kuma![n][f 1 1][e]
[f 0 5 65278][f 2 1]Fine then! I'll kick the crap out of the[n]Shadows to keep my mind off this costume![n][f 1 1][e]

[msg COStalk_CHI_10_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]I think so, too![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]I can see you kicking down all the trees! [n]It's perfect for you![n][f 1 1][e]

[msg COStalk_CHI_10_Dialo01_3 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 14 65535 1]Haha. That's not exactly eco-friendly,[n]Kuma...[n][f 1 1][e]

[msg COStalk_CHI_13_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Chie-chan, you like those glasses?[n]You should have told me![n][f 1 1][e]

[msg COStalk_CHI_20_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]I've seen one of those before! On TV![n][f 1 1][e]
[f 0 5 65278][f 2 1]"Going up!" right? [n]Say it, Chie-chan![n][f 1 1][e]

[msg COStalk_CHI_20_Dialo01_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]...Sensei, Chie-chan's acting weird. [n]The next floor up's not going to have[n]anything but Shadows.[n][f 1 1][e]

[msg COStalk_CHI_09_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]Rowrr! *catcall*[n]Hot cha cha, Chie-chan![n]Sensei, I like the way you think![n][f 1 1][e]

[msg COStalk_CHI_10_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]I think so too![n][f 1 1][e]
[f 0 5 65278][f 2 1]I can picture you kicking down an entire[n]forest! It's perfect for you![n][f 1 1][e]

[msg COStalk_CHI_13_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]Chie-chan, you're into those glasses?[n]You should have told me![n][f 1 1][e]

[msg COStalk_CHI_20_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]I've seen that on TV![n][f 1 1][e]
[f 0 5 65278][f 2 1]"Going up!" right? [n]You try it, Chie-chan![n][f 1 1][e]

[msg COStalk_CHI_20_Dialo01_4_2 [Kuma]]
[f 0 5 65278][f 2 1]Sensei! Chie-chan's acting weird! There's[n]no way there's gonna be womens' clothes[n]on the next floor. It's just Shadows.[n][f 1 1][e]

[msg COStalk_YUK_14_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]No, no, Yuki-chan! That's not supposed[n]to be the fat Santa! That outfit's a[n]different Santa who gives other presents![n][f 1 1][e]
[f 0 5 65278][f 2 1]Sheesh! I get that, and I'm not even[n]part of your world. You should be[n]embearassed.[n][f 1 1][e]

[msg COStalk_YUK_20_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Ah, Miss Amagi, I need to see you in my[n]office. I have an important matter that[n]needs your immediate attention.[n][f 1 1][e]

[msg COStalk_YUK_20_Dialo01_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 7 65535 1]Gah... Life in the corporate world is[n]tough![n][f 1 1][e]

[msg COStalk_YUK_14_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]No, no, no, Yuki-chan! You're not[n]supposed to be the fat, jolly Santa.[n]You're a different kind.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Even I understand that, and I'm still[n]just learning about your world.[n][f 1 1][e]

[msg COStalk_YUK_20_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]Miss Amagi, I'm going to need to see you[n]in my office to discuss some things.[n]Alone.[n][f 1 1][e]

[msg COStalk_YUK_20_Dialo01_4_2 [Kuma]]
[f 0 5 65278][f 2 1]Gah... Business is harsh.[n][f 1 1][e]

[msg COStalk_KAN_11_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 65535 1]Oh no! Kanji's Shadow appeared again![n]I guess it didn't disappear completely![n][f 1 1][e]

[msg COStalk_KAN_16_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Eat watermelon, take a nap, and slap at[n]the mosquitos![n][f 1 1][e]
[f 0 5 65278][f 2 1]Then, the wind chime will go off, and[n]you'll hear the sound of fireworks...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Fweeeeeee! BOOOM! PAAA! KASSSSHHH![n][f 1 1][e]

[msg COStalk_KAN_16_Dialo01_3 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 6 11 65535 1]SHA-SHA-SHA! KRA-KOW! FOOMP![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 6 14 65535 1]Oh, sorry, Senpai. I got a little[n]carried away after Kuma got me going.[n][f 1 1][e]
[msg COStalk_KAN_11_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]Oh no, guys! Kanji's Shadow appeared[n]again! I guess it didn't disappear[n]completely![n][f 1 1][e]

[msg COStalk_KAN_16_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]Eat some watermelon, take a nap, and[n]swat at those dang mosquitos![n][f 1 1][e]
[f 0 5 65278][f 2 1]Then, the melody of wind chimes will give[n]way to the sound of fireworks...[n][f 1 1][e]
[f 0 5 65278][f 2 1]BOOOOOM![n][f 1 1][e]

[msg COStalk_NAO_13_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Hm? Do you like those, Nao-chan? I have a[n]spare, so you can have another. One for [n]battle, one for home![n][f 1 1][e]

[msg COStalk_NAO_13_Dialo01_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]That hurt! You didn't even hesitate for[n]a second![n][f 1 1][e]

[msg COStalk_NAO_14_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Nao-chan, you look so cutesy and pretty![n]Well, even I won't give up my mascot[n]position without a fight! [n][f 1 1][e]

[msg COStalk_NAO_21_Dialo01_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Ooh! Then I'll be Watson! [n]Wait... What does Watson wear?[n][f 1 1][e]

[msg COStalk_NAO_21_Dialo01_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Oh, that's great! Then I can play Watson[n]just fine while I'm wearing this.[n][f 1 1][e]

[msg COStalk_NAO_13_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]Hm? Do you like those, Nao-chan? I have[n]a spare pair, so you can have another.[n]You'll have a pair for battle and home![n][f 1 1][e]

[msg COStalk_NAO_13_Dialo01_4_2 [Kuma]]
[f 0 5 65278][f 2 1]That hurt! You didn't even blink![n][f 1 1][e]

[msg COStalk_NAO_14_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]Nao-chan, you look so cutesy and pretty![n]BUt I won't give up my position as[n]mascot! [n][f 1 1][e]

[msg COStalk_NAO_21_Dialo01_2_2 [Kuma]]
[f 0 5 65278][f 2 1]Then I can be Watson! [n]What does Watson wear?[n][f 1 1][e]

[msg COStalk_NAO_21_Dialo01_4_2 [Kuma]]
[f 0 5 65278][f 2 1]Oh, great! Then I'll just keep wearing[n]this.[n][f 1 1][e]

[msg COStalk_KUM_LoveDEF01 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Sensei, Sensei! I want to change my[n]outfit! I want people to see me in[n]all kinds of different looks![n][f 1 1][e]

[msg COStalk_KUM_LoveDEF02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Sensei, Sensei! I want to change my[n]outfit! I want people to see me in[n]all kinds of bearious costumes![n][f 1 1][e]

[msg COStalk_KUM_CON_ON01 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Oh yeah, you changed too, Sensei.[n][f 1 1][e]

[msg COStalk_KUM_CON_ON02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]You changed outfits, Sensei![n][f 1 1][e]

[msg COStalk_KUM_CON_ON03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]...Hm? Did you change too, Sensei?[n][f 1 1][e]

[msg COStalk_KUM_01_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Sensei! [n]I wore my bear suit![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Hehehe... You missed me, didn't you, Suit?[n]I missed you too![n][f 1 1][e]

[msg COStalk_KUM_02_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Hehehe, I'm back in normal clothes.[n][f 1 1][e]
[f 0 5 65278][f 2 1]A customer at Junes asked me the other[n]day, "Where are you from!?"[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]I told them, "I'm from my bear suit!"[n]like I was supposed to![n][f 1 1][e]

[msg COStalk_KUM_03_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]I'm in a school uniform now, hehehe.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Is this the uniform for a different[n]school? I wanna go there![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 65535 1]I can't wait to check out the girls[n]there![n][f 1 1][e]

[msg COStalk_KUM_03_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Hehe, I'm in a school uniform.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Is this another school's uniform?[n]I wanna go there, Sensei![n][f 1 1][e]

[msg COStalk_KUM_03_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Oh, Chie-chan... what is that I detect...[n]Is it... jealousy!?[n][f 1 1][e]

[msg COStalk_KUM_03_Dialo01_4 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 13 65535 1]Kuma, do you want a footprint on your[n]brand-new costume?[n][f 1 1][e]

[msg COStalk_KUM_04_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Look, look! I changed![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm Kuma in Wonderland! [n]Hey, Sensei, your face is turning red![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 65535 1]I just mauled your heart, didn't I?[n][f 1 1][e]

[msg COStalk_KUM_04_Favor_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Sensei... I want to change...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 65535 1]I'm too cute in this outfit...[n]I bet you can't concentrate, either![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]*sob* Looking this beautiful is such a[n]burden![n][f 1 1][e]

[msg COStalk_KUM_04_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Look at me! I changed![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm Kuma in Wonderland! [n]Whoa, Sensei! Your face is bright red![n][f 1 1][e]

[msg COStalk_KUM_04_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 6 65535 1]Hehehe...! I'm a regular thief of[n]hearts! Guy or girl, I'll steal their[n]heart away![n][f 1 1][e]

[msg COStalk_KUM_04_Limit_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Check out my new threads![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Ohhh... It reminds me of Nao-chan and I's[n]miracle! It is now legend![n][f 1 1][e]
[f 0 5 65278][f 2 1]I want to go to the Culture Festival[n]again![n][f 1 1][e]

[msg COStalk_KUM_05_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Heehee, I changed into swimming trunks![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]When I have this on, I can just hear[n]the voices of the tanned girls calling[n]out for me.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Sensei, I want to go to the beach![n][f 1 1][e]

[msg COStalk_KUM_05_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Nice! I'm in swimming trunks![n][f 1 1][e]

[msg COStalk_KUM_05_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Hmm, I haven't really looked all that[n]hard. Maybe I still have a tail...[n][f 1 1][e]

[msg COStalk_KUM_05_Limit_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Now it's swim tiiime![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]These trunks remind me of the beach. It[n]was so much fun. I want to go again.[n][f 1 1][e]
[f 0 5 65278][f 2 1]The shining sun, the waves... The sound[n]of scantily clad girls calling out to me[n]from the shore...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 7 65535 1]Whoa! Gotta stop daydreaming! The Shadows[n]are starting to look like kelp.[n][f 1 1][e]

[msg COStalk_KUM_06_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]I think I changed into gym clothes. Cool![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]It's got the decals from your school![n]What's the "Y.H." mark on the chest stand[n]for?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh I know! Is it "YAAAHOO!"?[n][f 1 1][e]

[msg COStalk_KUM_06_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]I'm in sporting clothes![n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh, it's the gym uniform of your high[n]school! What's the "Y.H." stand for?[n][f 1 1][e]

[msg COStalk_KUM_06_Dialo01_2 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 11 65535 1]Duh, Kuma. It stands for "Yaaahoo."[n]Because everyone's always yelling[n]loudly in gym class.[n][f 1 1][e]

[msg COStalk_KUM_06_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Oh, that makes total sense![n]Yaaaaaahooooooo![n][f 1 1][e]

[msg COStalk_KUM_07_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]I love new outfits![n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh, this is something a prince on a white[n]steed would wear! Walk on! Good horse![n]Whoa![n][f 1 1][e]

[msg COStalk_KUM_07_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Here comes a new costume![n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh, this is something a prince on a white[n]steed would wear! Here I come to save the[n]fair Princess Yukiko![n][f 1 1][e]

[msg COStalk_KUM_07_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]Nuuuuuu...[n][f 1 1][e]

[msg COStalk_KUM_08_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Whoa! This one is epic![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 65535 1]I'm a Tidy Endorphin Powered Stranger![n]Now, I'm going to defeat the Shadows![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]...But before that, can you give me a[n]hand with my zipper, Sensei?[n][f 1 1][e]

[msg COStalk_KUM_08_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]This costume's amazing![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 65535 1]I'm a Tidy Endorphin Powered Stranger![n]Here I come to save the daayyyyy![n][f 1 1][e]

[msg COStalk_KUM_09_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]Sensei, I changed, but...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Is there a bath nearby? Is that why I'm[n]in this outfit? I don't smell one...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]...This reminds me of Kanji.[n][f 1 1][e]

[msg COStalk_KUM_09_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]I changed, Sensei, but...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Is there supposed to be a bath nearby?[n]I don't smell one...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]...This outfit reminds me of Kanji.[n][f 1 1][e]

[msg COStalk_KUM_10_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Hehehe... I changed into a suit.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Isn't it awesome? I look so... coooool.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]It makes my shoulders kind of tense,[n]though.[n][f 1 1][e]

[msg COStalk_KUM_10_Favor_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]Sensei... I want to change soon.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Wearing this makes me all tense. [n]Also, every time I walk, I hear something[n]rip...[n][f 1 1][e]

[msg COStalk_KUM_10_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Hehehe... My very own suit.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]This is great! I'm lookin' sooooo gooood![n][f 1 1][e]
[f 0 5 65278][f 2 1]It's a little restrictive, though.[n][f 1 1][e]

[msg COStalk_KUM_10_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]With hard work and persistence. If you[n]want to get ahead in life, you must learn[n]to be similarly disciplined, Yosuke.[n][f 1 1][e]

[msg COStalk_KUM_11_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Check it out, Sensei.[n]I wore my special glasses.[n][f 1 1][e]
[f 0 5 65278][f 2 1]But I can see past the fog even without[n]glasses, though...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 65535 1]Hmm, I bet you made me wear these because[n]you have a thing for Kumas with glasses![n][f 1 1][e]

[msg COStalk_KUM_11_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]I wore my special glasses, as requested.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Well? Well? Do I look good?[n][f 1 1][e]

[msg COStalk_KUM_11_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 7 65535 1]Noooo! I'm hurt...[n][f 1 1][e]

[msg COStalk_KUM_12_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Ooh, ooh! Look at me! I'm a reindeer![n][f 1 1][e]
[f 0 5 65278][f 2 1]Double the fur! Double the fluff![n][f 1 1][e]
[f 0 5 65278][f 2 1]The red nose is the best part![n][f 1 1][e]

[msg COStalk_KUM_12_Favor_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]Sensei... I want to change.[n][f 1 1][e]
[f 0 5 65278][f 2 1]When I wear this, the lines kinda blur.[n]Am I a human in a bear suit in a reindeer[n]outfit? Or just a bear? Or a reindeer?[n][f 1 1][e]
[f 0 5 65278][f 2 1]This costume's giving me an identity[n]crisis.[n][f 1 1][e]

[msg COStalk_KUM_12_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Look at me, everyone![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm a Christmas reindeer![n]Fluffy galore![n][f 1 1][e]

[msg COStalk_KUM_12_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 65535 1]How rude! I'm a bear! I'm Kuma wearing[n]a bear suit, wearing a reindeer suit, and[n]don't you forget it![n][f 1 1][e]

[msg COStalk_KUM_13_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Neat! I changed into a happi.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]When I'm wearing this, I can't help[n]myself! I wanna sing and dance![n]Ara, essa essa![n][f 1 1][e]

[msg COStalk_KUM_13_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Check it out! I'm wearing a happi![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]When I'm wearing this, I feel like[n]dancing! Ara, essa essa![n][f 1 1][e]

[msg COStalk_KUM_14_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]This is an interesting outfit, isn't it?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Trigger tree! [n]C'mon Sensei, gimme some canday![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]...Just no meat gum, though.  I got one[n]from Chie-chan once, and one is enough[n]for a lifetime.[n][f 1 1][e]

[msg COStalk_KUM_14_Favor_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]Sensei... I want to change outfits.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm not sure if I'm a bear or a pumpkin.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Too many costumes at once jumbles up my[n]polarity...[n][f 1 1][e]

[msg COStalk_KUM_14_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Tada![n][f 1 1][e]

[msg COStalk_KUM_14_Dialo01_2 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 14 65535 1]Ahahaha! That's great, Kuma![n]You're totally a pumpkin![n][f 1 1][e]

[msg COStalk_KUM_14_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]Hehehe, trigger tree! Chie-chan, won't[n]you give me some canday!?[n][f 1 1][e]

[msg COStalk_KUM_14_Dialo01_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]What? It's meat, but it's gum?[n]This bear's seen everything now.[n][f 1 1][e]

[msg COStalk_KUM_16_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Hey, Sensei, I changed.[n][f 1 1][e]
[f 0 5 65278][f 2 1]But what is this...? I heard someone say[n]it was mutton or something.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]You're quite the jokester to put a bear[n]in sheep's clothing![n][f 1 1][e]

[msg COStalk_KUM_16_Favor_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]Sensei... Can I change costumes?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I feel like the sheepness of this costume[n]is taking control of my beareality![n][f 1 1][e]
[f 0 5 65278][f 2 1]My ursa and the sheepgo are fighting for[n]control of my psyche! [n][f 1 1][e]

[msg COStalk_KUM_16_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Okay, Sensei, I changed.[n][f 1 1][e]
[f 0 5 65278][f 2 1]What is this outfit, though?[n]I feel like I should be carrying tea.[n][f 1 1][e]

[msg COStalk_KUM_16_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]A mutton outfit?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Sensei's such a wiseguy. Making a bear[n]wear a sheep. [n][f 1 1][e]

[msg COStalk_KUM_17_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Yay! New outfit![n][f 1 1][e]
[f 0 5 65278][f 2 1]I know this one! I'm part of a Japanese[n]cheering squad![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Go! Go! Sensei![n]Ei! Yah! Toh![n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's throw those Shadows to the ground![n][f 1 1][e]

[msg COStalk_KUM_17_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Look at me now![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm part of a Japanese cheering squad![n][f 1 1][e]
[f 0 5 65278][f 2 1]Go! Go! Sensei![n]Ei! Yah! Toh![n][f 1 1][e]

[msg COStalk_KUM_17_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 6 65535 1]Hehehehe... I'll capture the hearts of [n]everyone watching TV![n][f 1 1][e]

[msg COStalk_KUM_18_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Changing complete![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm supposed to be hotel staff, right?[n]I've seen it on TV before![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'll welcome people as they walk in![n][f 1 1][e]

[msg COStalk_KUM_18_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Costume change finished![n][f 1 1][e]
[f 0 5 65278][f 2 1]This is a hotel employee costume, right?[n]I've seen it on TV before![n][f 1 1][e]

[msg COStalk_KUM_18_Dialo01_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 65535 1]You are such a meanie, Kanji![n][f 1 1][e]
[f 0 5 65278][f 2 1]If it closes down just because I snuck[n]bites of their food, then it was gonna[n]close down anyway![n][f 1 1][e]

[msg COStalk_KUM_19_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Oh, it's a Junes apron.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Working at Junes is fun![n]Everyday's great at my Junes![n][f 1 1][e]

[msg COStalk_KUM_19_Dialo01_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Check it out! I got a promotion![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Working at Junes is fun![n]Everyday's great![n][f 1 1][e]

[msg COStalk_KUM_21_Change_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Hehehe, I changed into my clothes, but[n]now, they fully protect me against cold![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]It was chosen for me by Yosuke and the[n]part-time workers! Everything's from[n]Junes![n][f 1 1][e]

[msg COStalk_KAN_SUM_HANA [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 6 14 65535 1]Those glasses... They're Kuma's nose-[n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 6 13 65535 1]I guess you ended up liking them. [n]You and Yukiko-senpai...[n][f 1 1][e]
[f 0 5 65278][f 2 1]But man... It's kinda scary how[n]you pretty much can make anything [n]look cool...[n][f 1 1][e]

[msg COStalk_KUM_CON_OFF1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Whoa, Sensei is changing.[n][f 1 1][e]

[msg COStalk_KUM_CON_OFF2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Hm? Did you change too, Sensei?[n][f 1 1][e]

[msg COStalk_KUM_NORMAL [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]You look the best in that! I[n]instantly know that I'm looking at my[n]Sensei![n][f 1 1][e]

[msg COStalk_KUM_SUM_UNIFORM [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Sensei, you look grreaat in a white[n]shirt! You're as bright as the summer[n]sun![n][f 1 1][e]

[msg COStalk_KUM_SHIFUKU [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]I know what that shirt is! It's called a[n]polo shirt![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 65535 1]I heard Kanji talk about cloth once. He[n]said there was one called herringbone.[n]That sounds delicious![n][f 1 1][e]

[msg COStalk_KUM_WIN_SHIFUKU [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Your clothes are so fashionable.[n]You might as well be all grown-up![n][f 1 1][e]

[msg COStalk_KUM_GEKKO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Ohh? That's uniform is a different style[n]from the gakuran you usually have on.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]You look good in anything! You are truly[n]a fashionable male![n][f 1 1][e]

[msg COStalk_KUM_JOSOU [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]Wow... that's a different look.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm impressed. You boldly go your own[n]way![n][f 1 1][e]

[msg COStalk_KUM_SWIMWEAR [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]Whoa! Sensei's showin' off his bod![n]Be careful that you don't give anyone[n]a kodiak arrest![n][f 1 1][e]

[msg COStalk_KUM_JERSEY [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Sensei's wearing workout clothes![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]I know what that is! It's a knapsack[n]jersey![n][f 1 1][e]
[f 0 5 65278][f 2 1]...So when you're done, how do you carry[n]potatoes in it? Do you tie it up?[n][f 1 1][e]

[msg COStalk_KUM_SENYO1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Those are your work clothes.[n]Oh, you work at the hospital, eh...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]It's the place where the lovely angels[n]dressed in white live! I want to go[n]there, too! Take me with you, Sensei![n][f 1 1][e]

[msg COStalk_KUM_HERO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]Whoa! When did you change, Sensei?[n]You have to yell out "Transforming!" or[n]something like that![n][f 1 1][e]

[msg COStalk_KUM_TOWEL [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]Huh? What's this outfit called? Naked?[n]You're just wearing a towel.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I guess you're trying to tell us you want[n]to take a bath. Don't worry, we don't[n]have much longer.[n][f 1 1][e]

[msg COStalk_KUM_BLACKSUITS [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Hohoh, you're dressed like you're[n]preparing for a secret investigation![n]You look a lot stronger than usual![n][f 1 1][e]

[msg COStalk_KUM_HANAMEGANE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Huh? Do you like those glasses, Sensei?[n]Don't worry, they work like the normal[n]ones so you can wear them in here![n][f 1 1][e]

[msg COStalk_KUM_SUM_HANA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Nice, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]The special glasses hilarity is magnified[n]by the mismatched summer outfit![n]It's Comedy 101![n][f 1 1][e]

[msg COStalk_KUM_CHRISTMAS [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Wow, it's the real Santa![n]I want a present...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]But, not weapons or items, or anything[n]like that. A real present![n][f 1 1][e]

[msg COStalk_KUM_SUM_SHIFUKU2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]That's called a jinbei.[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's so manly! It brings out your charm![n]Yosuke's dad likes to say, "It's MANsoon[n]season!" when he wears one.[n][f 1 1][e]

[msg COStalk_KUM_HALLOWEEN [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]That's a little scary. If I saw you at[n]night, I'd be quaking in my fur![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]...Wait, that might strike fear into the[n]Shadows, too![n][f 1 1][e]

[msg COStalk_KUM_BUTLER_MAID [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Wow, Sensei looks so classy![n]I require a spot of tea...[n][f 1 1][e]

[msg COStalk_KUM_CHEER [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 65535 1]Wow, you mean business, wearing the[n]hachimaki and everything.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]It looks great, Sensei. It kinda reminds[n]me of your first Persona.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Oh, the memories...[n][f 1 1][e]

[msg COStalk_KUM_VELVETROOM [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Wow, these are really strange clothes. [n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]I feel like I've seen them somewhere...[n]But then, maybe not...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]...Eh, it's probearbly just my[n]imagination.[n][f 1 1][e]

[msg COStalk_KUM_SENYO2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Wow! That's Nana-chan's dad's outfit![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]You look great! My heart is fluttering![n]I want to start a family with you...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Where's Nana-chan's outfit? Oh, you[n]don't have hers?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]I am disappoint...[n][f 1 1][e]

[msg COStalk_KUM_SENYO2_EX [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 65535 1]Whoa! Th-That's chocolate in your mouth![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Hehehe, you can't trick THIS bear's[n]nose![n][f 1 1][e]

[msg COStalk_KUM_WIN_UNIFORM [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 65535 1]Oh... A scarf! I'm so jealous![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]The ones at Junes are too short... [n]I can't wear them over my bear suit...[n][f 1 1][e]

[msg COStalk_KUM_WIN_UNIFORM_ [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Oh... That's a scarf! Can I borrow it[n]sometime?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]Oh, but it's too short - I don't think I[n]could wear it over my bear suit...[n][f 1 1][e]

[msg COStalk_KUM_WIN_SHIFUKU2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Whoa... The smell of your clothes is[n]similar to Nana-chan's smell.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]Do you all become the same smell when you[n]live together? Family must be so nice...[n][f 1 1][e]

[msg COStalk_KUM_WIN_SHIFUKU2_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Whoa... Sensei's clothing smells so[n]good...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 65535 1]It's warm and nice![n][f 1 1][e]

[msg COStalk_KUM_LoveFirst_ON [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]Oh yeah, speaking of clothes! [n]I wanted to talk about yours.[n][f 1 1][e]

[msg COStalk_KUM_LoveFirst_OF [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]By the way, Sensei, um, your clothes...[n][f 1 1][e]

[msg COStalk_KUM_LoveDEF01_L [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 65535 1]You've been wearing that for a while.[n]How about changing?[n][f 1 1][e]

[msg COStalk_KUM_LoveDEF02_L [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 65535 1]Sensei, are you really okay constantly[n]wearing just that?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 7 65535 1]Won't the towel come off during battle?[n]That'll be super awkward![n][f 1 1][e]

[msg COStalk_KUM_CON_OFF1_OFF [Kuma]]
[f 0 5 65278][f 2 1]Whoa, Sensei changed.[n][f 1 1][e]

[msg COStalk_KUM_CON_OFF2_OFF [Kuma]]
[f 0 5 65278][f 2 1]Hm? Sensei changed.[n][f 1 1][e]

[msg COStalk_KUM_NORMAL_OFF [Kuma]]
[f 0 5 65278][f 2 1]You look the best in that![n]I can definitely tell I'm looking at my[n]Sensei![n][f 1 1][e]

[msg COStalk_KUM_SUM_UNIFORM_ [Kuma]]
[f 0 5 65278][f 2 1]Sensei, you look so good in a white[n]shirt! You radiate like the summer sun![n][f 1 1][e]

[msg COStalk_KUM_SHIFUKU_OFF [Kuma]]
[f 0 5 65278][f 2 1]I know those clothes! It's a claw-llard[n]shirt, right?[n][f 1 1][e]
[f 0 5 65278][f 2 1]It sounds dangerous...[n][f 1 1][e]

[msg COStalk_KUM_WIN_SHIFUKU_ [Kuma]]
[f 0 5 65278][f 2 1]Your clothes are so fashionable.[n]You're basically a grown-up![n][f 1 1][e]

[msg COStalk_KUM_GEKKO_OFF [Kuma]]
[f 0 5 65278][f 2 1]Ohh? That's different from the normal[n]school uniform you wear.[n][f 1 1][e]
[f 0 5 65278][f 2 1]You look good in anything! You truly are[n]a man of the city![n][f 1 1][e]

[msg COStalk_KUM_JOSOU_OFF [Kuma]]
[f 0 5 65278][f 2 1]Wow... that's unexpected.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm impressed. You boldly forge ahead on[n]your own path![n][f 1 1][e]

[msg COStalk_KUM_SWIMWEAR_OFF [Kuma]]
[f 0 5 65278][f 2 1]Whoa! Sensei's showin' off his bod![n]Be careful that you don't give anyone[n]a kodiak arrest![n][f 1 1][e]

[msg COStalk_KUM_SWIMWEAR_OFF_2 [Kuma]]
[f 0 5 65278][f 2 1]Whoa! Sensei's ripped and he knows it![n]Be careful, Sensei, your allies might[n]lose focus![n][f 1 1][e]

[msg COStalk_KUM_JERSEY_OFF [Kuma]]
[f 0 5 65278][f 2 1]Sensei is wearing some athletic rags![n][f 1 1][e]
[f 0 5 65278][f 2 1]Perfect for exercising or washing cars![n][f 1 1][e]
[f 0 5 65278][f 2 1]...Those things look pretty cheap to[n]make.[n][f 1 1][e]

[msg COStalk_KUM_SENYO1_OFF [Kuma]]
[f 0 5 65278][f 2 1]Those are your work clothes.[n]Oh, you work at the hospital, eh...[n][f 1 1][e]
[f 0 5 65278][f 2 1]That's where the angels in white live and[n]bring the sick back to health![n]I want to go there too![n][f 1 1][e]

[msg COStalk_KUM_HERO_OFF [Kuma]]
[f 0 5 65278][f 2 1]Whoa! When did you change into that,[n]Sensei? You're supposed to announce that[n]you're transforming![n][f 1 1][e]

[msg COStalk_KUM_TOWEL_OFF [Kuma]]
[f 0 5 65278][f 2 1]What are you doing, Sensei!? You're only[n]in a towel![n][f 1 1][e]
[f 0 5 65278][f 2 1]Are you trying to say that you wanna take[n]a nice long bath? Don't worry, we're[n]almost done here.[n][f 1 1][e]

[msg COStalk_KUM_BLACKSUITS_O [Kuma]]
[f 0 5 65278][f 2 1]Hohoh, you're dressed like you're ready[n]for a secret mission! You look even[n]stronger than usual![n][f 1 1][e]

[msg COStalk_KUM_HANAMEGANE_O [Kuma]]
[f 0 5 65278][f 2 1]Huh? Do you like those glasses, Sensei?[n]Don't worry, they work like the normal[n]ones![n][f 1 1][e]

[msg COStalk_KUM_SUM_HANA_OFF [Kuma]]
[f 0 5 65278][f 2 1]Nice, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]The special glasses and summer clothes[n]combo makes the glasses even more[n]hilarious![n][f 1 1][e]

[msg COStalk_KUM_CHRISTMAS_OF [Kuma]]
[f 0 5 65278][f 2 1]Wow, it's Santa! I want a present...[n][f 1 1][e]
[f 0 5 65278][f 2 1]No meat gum, please.[n][f 1 1][e]

[msg COStalk_KUM_SUM_SHIFUKU2_2 [Kuma]]
[f 0 5 65278][f 2 1]That's a jinbei.[n][f 1 1][e]
[f 0 5 65278][f 2 1]When you wear it, it brings out your[n]manly charm![n][f 1 1][e]

[msg COStalk_KUM_HALLOWEEN_OF [Kuma]]
[f 0 5 65278][f 2 1]That's kinda scary. If I saw you at[n]night, I'd flee in panic![n][f 1 1][e]
[f 0 5 65278][f 2 1]...Wait, the Shadows might get scared[n]away, too![n][f 1 1][e]

[msg COStalk_KUM_BUTLER_MAID_ [Kuma]]
[f 0 5 65278][f 2 1]Wow, Sensei looks so classy![n]I want some tea now...[n][f 1 1][e]

[msg COStalk_KUM_CHEER_OFF [Kuma]]
[f 0 5 65278][f 2 1]Wow, you're ready for some serious[n]cheering.[n][f 1 1][e]
[f 0 5 65278][f 2 1]It looks great, Sensei. I think the first[n]Persona you had looked like that too.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Brings back memories...[n][f 1 1][e]

[msg COStalk_KUM_VELVETROOM_O [Kuma]]
[f 0 5 65278][f 2 1]Wow, these are really strange clothes. [n][f 1 1][e]
[f 0 5 65278][f 2 1]I feel like I've seen those colors[n]somewhere... But then, maybe not...[n][f 1 1][e]
[f 0 5 65278][f 2 1]...I'm sure it's just my imagination.[n][f 1 1][e]

[msg COStalk_KUM_SENYO2_OFF [Kuma]]
[f 0 5 65278][f 2 1]Whoa! That's chocolate in your mouth![n][f 1 1][e]
[f 0 5 65278][f 2 1]Hehehe, you can't trick THIS bear's nose![n][f 1 1][e]

[msg COStalk_KUM_WIN_UNIFORM__2 [Kuma]]
[f 0 5 65278][f 2 1]Oh... That's a scarf! I wish you'd let[n]me borrow it![n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh, but it's too short - I don't think I[n]can wear it over my bear suit...[n][f 1 1][e]

[msg COStalk_KUM_WIN_SHIFUKU2_3 [Kuma]]
[f 0 5 65278][f 2 1]Whoa... Sensei's clothing smells so good...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's warm and nice![n][f 1 1][e]

[msg COStalk_KUM_LoveFirst_ON_2 [Kuma]]
[f 0 5 65278][f 2 1]Oh yeah, speaking of clothes! [n]I wanted to talk about yours.[n][f 1 1][e]

[msg COStalk_KUM_LoveFirst_OF_2 [Kuma]]
[f 0 5 65278][f 2 1]By the way, about your clothes...[n][f 1 1][e]

[msg COStalk_KUM_LoveDEF01_L_ [Kuma]]
[f 0 5 65278][f 2 1]You've been wearing that for a while.[n]How about changing into something new?[n][f 1 1][e]

[msg COStalk_KUM_LoveDEF02_L_ [Kuma]]
[f 0 5 65278][f 2 1]Sensei, are you okay with constantly[n]wearing that?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Won't the towel come off during battle?[n]That'll be awkwarrrrrrd![n][f 1 1][e]