[msg GK_KUMA [Kuma]]
[f 0 5 65278][f 2 1]I sense a strong Shadow in the flaming[n]room that Kanji was in.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, go and defeat it![n][f 1 1][e]

[msg KAN_021_1 [Kuma]]
[f 0 5 65278][f 2 1]This place is really steamy...[n][f 1 1][e]
[f 0 5 65278][f 2 1]So why do I feel a chill down my[n]fuzzy spine?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I think I caught a cold...[n]My nose is totally useless too.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Kanji-kun, where are you!?[n]Answer us![n][f 1 1][e]

[msg KAN_022_1 [Kuma]]
[f 0 5 65278][f 2 1]Hmmm... We haven't come across this[n]Kanji-kun yet...[n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh yeah, Sensei![n]Can I ask you something?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Why is it so steamy here? Does it have[n]something to do with Kanji-kun?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I don't really get it...[n]Do you know what it is, Sensei?[n][f 1 1][e]

[msg KAN_022_2Y [Kuma]]
[f 0 5 65278][f 2 1]I see... So there are things even[n]Sensei doesn't know about...[n][f 1 1][e]

[msg KAN_022_2N [Kuma]]
[f 0 5 65278][f 2 1]Aah, that's my Sensei! Is there[n]anything you don't know!?[n][f 1 1][e]

[msg KAN_025_3 [Kuma]]
[f 0 5 65278][f 2 1]Hrmmm... It's no good...[n][f 1 1][e]
[f 0 5 65278][f 2 1]The steam's getting worse, so I can't[n]tell where Kanji-kun is at all...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Maybe it's already time for me to retire[n]from being a guide...[n][f 1 1][e]

[msg KAN_026_1 [Kuma]]
[f 0 5 65278][f 2 1]*gasp*[n][f 1 1][e]
[f 0 5 65278][f 2 1]This feeling... The other Kanji's[n]staring at us![n][f 1 1][e]

[msg KAN_026_3 [Kuma]]
[f 0 5 65278][f 2 1]O-Oh my! It's making contact with us![n][f 1 1][e]

[msg KAN_026_5 [Kuma]]
[f 0 5 65278][f 2 1]No! Sensei came to rescue Kanji![n][f 1 1][e]

[msg KAN_026_7 [Kuma]]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei... This little bear's getting[n]too scared to go on...[n][f 1 1][e]

[msg KAN_028_3 [Kuma]]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Hey, Sensei?[n][f 1 1][e]
[f 0 5 65278][f 2 1]The world you came from seems really[n]complicated...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Ever since I met you, I really had to[n]think hard about stuff like what I am...[n][f 1 1][e]
[f 0 5 65278][f 2 1]So I can kinda understand how[n]Kanji feels.[n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, we gotta save Kanji![n][f 1 1][e]

[msg KAN_029_3 [Kuma]]
[f 0 5 65278][f 2 1]S-Something definitely feels wrong![n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, we need to hurry![n][f 1 1][e]

[msg KAN_030 [Kuma]]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]I can't hear Kanji's voice...[n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Alrighty![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm gonna get myself pumped up again[n]to look for Kanji![n][f 1 1][e]
[f 0 5 65278][f 2 1]Concentrate! Raaaaaaaaawr![n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Here goes![n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Whoa... this feeling! I think I've[n]made a comeback![n][f 1 1][e]
[f 0 5 65278][f 2 1]Kanji's not far from here![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm positive he's really close by![n][f 1 1][e]

