[msg RIS_041 [Kuma]]
[f 0 5 65278][f 2 1]Hrmmm... This smell, this atmosphere...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's making my heart pound![n][f 1 1][e]

[msg RIS_042_1 [Kuma]]
[f 0 5 65278][f 2 1]Sensei, are you okay?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I think I'm getting a little drunk from[n]all the pink...[n][f 1 1][e]

[msg RIS_044_3 [Kuma]]
[f 0 5 65278][f 2 1]I've had enough of this place too![n]Urgh, I'm getting all dizzy...[n][f 1 1][e]

[msg RIS_045_1 [Kuma]]
[f 0 5 65278][f 2 1]Sensei, are you all right?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Why don't we call it a day today?[n]I'm getting really dizzy...[n][f 1 1][e]

[msg RIS_045_3 [Kuma]]
[f 0 5 65278][f 2 1]...![n][f 1 1][e]
[f 0 5 65278][f 2 1]S-Sensei! I'm gonna try even harder![n][f 1 1][e]

[msg RIS_046_2 [Kuma]]
[f 0 5 65278][f 2 1]Whaa...?[n][f 1 1][e]
[f 0 5 65278][f 2 1]We're desperately trying to save her,[n]but she's cheering us on instead...?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I don't know how to feel about this...[n][f 1 1][e]

[msg RIS_048_2 [Kuma]]
[f 0 5 65278][f 2 1]What's this?[n][f 1 1][e]
[f 0 5 65278][f 2 1]What's she up to?[n][f 1 1][e]

[msg RIS_048_4 [Kuma]]
[f 0 5 65278][f 2 1]L...[n][f 1 1][e]
[f 0 5 65278][f 2 1]LAAAAME![n][f 1 1][e]

[msg RIS_049_2 [Kuma]]
[f 0 5 65278][f 2 1]It's really fulfilling for me too,[n]since I'm with you guys, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]Thank you, Sensei![n][f 1 1][e]

[msg RIS_050_2 [Kuma]]
[f 0 5 65278][f 2 1]I see... So one's insides are[n]important...[n][f 1 1][e]
[f 0 5 65278][f 2 1]But I'm all empty...[n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]