[msg GK_KUMA [Kuma]]
[f 0 5 65278][f 2 1]I sense the presence of a strong Shadow[n]in the room Yuki-chan was in.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, you should defeat it![n][f 1 1][e]

[msg KUMA_FOR_CHIE [Kuma]]
[f 0 5 65278][f 2 1]She hasn't gone that far yet.[n][f 1 1][e]

[msg HELP_KUMA_ENCOUNT_1 [Kuma]]
[f 0 5 65278][f 2 1]Um, wait a second![n][f 1 1][e]
[f 0 5 65278][f 2 1]The Shadows have gotten aggravated ever[n]since you two got here.[n][f 1 1][e]
[f 0 5 65278][f 2 1]They'll probably attack as soon as they[n]find you, Sensei.[n][f 1 1][e]
[f 0 5 65278][f 2 1]So try to get the jump on Shadows before[n]they can attack you![n][f 1 1][e]

[msg KUMA_FOR_YUKIKO [Kuma]]
[f 0 5 65278][f 2 1]Anyways, I don't sense anyone around[n]this area.[n][f 1 1][e]
[f 0 5 65278][f 2 1]If you go further ahead, we might be[n]able to find something.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Be careful and move on.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh! But don't get too excited in tracking[n]her down![n][f 1 1][e]
[f 0 5 65278][f 2 1]If you forget how to get back here, not[n]even I will be able to help you![n][f 1 1][e]

[msg HELP_MAP_1 [Kuma]]
[f 0 5 65278][f 2 1]Hrmm...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, can I bother you for a second?[n][f 1 1][e]
[f 0 5 65278][f 2 1]The hall here seems different from[n]before, so this place might get[n]pretty tricky...[n][f 1 1][e]
[f 0 5 65278][f 2 1]But I'm with you! Don't you worry,[n]Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]Leave it to me to show the way![n][f 1 1][e]

[msg HELP_MAP_2 [Kuma]]
[f 0 5 65278][f 2 1]Hrmm...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, can I bother you for a second?[n][f 1 1][e]
[f 0 5 65278][f 2 1]The hall here seems different from[n]before, so this place might get[n]pretty tricky...[n][f 1 1][e]
[f 0 5 65278][f 2 1]But I'm with you! Don't you worry,[n]Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]Leave it to me to show the way![n][f 1 1][e]

[msg YUKI_008_3 [Kuma]]
[f 0 5 65278][f 2 1]Hrmm...[n]I hear her voice...[n][f 1 1][e]
[f 0 5 65278][f 2 1]But all I sense around here are you[n]and Shadows.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Watch out for the Shadows, and keep going![n][f 1 1][e]

[msg YUKI_008_4 [Kuma]]
[f 0 5 65278][f 2 1]When a Shadow has its back to you,[n]carefully get in close and smack it![n][f 1 1][e]

[msg YUKI_009_3 [Kuma]]
[f 0 5 65278][f 2 1]...What's this voice talking about?[n][f 1 1][e]
[f 0 5 65278][f 2 1]This place isn't an inn. It's totally[n]a castle![n][f 1 1][e]

[msg YUKI_011_8 [Kuma]]
[f 0 5 65278][f 2 1]I don't get what's going on with all[n]those voices, but I can sense that we're[n]getting closer.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Hang in there![n][f 1 1][e]

[msg YUKI_012_3 [Kuma]]
[f 0 5 65278][f 2 1]It's close![n][f 1 1][e]
[f 0 5 65278][f 2 1]She's just beyond here![n][f 1 1][e]