[msg MSG_KUMA_1 [Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 439]Defend yourself like that Shadow's[n]doing! Then you can cover up your[n]weakness![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 440]Whenever you feel threatened,[n]just defend yourself![n][f 1 3 65535][f 1 1][e]

[msg MSG_KUMA_2 [Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 409]This one's much stronger than the[n]last type! Be careful![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 440]Whenever you feel threatened,[n]just defend yourself![n][f 1 3 65535][f 1 1][e]