[msg MSG_BTLSTART_000 [Shadow Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 3 1309]I am a shadow... The true self...[n][f 1 3 65535][f 1 1][e]

[msg MSG_BTLSTART_001 [Shadow Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 3 1354]I shall give you the "truth" you claim[n]to hold so dear...[n][f 1 3 65535][f 1 1][e]

[msg MSG_BTLSTART_001_02 [Shadow Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 3 1355]The inescapable fact of your death here![n][f 1 3 65535][f 1 1][e]

[msg MSG_BTLSTART_002 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 14 1 1][f 3 1 3 0 3 496]Was that creepy thing really inside[n]our Kuma...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_BTLSTART_005 [Shadow Kuma]]
[f 0 5 65278][f 2 1][f 4 7 3 14 1][f 4 7 2 12 1][f 3 1 3 0 3 1150]Foolish beings! Accept your end with[n]dignity and grace![n][f 1 3 65535][f 1 1][e]

[msg MSG_HP_75 [Shadow Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 3 1133]Stop this futile struggling. Even if you[n]resist, it will all come to naught...[n][f 1 3 65535][f 1 1][e]

[msg MSG_HP_50 [Shadow Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 3 1134]What...? How can you summon such[n]strength for such a futile endeavor...!?[n][f 1 3 65535][f 1 1][e]

[msg MSG_HP_25 [Shadow Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 3 1135]Why do you still resist...!? Even should[n]you win, naught but suffering awaits![n][f 1 3 65535][f 1 1][e]