[msg MSG_BTLSTART_000 [Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 434]Stay calm and listen.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BTLSTART_001 [Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 435]Some Shadows have weaknesses.[n][f 1 3 65535][f 1 1][e]

[msg MSG_BTLSTART_002 [Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 436]I can tell this one has a weakness too![n][f 1 3 65535][f 1 1][e]

[msg MSG_BTLSTART_003 [Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 437]If you can pinpoint that weakness[n]and take advantage of it, the battle[n]will be a lot easier![n][f 1 3 65535][f 1 1][e]

[msg MSG_BTLSTART_004 [Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 438]Try stuff out and see what works![n][f 1 3 65535][f 1 1][e]

[msg MSG_BTL1MORE [Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 406]Ooh, you hit its weakness! Now go for[n]another attack while it's stunned![n][f 1 1][e]

[msg MSG_BTLANLZ_001 [Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 443]I'll keep track of what attacks have[n]what effects on enemies![n][f 1 3 65535][f 1 1][e]

[msg MSG_BTLANLZ_002 [Kuma]]
[f 0 5 65278][f 2 1][f 3 1 3 0 5 444]If you want to know what we've learned[n]about Shadows, just ask me![n][f 1 3 65535][f 1 1][e]