[msg MSG_000]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]> When you arrive at home, Kuma is[n]there to greet you...[n][f 1 3 65535][f 1 1][e]

[msg MSG_001 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]WEL! COME! HO! MMMMMMMMM![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I've been waiting forevvvvvvvver[n]and evvvvvvvver for this day![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Now now now, come in, come in! Gimme one[n]of those "Honey, I'm home" kisses![n][f 1 3 65535][f 1 1][e]

[msg MSG_002 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Oh, don't be so shy. Smoochy-smoochy![n]Come on, pleeeeeeash?[n][f 1 3 65535][f 1 1][e]

[msg MSG_004 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Gyaaaaaaah! My bearamones are too[n]powerful! I came on too strong![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Stop! Break! Cut![n]It's all a mistake![n][f 1 3 65535][f 1 1][e]

[msg MSG_005 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Th-That's mean...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]I'm sure Nana-chan wouldn't be so mean...[n][f 1 3 65535][f 1 1][e]

[msg MSG_006 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Today's the day Nana-chan comes back,[n]so I've been practicing hard to greet her.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hey, if it was you, how would you like to[n]be welcomed home, Sensei?[n][f 1 3 65535][f 1 1][e]

[msg MSG_008 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]All right, Sensei![n]I knew I could count on you![n][f 1 3 65535][f 1 1][e]

[msg MSG_009 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Oh, it's a bear hug! I can do that![n]My heart's beating so fast...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]...I feel like I'm being swept away.[n][f 1 3 65535][f 1 1][e]

[msg MSG_011 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Hmmmmmmm. I don't get it.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Try demonstrating it on me.[n][f 1 3 65535][f 1 1][e]

[msg MSG_012 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Oh, it's a bear hug! I can do that![n]My heart's beating so fast...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]...I feel like I'm being swept away.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]All right, I think I get it![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Hey, I've got a whole little show to[n]go along with it. Let me show you![n][f 1 3 65535][f 1 1][e]

[msg MSG_015 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Nana-chan~ Ohhhhhhh~![n]You are a shining star~![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Come home well, and[n]WEL! COME! HOOOOOOOME~![n][f 1 3 65535][f 1 1][e]

[msg MSG_017 [Nanako]]
[f 0 5 65278][f 2 1][f 4 6 10 1 65535 1][f 3 1 1 0 0 0]Big bro! I'm home![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Oh! Kuma's here, too![n][f 1 3 65535][f 1 1][e]

[msg MSG_018 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Nana-chan! You're all better![n][f 1 3 65535][f 1 1][e]

[msg MSG_024 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Okay, well, I was able to say hello to[n]Nana-chan, so I guess I'll be going now.[n][f 1 3 65535][f 1 1][e]

[msg MSG_026 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Now that you're home, Sensei won't be[n]lonely anymore, so...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 0]Plus, I'm not a family member...[n][f 1 3 65535][f 1 1][e]

[msg MSG_028 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Sensei... So I can stay here...?[n][f 1 3 65535][f 1 1][e]

[msg MSG_031 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]Pops...! I'm such a lucky bear...![n][f 1 3 65535][f 1 1][e]

[msg MSG_038 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0]It's so good! So good! So good![n][f 1 3 65535][f 1 1][e]