[msg MSG_001 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 4 65535 1]Kuma probably gets lonely if we don't[n]show up every once a while...[n][f 1 1][e]

[msg MSG_007 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 5 65535 1]Listen to this, [f 4 2]-kun![n]I saw Kuma in the screen![n][f 1 1][e]

[msg MSG_012 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 2 65535 1]This may sound strange, [f 4 2]-kun,[n]but I think I heard Kuma-chan's voice[n]during class.[n][f 1 1][e]

[msg MSG_013 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 1 65535 1]I thought I might have been imagining[n]it... But I figure Kuma-chan may be[n]bored all by himself.[n][f 1 1][e]

[msg MSG_021 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 5 2 65535 1]Haha, I'm just kidding! Really, I'm[n]bored. Do you wanna go see Kuma-chan's[n]place today?[n][f 1 1][e]

[msg MSG_022 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 5 3 65535 1]Senpai! D-Did you see Kuma-chan[n]during lunch!?[n][f 1 1][e]

[msg MSG_025 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 3 65535 1]Senpai, what do you think Kuma[n]is doing?[n][f 1 1][e]