[msg YOU_NIGHT08_TALK01_MES_S [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 1304][f 4 9 2 3 5 0 5][f 4 6 2 9 65535 1]You know how Kuma's working at my place?[n]That bear's out of control...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 8 65535 1]He eats the meat at the tasting tables,[n]falls asleep on the massage chairs...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 2 3 5 0 5]Then on top of all that, he won't shut up[n]about getting Junes to carry Topsicles.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 8 2 10]Meanwhile, I'm the one who gets yelled at[n]by the manager! Like I'm his trainer or[n]something.[n][f 1 1][e]

[msg YOU_NIGHT09_TALK01_MES_E [Yosuke]]
[f 0 5 65278][f 2 1][f 4 9 2 3 5 0 5][f 4 6 2 1 65535 1]That reminds me, Kuma's been acting fidgety[n]lately for some reason...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 4 65535 1]I hope it's nothing, but I'm still keeping[n]my fingers crossed he doesn't try anything[n]funny.[n][f 1 1][e]

[msg YOU_NIGHT09_TALK03_MES_S [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 1304][f 4 9 2 3 5 0 5][f 4 6 2 9 65535 1]That Kuma is giving me real headaches.[n]He's surprisingly shrewd.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 1 65535 1]He was broke during our school trip, so I[n]gave him some money to spend...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 5 65535 1][f 4 8 2 10]I don't know when he did it, but he bought[n]souvenirs for my parents. You should have[n]seen them! "He's so thoughtful," they said...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 2 3 5 0 5][f 4 6 2 8 65535 1]I got stuck in an awkward position because[n]I'd run out of money from giving mine to[n]Kuma![n][f 1 1][e]

[msg YOU_NIGHT10_TALK02_MES_S [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 1304][f 4 9 2 3 5 0 5][f 4 6 2 9 65535 1]Man, that Kuma's done it again. We're doing[n]"Mushroom Days" at Junes now...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 8 2 15]But Kuma got the matsutake and shiitake[n]mushrooms mixed up, and sold some super[n]expensive ones for dirt cheap...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 2 3 5 0 5][f 4 6 2 8 65535 1]Could he not tell from the size difference!?[n]That bear's nose is completely useless.[n][f 1 1][e]

[msg YOU_NIGHT12_TALK02_MES_S [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 33][f 4 9 2 3 5 0 5][f 4 6 2 2 65535 1]This doesn't go farther than you and me, but[n]man, for once I'm glad Kuma works for us.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 1 65535 1]The mood around the store has been awful[n]because of the fog. The employees, the[n]customers, everyone seems unsettled...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 2 3 5 0 5][f 4 6 2 2 65535 1][f 4 8 2 10]But when Kuma's around, things kinda go[n]back to normal. He might be consciously[n]trying to cheer everyone up.[n][f 1 1][e]

[sel YOU_NIGHT12_TALK02_MES_S_2 top]
[f 0 5 65278][f 2 1]"Kuma's doing his part."[e]
[f 0 5 65278][f 2 1]"Kuma's used to the fog."[e]
[f 0 5 65278][f 2 1]"I doubt he's consciously doing it."[e]

[msg YOU_NIGHT12_TALK02_MES_E [Yosuke]]
[f 0 5 65278][f 2 1][f 4 9 2 3 5 0 5][f 4 6 2 2 65535 1]Don't tell Kuma I said that, okay? He gets[n]carried away too easy.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I mean, just the other day...[n][f 1 1][e]

[msg YOU_NIGHT12_TALK03_MES_A [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 1329][f 4 6 2 2 65535 1][f 4 8 2 5]Yeah! Hmm, but what should we do to ring in[n]the new year? Oh, why don't we go touring[n]on our motorcycles?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Hmm, wait, lounging around the kotatsu and[n]playing fighting games sounds good too...[n]Kuma's damn good at those, you know![n][f 1 1][e]

[msg YOU_NIGHT01_TALK01_MES_S [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 1304][f 4 9 2 3 5 0 5][f 4 6 2 9 65535 1]Man... The other day, a bigwig from the Junes[n]main office came to inspect our branch.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 8 65535 1][f 4 8 2 10]And he was really interested in Kuma.[n]Said he wants Kuma to be their exclusive[n]model...[n][f 1 1][e]

[msg YOU_NIGHT01_TALK01_MES_A [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24][f 4 6 2 9 65535 1][f 4 8 2 8]No, the thing is... he wasn't talking about[n]the costume, but the boy-Kuma inside.[n][f 1 1][e]
[f 0 5 65278][f 2 1]You know how no one in the real world knows[n]what he really is. We'll be in big trouble[n]if that gets exposed...[n][f 1 1][e]

[msg YOU_NIGHT01_TALK01_MES_B [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 24][f 4 6 2 4 65535 1][f 4 8 2 8]Seriously...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 2 3 5 0 5]It would be one thing if he was talking[n]about the costume, but hiring boy-Kuma[n]as a model...?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 9 65535 1]No one in the real world knows what he is.[n]We'll be in big trouble if that gets[n]exposed...[n][f 1 1][e]

[msg YOU_NIGHT01_TALK01_MES_C [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 1289][f 4 6 2 5 65535 1][f 4 8 2 24][f 3 1 5 0 0 195]Oh, seriously? Hmm, I guess you'd be[n]photogenic enough...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 4 65535 1]Wait, no, that won't work.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 1 65535 1]It has to be a current employee. The bigwig[n]was dead set on that.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 2 3 5 0 5]And I mean, if it was just the costume, that[n]would be fine. But he wants to use boy-Kuma[n]as the model...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 9 65535 1]No one in the real world knows what he is.[n]We'll be in big trouble if that gets[n]exposed...[n][f 1 1][e]

[msg YOU_NIGHT01_TALK02_MES_S [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5][f 4 9 2 3 5 0 5][f 4 6 2 2 65535 1]So, is Kuma causing you any trouble? I know[n]how he can get into everything.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 4 65535 1]He's had his paws in my stuff all year.[n]He's ruined my manga, broke my consoles...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 2 65535 1][f 4 8 2 10]Don't hesitate to tell me if you reach[n]your wits' end. You can return him anytime[n]you want.[n][f 1 1][e]

[msg YOU_NIGHT01_TALK03_MES_S [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 5][f 4 9 2 3 5 0 5][f 4 6 2 1 65535 1]Man, Kuma's been all hyper ever since he[n]got back.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 8 65535 1]He even makes a big fuss at dinner or while[n]taking a bath... I yell at him to calm down,[n]but he just doesn't listen.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 2 3 5 0 5][f 4 8 2 15]That creep snuck into my bed, being all,[n]"Weren't you lonely without me, Yosuke?"[n][f 1 1][e]

[sel YOU_NIGHT01_TALK03_MES_S_2 top]
[f 0 5 65278][f 2 1]"That's horrifying."[e]
[f 0 5 65278][f 2 1]"You guys get along great."[e]
[f 0 5 65278][f 2 1]"Aww, Kuma was lonely too."[e]

[msg YOU_NIGHT01_TALK03_MES_A [Yosuke]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 1304][f 4 6 2 9 65535 1][f 4 8 2 8]Isn't it? What did I do to deserve having[n]to sleep right next to Kuma?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 2 65535 1]Well, if he's cutting loose because he was[n]behaving himself at your place, I guess[n]that's okay.[n][f 1 1][e]