[msg BU1_NIGHT11_TALK01_MES_E [Yumi]]
[f 0 5 65278][f 2 1][f 4 9 900 3 5 0 5][f 4 6 30 1 65535 1]But, still... who was that Kuma guy?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 8 900 10]He had a strange aura to him.[n]Definitely an interesting person.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 900 3 5 0 5]He's going to be a huge star one day![n]I mean, did you see him? I could tell[n]by the way he walked his walk...[n][f 1 1][e]

[msg BU1_NIGHT11_TALK01_MES_E_2 [Yumi]]
[f 0 5 65278][f 2 1][f 4 9 900 3 5 0 5][f 4 6 30 1 65535 1]But, still... who was that Kuma guy?[n][f 1 1][e]
[f 0 5 65278][f 2 1]He had a strange aura to him.[n]Definitely an interesting person.[n][f 1 1][e]
[f 0 5 65278][f 2 1]He's going to be a huge star one day![n]I mean, did you see him? I could tell[n]by the way he walked his walk...[n][f 1 1][e]

[msg BU1_NIGHT11_TALK01_MES_E_3 [Yumi]]
[f 0 5 65278][f 2 1][f 4 9 900 3 5 0 5][f 4 6 30 1 65535 1]But, still... who was that Kuma guy?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 30 2 65535 1]He had a strange aura to him.[n]Definitely an interesting person.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 900 3 5 0 5][f 4 6 30 5 65535 1][f 4 8 900 10]He's going to be a huge star one day![n]I mean, did you see him? I could tell[n]by the way he walked his walk...[n][f 1 1][e]