[msg YUK_NIGHT05_TALK02_MES_C [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 81][f 4 6 4 2 65535 1][f 4 8 4 0]You mean... Kuma from the TV world?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 89][f 4 9 4 24 5 25 5][f 4 6 4 7 65535 1][f 4 8 4 10]Snrk...! Heeheehee! Enlisting a bear...[n]Kuma helping at the inn...[n][f 1 1][e]

[msg YUK_NIGHT05_TALK03_MES_C [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 81][f 4 6 4 5 65535 1][f 4 8 4 0]You mean... Kuma from the TV world?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 89][f 4 9 4 23 5 24 5][f 4 6 4 7 65535 1][f 4 8 4 10]Snrk...! Heeheehee! Enlisting a bear...[n]Kuma helping at the inn...[n][f 1 1][e]

[msg YUK_NIGHT08_TALK02_MES_C [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 1377][f 4 6 4 2 65535 1][f 4 8 4 10]Yeah, that sounds great. Kuma's very[n]popular amongst the kids.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 1 65535 1]But I bet it must be hot inside those[n]costumes. I hear that you sweat a lot...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 8 4 2]...Do you think Kuma is waterproof?[n]I wonder if there's any way we could put[n]that to the test.[n][f 1 1][e]

[msg YUK_NIGHT10_TALK01_MES_A [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 86][f 4 6 4 2 65535 1][f 4 8 4 10]Oh, that's a great idea! I bet our guests[n]with children would be delighted.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I should ask Kuma what kind of candy[n]kids like.[n][f 1 1][e]

[msg YUK_NIGHT10_TALK02_MES_S [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 60][f 4 9 4 3 5 0 5][f 4 6 4 2 65535 1]You know, Kuma's been the number one[n]subject of conversation among the girls[n]at school.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 8 4 10]He leaves as suddenly as he appears, so they[n]call him the "Shooting Star Prince."[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 4 3 5 0 5]Apparently, some of the girls follow him[n]all the way to Junes and give him snacks.[n][f 1 1][e]
[f 0 5 65278][f 2 1]He might become a homegrown Inaba idol at[n]this rate.[n][f 1 1][e]

[msg YUK_NIGHT10_TALK02_MES_A [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 1377][f 4 6 4 2 65535 1][f 4 8 4 10]Ooh, he'd have all the bases covered! He can[n]sing, dance, and wear a costume![n][f 1 1][e]
[f 0 5 65278][f 2 1]It might not be long before Kuma even[n]shows up on Junes commercials.[n][f 1 1][e]

[msg YUK_NIGHT10_TALK02_MES_C [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 86][f 4 6 4 2 65535 1][f 4 8 4 24][f 3 1 5 0 0 195]Well, why don't the two of you make your[n]debuts together!?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 7 65535 1]Kuma would be the comedian... so I guess[n]you could be his straight man?[n][f 1 1][e]

[msg YUK_NIGHT10_TALK02_MES_E [Yukiko]]
[f 0 5 65278][f 2 1][f 4 9 4 3 5 0 5][f 4 6 4 2 65535 1]Kuma has this mysterious charm about him[n]that draws people in.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Every time I see him at Junes, he's always[n]surrounded by fans.[n][f 1 1][e]

[msg YUK_NIGHT11_TALK02_MES_S [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 60][f 4 9 4 3 5 0 5][f 4 6 4 2 65535 1]So it seems that Ms. Kashiwagi and Hanako-san[n]were staying at our inn after the Culture[n]Festival too.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 1 65535 1]Kuma told me about it, but it was news[n]to me...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 4 3 5 0 5][f 4 8 4 10]He seemed depressed when he mentioned it[n]for some reason, though.[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Did something happen?[n][f 1 1][e]

[msg YUK_NIGHT11_TALK02_MES_C [Yukiko]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 81][f 4 6 4 5 65535 1][f 4 8 4 2]Huh? You either? Kuma said the same thing.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 1 65535 1]But he seemed frightened, too...[n]Did something scary happen?[n][f 1 1][e]