[msg RIS_NIGHT08_TALK01_MES_E [Rise]]
[f 0 5 65278][f 2 1][f 4 9 5 14 5 13 5][f 4 6 5 1 65535 1]Oh, I had a thought when I was studying road[n]signs for the license exam...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 8 5 10]Don't you think Junes needs a Kuma Crossing[n]sign?[n][f 1 1][e]

[msg RIS_NIGHT10_TALK02_MES_E [Rise]]
[f 0 5 65278][f 2 1][f 4 9 5 14 5 13 5][f 4 6 5 1 65535 1]They had other Halloween stuff besides[n]costumes, like a pumpkin you wear on[n]your head.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 5 2 65535 1]I bet that'd look good on Kuma... Oh, wait,[n]he's already in costume.[n][f 1 1][e]

[msg RIS_NIGHT11_TALK01_MES_C [Rise]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 330][f 4 6 5 3 65535 1][f 4 8 5 0]Whaaat? Ugh, Kuma is rubbing off on you![n]What will you do if you fall and hurt[n]yourself, huh?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 342][f 4 9 5 14 5 13 5]Don't try and manufacture any more legends,[n]okay?[n][f 1 1][e]

[msg RIS_NIGHT11_TALK01_MES_E [Rise]]
[f 0 5 65278][f 2 1][f 4 9 5 14 5 13 5][f 4 6 5 1 65535 1]Mmm, I think I'll pass on doing any more[n]concerts for a while. It's not like I'm back[n]into showbiz yet.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 8 5 24][f 3 1 5 0 0 195]Oh, but hmm. If I wear Kuma's costume,[n]maybe people won't know it's Risette.[n][f 1 1][e]

[msg RIS_NIGHT11_TALK02_MES_A [Rise]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 315][f 4 6 5 1 65535 1][f 4 8 5 10]Y-You're right... I'm not going to let him[n]out-girl me![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 5 2 65535 1]I'm gonna go practice! Hmm, where should I[n]start... I wonder if Kuma has any rips[n]in his costume.[n][f 1 1][e]