[msg SP1_NIGHT11_TALK01_MES_S [Kou]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 617][f 4 9 900 14 5 13 5][f 4 6 23 1 65535 1]I'm still shocked about the Culture[n]Festival. I didn't know you were like[n]that, man...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 23 2 65535 1][f 4 8 900 8]I mean, everybody on the team voted for[n]you, but we couldn't beat the massive[n]popularity of that Kuma-kun...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 900 14 5 13 5]Sorry that we couldn't turn the tide![n]I should've asked my classmates, too![n][f 1 1][e]

[msg SP1_NIGHT11_TALK01_MES_B [Kou]]
[f 0 5 65278][f 2 1][f 3 1 1 0 0 605][f 4 6 23 2 65535 1][f 4 8 900 8]Sorry. That Kuma-kun came outta nowhere.[n]That wasn't in my plans.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 9 900 14 5 13 5]You were close, though! I asked about[n]the vote count, and they said you came[n]in second.[n][f 1 1][e]

[msg SP1_NIGHT02_TALK01_MES_E [Kou]]
[f 0 5 65278][f 2 1][f 4 9 900 14 5 13 5][f 4 6 23 1 65535 1]Kuma-kun was at the register when he[n]bought them. You remember that guy?[n]From the cross-dressing pageant?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 8 900 10]He called Daisuke "Kanji Two!"[n]What's that supposed to mean...?[n][f 1 1][e]