[msg MSG_MUSITORI_PREOPEN_010 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 81 0 1]Here, here! Try digging here![n][f 1 1][e]

[msg MSG_MUSITORI_PREOPEN_020 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 84 0 1]Look, Sensei! Something's coming out![n][f 1 1][e]

[msg MSG_MUSITORI_PREOPEN_040 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 80 0 1]So when it snows, bugs burrow into[n]the ground...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 81 0 1]Heeheehee, they're so shy![n][f 1 1][e]
[f 0 5 65278][f 2 1]I bet Nana-chan will be surprised when we[n]tell her we harvested a bug![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 83 0 1]Hrgh... Sensei, my hands are getting cold...[n][f 1 1][e]
[f 0 5 65278][f 2 1]We can't have you getting sick again too.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's go back inside and warm up with[n]the kotatsu.[n][f 1 1][e]

[msg MSG_MUSITORI_010 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 81 0 1][f 3 1 1 0 0 2051]Woohoo![n][f 1 1][e]
[f 0 5 65278][f 2 1]Time to dig! Dig and dig and dig some more![n][f 1 1][e]

[msg MSG_MUSITORI_020 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 81 0 1]Ah, there it is! I found one![n][f 1 1][e]

[msg MSG_MUSITORI_040 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 83 0 1]Hrgh...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, my hands are getting cold...[n]I'm at my limit...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I wanna go back inside and warm up with[n]the kotatsu...[n][f 1 1][e]