[msg MSG_KUMA_GREAT [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Wow, Sensei! Me rooting for you really did[n]the trick![n][f 1 1][e]

[msg MSG_KUMA_GOOD [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You did it, Senpai! Next time, try and catch[n]even more![n][f 1 1][e]

[msg MSG_KUMA_BAD [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hrmm... That didn't go so good. Oh well,[n]we'll make up for it some other day![n][f 1 1][e]

[msg MSG_KUMA_NG [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Tires, tires, tires... Looks like we'll be[n]having a tire party tonight![n][f 1 1][e]

