[msg MSG_002_001]
[f 0 5 65278][f 2 1]> You see Yosuke and Kuma a little ways[n]off from you...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> They don't seem to notice you. You hear them[n]talking to each other...[n][f 1 1][e]

[msg MSG_002_003 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 71 0 1][f 3 1 1 0 0 2007]Bring it on! A useless Kuma is no Kuma[n]at all![n][f 1 1][e]

[msg MSG_002_005 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 73 0 1]......[n][f 1 1][e]

[msg MSG_002_007 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 71 0 1]...The snacks in the back look delicious.[n][f 1 1][e]

[msg MSG_002_009 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 71 0 1]Hey, Yosuke! When is snack time at Junes?[n][f 1 1][e]

[msg MSG_002_011]
[f 0 5 65278][f 2 1]> Yosuke and Kuma leave...[n][f 1 1][e]

[msg MSG_005_008 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 1 65535 1][f 3 1 1 0 0 62]Awww... Then what should I do?[n][f 1 1][e]
[f 0 5 65278][f 2 1]With everything that happened last year,[n]I realized a lot of things, and felt like[n]I was able to change.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 2 65535 1]So, just like how Kuma became Kuma 2.0,[n]I want to become Yukiko Amagi 2.0![n][f 1 1][e]