[msg MSG_KUMA_SUMMER [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]We made it here in the blink of an eye...[n]Seeing you become one with the wind on[n]your scooter was so inspiring![n][f 1 1][e]
[f 0 5 65278][f 2 1]Though going uphill on sheer manpower...[n]or bearpower, anyway, was still tough...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh, you're going to fish today? I'm sure[n]you'll charm those fishies right into your[n]boat, Sensei![n][f 1 1][e]

[msg MSG_KUMA_FALL [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whee! We are the wind![n][f 1 1][e]
[f 0 5 65278][f 2 1]Hey Sensei, if you're gonna fish, I want to[n]catch a mermaid![n][f 1 1][e]
[f 0 5 65278][f 2 1]Hopefully one that's put some fat on her[n]chest! The softer looking, the better![n][f 1 1][e]

[msg MSG_KUMA_WINTER [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]So cold...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I think we're more likely to catch a cold[n]than catch any fish...[n][f 1 1][e]
[f 0 5 65278][f 2 1]But I'll follow you anywhere you ask me to,[n]Sensei![n][f 1 1][e]

[msg MSG_KUMA_MIST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hrm?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Say, the fog... I don't see it here.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I bet the even the fog has decided to be[n]nice to us![n][f 1 1][e]