[msg MSG_HEYA_SUGUNERU_EVT_02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]Huh...?[n][f 1 1][e]

[msg MSG_HEYA_SUGUNERU_EVT_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]S-S-S-S-Sensei!?[n][f 1 1][e]

[msg MSG_HEYA_SUGUNERU_EVT_04]
[f 0 5 65278][f 2 1]> You can hear Kuma's voice from[n]far away...[n][f 1 1][e]

[msg TUUHAN__TODOKU_00_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 65535 1]Oh, somebody came with a package for[n]you, Sensei! I put it on the table![n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0010 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 886]Welcome back.[n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0020 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 888]Ooh, the Sensei is back![n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0030 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 890]Welcome home, big bro![n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0040 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 892]You're home![n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0050 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 894]Welcome home![n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0103 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Thanks for helping me unpack![n][f 1 1][e]
[f 0 5 65278][f 2 1]You and me, sleeping under the same[n]roof from now on![n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0105 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 886]Welcome back.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, where do you put "the goods?"[n]Oh, I know, in the drawer?[n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0106 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 892]You're back![n][f 1 1][e]
[f 0 5 65278][f 2 1]Just was really busy. I was the star of[n]the show![n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0113 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 888]Oh, Sensei's home![n][f 1 1][e]
[f 0 5 65278][f 2 1]Heheheh, it's time for dinner.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Your cooking is so good! I'm gonna get[n]all fat![n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0116 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 886]Welcome home.[n][f 1 1][e]
[f 0 5 65278][f 2 1]One of the neighbors was asking me if[n]I was an "exchange student."[n][f 1 1][e]
[f 0 5 65278][f 2 1]I told her, "No, I'm Kuma!" [n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0119 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 890]Welcome back, big bro![n][f 1 1][e]
[f 0 5 65278][f 2 1]Tomorrow is the day Nana-chan leaves the[n]hospital. She's coming home![n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0119_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 890]Welcome back, big bro![n][f 1 1][e]
[f 0 5 65278][f 2 1]Are you going to take a bath? Or do you[n]want to eat first?[n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0109 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 886]Welcome home.[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's snowing outside. I wanna go skiing[n]again...[n][f 1 1][e]

[msg MSG_KUMA_COMINGHOME_0111 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 888]Oh, Sensei's home![n][f 1 1][e]
[f 0 5 65278][f 2 1]It stopped snowing, right? Leave the[n]laundry to me![n][f 1 1][e]

[msg MSG_KUMA_HOLYDAYFARM_NOR [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Sensei, you were really at work at the[n]garden.[n][f 1 1][e]

[msg MSG_KUMA_HOLYDAYMYROOM_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Oh, you came down. What are you gonna[n]do today?[n][f 1 1][e]

[msg MSG_KUMA_HOLYDAYMYROOM_Y [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Ooh, you came down.[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's going to snow tomorrow.[n][f 1 1][e]

[msg MSG_KUMA_HOLYDAYMYROOM_Y_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Oh, you've come down.[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's gonna be snowing tomorrow, too.[n][f 1 1][e]

[msg MSG_KUMA_BOXLUNCH [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]I got a lot of leftover food from Junes![n][f 1 1][e]
[f 0 5 65278][f 2 1]The fridge is packed![n][f 1 1][e]

[msg MSG_KUMA_FARMFIELD_NUT_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Say, those vegetables you have in the[n]garden look really good...[n][f 1 1][e]

[msg MSG_KUMA_FARMFIELD_NUT_T [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]You haven't worked on the garden much.[n]Is it okay?[n][f 1 1][e]

[msg MSG_KUMA_FARMFIELD_SEASO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Sensei, how did the vegetables turn out?[n][f 1 1][e]

[msg MSG_KUMA_DUNGEON_0010 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1][f 3 1 3 0 6 896]I'm back! Plus, welcome home![n][f 1 1][e]

[msg REIZOU_32]
[f 0 5 65278][f 2 1]> You opened the fridge.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...?[n][f 1 1][e]
[f 0 5 65278][f 2 1]> There's a magazine in the vegetable[n]bin...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You flip through it and see that[n]it's an official fan club magazine for[n]a popular female idol...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> This is Kuma's doing...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You left it alone.[n][f 1 1][e]

[msg REIZOU_33]
[f 0 5 65278][f 2 1]> You opened the fridge.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]> There's animal hair in the egg case![n][f 1 1][e]
[f 0 5 65278][f 2 1]> The color and feeling is somehow[n]familiar... It's... Kuma's hair?[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ......[n][f 1 1][e]
[f 0 5 65278][f 2 1]> ...You left it alone.[n][f 1 1][e]

[msg DUN_SASOI_RISE_KIKANGAI [Rise]]
[f 0 5 65278][f 2 1][f 4 6 5 2 65535 1]Hell-o! This is Rise![n][f 1 1][e]
[f 0 5 65278][f 2 1]Hey, why don't we go to Kuma's place[n]tomorrow?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I know the criminal was arrested, but[n]we can still go in there, you know.[n]Plus, I don't feel relieved yet...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Aaaaand... I wanna see you fight, Senpai![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 1 5] [n][f 4 7 0 0 0]> Rise hung up.[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You thought about exploring the[n]TV world tomorrow.[n][f 1 1][e]

[msg IMA_TV_KOTOWARI_KUMA]
[f 0 5 65278][f 2 1]> You asked Kuma for permission and[n]changed the channel to the forecast...[n][f 1 1][e]

[msg TEST_FARM_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Oh, you're going to work in the garden?[n]I'll help![n][f 1 1][e]

[msg TEST_FARM_KUMA_TALK [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Conversation with Kuma[n][f 1 1][e]

[msg TEST_FARM_KUMA_UP]
[f 0 5 65278][f 2 1]> You feel that you and Kuma have[n]grown closer through your work together[n]in the garden...[n][f 1 1][e]

[msg MSG_FARMWORK_REST_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]But we just got all the veggies.[n]Let's wait 'til tomorrow to plant more.[n][f 1 1][e]

[msg MSG_FARMWORK_WORKED_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]But we already worked on the garden.[n]We can do that tomorrow.[n][f 1 1][e]

[msg MSG_FARMWORK_CHANGE_SEED_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Kuma'll help too![n][f 1 1][e]

[msg MSG_FARMWORK_NONE_SEEDSE_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]I'll plant some, too.[n][f 1 1][e]

[msg MSG_FARMWORK_LOOK_SEED_S_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]I'm going too, Sensei. Let's see them[n]vegetables.[n][f 1 1][e]

[msg MSG_FARMWORK_LOOK_SEEDLI_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]I'll go see the veggies with you too.[n][f 1 1][e]

[msg MSG_FARMWORK_LOOK_NUT_ST_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Sensei, you going to collect the[n]vegetables? I'll help![n][f 1 1][e]

[msg MSG_FARMWORK_LOOK_SEASON_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Sensei, you going to collect the[n]vegetables? I'll help![n][f 1 1][e]

[msg MSG_FARMFIELD_MUSITORI_K [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1]Oh, you came down.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I came here to keep you company![n]Don't you think you're being a little[n]inhospitable?[n][f 1 1][e]

[msg MSG_FARMFIELD_MUSITORI_K_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]Oh, that's right![n][f 1 1][e]
[f 0 5 65278][f 2 1]I heard from Nana-chan a while back[n]that you're raising vegetables![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1]That's not fair! I wanna grow veggies too![n][f 1 1][e]

[msg MSG_FARMFIELD_MUSITORI_K_3]
[f 0 5 65278][f 2 1]> Kuma went outside...[n][f 1 1][e]

[msg MSG_FARMFIELD_MUSITORI_K_4]
[f 0 5 65278][f 2 1]> You can hear Kuma's voice...[n][f 1 1][e]

[msg MSG_FARMFIELD_MUSITORI_K_5 [Kuma]]
[f 0 5 65278][f 2 1]Wooooo![n][f 1 1][e]
[f 0 5 65278][f 2 1]It's cold![n][f 1 1][e]
[f 0 5 65278][f 2 1]What's this!?[n][f 1 1][e]

[msg MSG_FARMFIELD_MUSITORI_K_6 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]Sensei, look at this![n][f 1 1][e]
[f 0 5 65278][f 2 1]Come on! Dig with me![n][f 1 1][e]

[msg MSG_FARMFIELD_MUSITORI_K_7 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]Oh, hold on! It's cold, so I'll go[n]change![n][f 1 1][e]
[f 0 5 65278][f 2 1]You just got better, so you'd better[n]dress warm![n][f 1 1][e]

[msg MSG_FARMFIELD_GET_MUSI_E [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]That was fun![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1]My hands are freezing, and we weren't[n]able to raise any vegetables...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]But it was fun! Let's do it again[n]sometime![n][f 1 1][e]

[msg MSG_FARMFIELD_MUSI_KUMA_]
[f 0 5 65278][f 2 1]> Will you take Kuma to the garden...?[n][f 1 1][e]

[msg MSG_FARMFIELD_MUSITORI_K_8 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]All right, Sensei! I knew you'd say that![n][f 1 1][e]

[msg MSG_FARMFIELD_MUSITORI_K_9 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Hold on there, Sensei! It's dangerous[n]to go alone! Take me![n][f 1 1][e]

[msg MSG_MOVIE_MAIL_KUMA [Kuma's message]]
[f 0 5 65278][f 2 1]Sensei![n]Moviesmoviesmoievsmoovesmoovs[n][f 1 1][e]
[f 0 5 65278][f 2 1]Thereee's a nEw 1 outtt i Want 2 seeeee![n]It's cAlled Orso Rosso![n][f 1 1][e]
[f 0 5 65278][f 2 1]I haerd the name n waz all[n]"O YEH! I GOTZ 2 SEE THIS"[n][f 1 1][e]
[f 0 5 65278][f 2 1]If you Ever wanT to see it,[n]tell ME n I'Ll go w/ you![n][f 1 1][e]