[sel SEL_EIGA_AITE_1 top]
[f 0 5 65278][f 2 1]Rise[e]
[f 0 5 65278][f 2 1]Kuma[e]
[f 0 5 65278][f 2 1]Naoto[e]
[f 0 5 65278][f 2 1]Someone else[e]
[f 0 5 65278][f 2 1]Cancel[e]

[msg MSG_GOJITUDAN_GUIDE_YOUS]
[f 0 5 65278][f 2 1]> Come to think of it, you have yet[n]to say goodbye to Yosuke and Kuma...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You should visit the [f 0 1 2]Junes[n]food court[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_10]
[f 0 5 65278][f 2 1]> Come to think of it, you have yet[n]to greet Kuma...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> If you visit [f 0 1 2]Junes[f 0 1 0],[n]will you be able to meet him...?[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_11]
[f 0 5 65278][f 2 1]> Come to think of it, you have yet[n]to greet Kuma...[n][f 1 1][e]