[msg RETURN_OK_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hmmm?[n][f 1 1][e]

[msg KUMA_BYE_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Okay...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'll see you later. Bye-bye![n][f 1 1][e]

[msg KUMA_BYE_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Good work, everyone![n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's go back![n][f 1 1][e]

[msg KUMA_BYE_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]...If you say so.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If you have time, come here again[n]tomorrow![n][f 1 1][e]

[msg KUMA_BYE_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]...Going back?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Okay, let's go together.[n][f 1 1][e]

[msg KUMA_HELP_DUNGEON_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Let's go save the lost girl![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'll take you to the castle![n][f 1 1][e]

[msg KUMA_HELP_DUNGEON_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Let me know when you're ready, Sensei.[n][f 1 1][e]

[msg KUMA_HIMA1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Welcome back![n][f 1 1][e]
[f 0 5 65278][f 2 1]I've been so very bored...[n][f 1 1][e]

[msg KUMA_HIMA2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh, it's Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]How can I help out?[n][f 1 1][e]

[msg KUMA_HIMA3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hey, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]It's been peaceful over here![n][f 1 1][e]

[msg KUMA_HIMA4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]There you are, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm so boooooored![n][f 1 1][e]

[msg KUMA_HIMA_MOROKIN_DEAD [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Why the long faces!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]What's the matter? Cheer up, guys![n][f 1 1][e]

[msg KUMA_HIMA5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I like it over there... But I kinda[n]like it here, too.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Ready to go exploring?[n][f 1 1][e]

[msg KUMA_HIMA6 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Do you need to do something over here?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Alright, alright. I'll go with you![n][f 1 1][e]

[msg KUMA_HIMA7 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]So you're exploring in here today, huh?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'll show you the power of Junes'[n]new idol![n][f 1 1][e]

[msg KUMA_HIMA8 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]W-Wait a second...[n]Let me put these back...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Alright! Let's do this![n][f 1 1][e]

[msg KUMA_HIMA13 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I'm still worried about[n]Nana-chan, but...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Ahem! We did what we needed to[n]do here![n][f 1 1][e]

[msg KUMA_HIMA14 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Whenever I come here, I think about[n]Nana-chan...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, are they still not letting[n]visitors in...?[n][f 1 1][e]

[msg KUMA_HIMA15 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh, it's you, Sensei... Going exploring?[n][f 1 1][e]

[msg KUMA_HIMA16 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Huh? What are we doing today?[n][f 1 1][e]

[msg KUMA_HELLO_01 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hey, there you are![n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's play! Huh? No time?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Oh, yeah, that's right![n][f 1 1][e]

[msg KUMA_HELLO_02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You're late![n][f 1 1][e]
[f 0 5 65278][f 2 1]I was gonna cry if you didn't show[n]up today...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Huh? No time to wipe my tears?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Oh, you're right![n][f 1 1][e]

[msg KUMA_YUKIKO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You guys are saving the girl who[n]got lost?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Good luck![n][f 1 1][e]

[msg KUMA_HELLO_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yay! Hi, everyone! I'm glad to see[n]you here![n][f 1 1][e]
[f 0 5 65278][f 2 1]You guys are searching today too?[n][f 1 1][e]

[msg KUMA_HELLO_04 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Helloooooo![n][f 1 1][e]
[f 0 5 65278][f 2 1]So what do you want to do today?[n]No time to play... right?[n][f 1 1][e]

[msg KUMA_KANJI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Let's psych ourselves up and save him![n][f 1 1][e]

[msg KUMA_HELLO_05 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hi there![n][f 1 1][e]
[f 0 5 65278][f 2 1]Exploring today too? Then I'll be giving[n]you my best support![n][f 1 1][e]

[msg KUMA_HELLO_06 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Woohoo! Thanks beary much for coming![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I was so lonely...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Just kidding, guys! I'm still at that[n]mischievous age, heheh.[n][f 1 1][e]

[msg KUMA_RISE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Let's look for Rise-chan. Oho![n]You thought I forgot her name, huh?[n][f 1 1][e]

[msg KUMA_HELLO_07 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hmhmhm, I've been waiting for this[n]moment all through my training...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's catch the killer![n][f 1 1][e]

[msg KUMA_HELLO_08 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Alright, I'll do my best![n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's bring in that killer![n][f 1 1][e]

[msg KUMA_KUBO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Rise-chan will be supporting you.[n]We can go whenever you're ready![n][f 1 1][e]

[msg KUMA_HELLO_09 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You're going to save him, right?[n]I was getting prepared while I waited[n]for you.[n][f 1 1][e]

[msg KUMA_HELLO_10 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]You're all fired up... I won't[n]fall behind![n][f 1 1][e]

[msg KUMA_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Get set, Sensei![n][f 1 1][e]

[msg KUMA_HELLO_11 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Nana-chan...[n][f 1 1][e]

[msg KUMA_HELLO_12 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Hang in there, Nana-chan...[n][f 1 1][e]

[msg KUMA_NAMATAME [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]I'll save you, Nana-chan![n][f 1 1][e]

[msg KUMA_HELLO_13 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Alright! Let's go get Adachy-baby![n][f 1 1][e]

[msg KUMA_HELLO_14 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Let's catch Adachy-baby as soon as[n]we can![n][f 1 1][e]

[msg KUMA_ADACHI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Ready, Sensei? I'll be giving you[n]the directions today![n][f 1 1][e]

[msg KUMA_MARY_A [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Huh? Why are we here? What about Emmy-chan?[n][f 1 1][e]

[msg KUMA_MARY_B [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...So, Sensei, what are we doing today?[n][f 1 1][e]

[msg KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]So this will be the last time I help you[n]catch the bad guy...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Good luck![n][f 1 1][e]

[msg KUMA_LOST_KANJI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sensei, you're here! Any clues?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]...I guess not.[n][f 1 1][e]

[msg KUMA_LOST_KANJI_OK [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sensei, you're here! Any clues?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh, you found some![n][f 1 1][e]

[msg KUMA_LOST_RISE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Rrrrr... I can't pinpoint her...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Did you find any clues?[n][f 1 1][e]

[msg KUMA_LOST_RISE_OK [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hey, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]You look like you found some clues![n][f 1 1][e]

[msg GK_CASTLE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...I forgot to tell you![n][f 1 1][e]
[f 0 5 65278][f 2 1]For some reason, I feel a powerful[n]Shadow in the castle.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Maybe this world is getting unstable[n]from people going in and out...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I don't think this Shadow is related[n]to the culprit. But I don't like it[n]being here.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'd be happy if you could defeat it[n]for me.[n][f 1 1][e]

[msg GK_SAUNA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh, by the way...![n][f 1 1][e]
[f 0 5 65278][f 2 1]I sense a powerful Shadow at the[n]steamy area where you found Kanji.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I think this world is getting more and[n]more unstable...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I just want to live here in peace...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, could you defeat the Shadow[n]at the steamy place?[n][f 1 1][e]

[msg DEBUG_CHK_NPC]
[f 0 5 65278][f 2 1]High: [f 2 4 0][n]Low: [f 2 4 1][n]Number of NPC that can be placed: [f 2 4 2][n][f 1 1][e]
[f 0 5 65278][f 2 1]Yosuke: [f 2 4 3] / Chie: [f 2 4 4] / Yukiko: [f 2 4 5][n]Kanji: [f 2 4 6] / Naoto: [f 2 4 7] / Kuma: [f 2 4 8][n]Fox: [f 2 4 9]  (Where each of them will be placed)[n][f 1 1][e]