[msg RETURN_ADVICE [Kuma]]
[f 0 5 65278][f 2 1]Sensei, are you okay? You're not tired?[n][f 1 1][e]
[f 0 5 65278][f 2 1]You can use those things I gave you at[n]the entrance to come back. It's tiring[n]walking back![n][f 1 1][e]

[msg HELP_ORDER_1 [Kuma]]
[f 0 5 65278][f 2 1]Hmm...[n][f 1 1][e]
[f 0 5 65278][f 2 1]You're good at fighting, Sensei.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Compared to you, Yosuke stinks...[n][f 1 1][e]

[msg HELP_ORDER_2 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 12 65535 1]Shut up, Kuma![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 10 65535 1]Though I do gotta admit... You have[n]a knack for this stuff.[n][f 1 1][e]

[msg HELP_ORDER_3 [Kuma]]
[f 0 5 65278][f 2 1]Doesn't he?[n][f 1 1][e]
[f 0 5 65278][f 2 1]So you should be the one to give Yosuke[n]orders during a fight.[n][f 1 1][e]

[msg HELP_ORDER_5 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 10 65535 1]It ticks me off to hear Kuma say that[n]stuff, but I don't wanna cause trouble[n]doing my own thing in battle...[n][f 1 1][e]
[f 0 5 65278][f 2 1]So don't hesitate to order me around.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 11 65535 1]I'm counting on you.[n][f 1 1][e]

[msg HELP_ORGANIZE_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Our team is filling out now that[n]Yuki-chan and Kanji are on board![n][f 1 1][e]

[msg CHASE_CHIE_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Urk...![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1]There are lots of Shadows in the castle.[n][f 1 1][e]
[f 0 5 65278][f 2 1]It'll be dangerous inside for a girl[n]by herself...[n][f 1 1][e]

[msg CHECK_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Are you sure you wanna go alone?[n][f 1 1][e]

[msg GO_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Let's go![n][f 1 1][e]

[msg GO_KUMA_YUKIKO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Be careful![n][f 1 1][e]

[msg RETURN_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Welcome back![n][f 1 1][e]

[msg RETURN_KUMA_CHIE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hmmm? Where's Chie-chan?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I haven't seen her come out.[n][f 1 1][e]

[msg RETURN_KUMA_YUKIKO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Welcome back, Sensei![n][f 1 1][e]

[msg RETURN_SUGGEST [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 10 65535 1]Hey, [f 4 2]. No straining overselves, okay?[n][f 1 1][e]
[f 0 5 65278][f 2 1]It isn't raining today, and we have Kuma's[n]reassurance, so...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 13 65535 1]As long as there's fog "here" then[n]there shouldn't be any "over there."[n][f 1 1][e]
[f 0 5 65278][f 2 1]We're the only ones who can save Yukiko. There's[n]no reason for us to rush things.[n][f 1 1][e]
[f 0 5 65278][f 2 1]If we don't have the power to save her,[n]then we just need to train.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 10 65535 1]We still have time. Let's take this one step[n]at a time.[n][f 1 1][e]

[msg KUMA_ITEM [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh, hey![n][f 1 1][e]
[f 0 5 65278][f 2 1]Take this, okay?[n][f 1 1][e]

[msg KUMA_ITEM_ADD [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]This too.[n][f 1 1][e]
[f 0 5 65278][f 2 1]These are for you. I collected[n]them myself![n][f 1 1][e]

[msg KUMA_ITEM_RETURN [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If you don't want to waste time[n]walking back to the entrance,[n]use this to teleport back here.[n][f 1 1][e]

[msg DRESSROOM_DOOR_CHIE [Kuma]]
[f 0 5 65278][f 2 1]There she is![n][f 1 1][e]
[f 0 5 65278][f 2 1]Chie-chan is in there![n][f 1 1][e]

[msg DRESSROOM_DOOR_YUKIKO [Kuma]]
[f 0 5 65278][f 2 1]Hmm?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I sense someone behind this door...[n][f 1 1][e]

[msg BOSSROOM_DOOR [Kuma]]
[f 0 5 65278][f 2 1]Huh? This smell is...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It must be her![n][f 1 1][e]
[f 0 5 65278][f 2 1]She's right behind this door![n][f 1 1][e]

[msg BOSSROOM_DOOR_NOT_OPEN_1 [Kuma]]
[f 0 5 65278][f 2 1]Huhhh? It won't open...[n][f 1 1][e]

[msg GK_DOOR_KUMA [Kuma]]
[f 0 5 65278][f 2 1]I sense a Shadow inside![n]Are you ready, Sensei?[n][f 1 1][e]

[msg GK_BATTLE_KUMA [Kuma]]
[f 0 5 65278][f 2 1]Let's do it, Sensei![n][f 1 1][e]

[msg GK_WIN_KUMA [Kuma]]
[f 0 5 65278][f 2 1]Alright![n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, thank you![n][f 1 1][e]

[msg DEBUG_CHK_NPC]
[f 0 5 65278][f 2 1]High: [f 2 4 0][n]Low: [f 2 4 1][n]Placeable number of NPC: [f 2 4 2][n][f 1 1][e]
[f 0 5 65278][f 2 1]Yosuke: [f 2 4 3]/Chie: [f 2 4 4]/Yukiko: [f 2 4 5][n]Kanji: [f 2 4 6]/Naoto: [f 2 4 7]/Kuma: [f 2 4 8]/Fox: [f 2 4 9][n](Disposition of each character)[n][f 1 1][e]

