[msg HELP_ORGANIZE_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Our team is filling out now that[n]Yuki-chan and Kanji are on board![n][f 1 1][e]

[msg CHECK_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Are you sure you wanna go alone?[n][f 1 1][e]

[msg GO_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Be careful![n][f 1 1][e]

[msg RETURN_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Are you okay, Sensei? Don't push[n]yourself too hard.[n][f 1 1][e]

[msg BOSSROOM_DOOR [Kuma]]
[f 0 5 65278][f 2 1]Hm? I can sense Kanji![n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]He must be behind this door![n][f 1 1][e]

[msg BOSSROOM_DOOR_NOT_OPEN_1 [Kuma]]
[f 0 5 65278][f 2 1]Hrmmmm... It's closed.[n][f 1 1][e]

[msg GK_DOOR_KUMA [Kuma]]
[f 0 5 65278][f 2 1]I sense a Shadow inside![n]Are you ready, Sensei?[n][f 1 1][e]

[msg GK_BATTLE_KUMA [Kuma]]
[f 0 5 65278][f 2 1]Let's do it, Sensei![n][f 1 1][e]

[msg DEBUG_CHK_NPC]
[f 0 5 65278][f 2 1]High: [f 2 4 0][n]Low: [f 2 4 1][n]Placeable number of NPC: [f 2 4 2][n][f 1 1][e]
[f 0 5 65278][f 2 1]Yosuke: [f 2 4 3]/Chie: [f 2 4 4]/Yukiko: [f 2 4 5][n]Kanji: [f 2 4 6]/Naoto: [f 2 4 7]/Kuma: [f 2 4 8]/Fox: [f 2 4 9][n](Disposition of each character)[n][f 1 1][e]

