[msg HELP_ORGANIZE_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Our team is filling out now that[n]Yuki-chan and Kanji are on board![n][f 1 1][e]

[msg CHECK_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Are you sure you wanna go alone?[n][f 1 1][e]

[msg GO_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Good luck![n][f 1 1][e]

[msg RETURN_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Good work![n][f 1 1][e]

[msg BOSSROOM_DOOR [Kuma]]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]I think that girl named Rise is ahead[n]of here...[n][f 1 1][e]
[f 0 5 65278][f 2 1]But I'm not certain.[n][f 1 1][e]

[msg DEBUG_CHK_NPC]
[f 0 5 65278][f 2 1]High: [f 2 4 0][n]Low: [f 2 4 1][n]Placeable number of NPC: [f 2 4 2][n][f 1 1][e]
[f 0 5 65278][f 2 1]Yosuke: [f 2 4 3]/Chie: [f 2 4 4]/Yukiko: [f 2 4 5][n]Kanji: [f 2 4 6]/Naoto: [f 2 4 7]/Kuma: [f 2 4 8]/Fox: [f 2 4 9][n](Disposition of each character)[n][f 1 1][e]

