[msg HELLO_AGAIN [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 65535 1]Wait for me, Emmy-chan![n]I'll come save you![n][f 1 1][e]

[msg DEBUG_CHK_NPC]
[f 0 5 65278][f 2 1]High: [f 2 4 0][n]Low: [f 2 4 1][n]NPCs available to set: [f 2 4 2][n][f 1 1][e]
[f 0 5 65278][f 2 1]Yosuke: [f 2 4 3] / Chie: [f 2 4 4] / Yukiko [f 2 4 5][n]Kanji: [f 2 4 6] / Naoto: [f 2 4 7] / Kuma: [f 2 4 8][n]Fox: [f 2 4 9] (position class)[n][f 1 1][e]