[msg FOODCOURT_MES_10_02 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 4 65535 1][f 4 9 2 14 5 13 5][f 4 9 15 14 5 13 5]Rise-chan's Persona seemed special...[n]And Kuma's too...[n][f 1 1][e]

[msg FOODCOURT_MES_13_05 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Me too, me too![n][f 1 1][e]

[msg FOODCOURT_MES_13_05a [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 4 9 7 3 5 0 5][f 4 9 19 1 5 0 5]Me too, me too![n][f 1 1][e]

[msg FOODCOURT_MES_DONTENTER_ [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 1 65535 1][f 4 9 1 1 5 0 5][f 4 9 14 1 5 0 5]Kuma's training as hard as he can[n]over there.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's leave him be for a while.[n][f 1 1][e]

[msg FOODCOURT_MES_DONTENTER__2 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 4 65535 1][f 4 9 3 14 5 13 5][f 4 9 16 14 5 13 5]We haven't been able to gather enough[n]information on Kanji-kun yet...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Even if we go see Kuma now, I don't[n]think he'll be able to figure out[n]where Kanji-kun is.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 3 65535 1]So we should hurry and gather more[n]information ourselves, and then go[n]see him once we have it![n][f 1 1][e]

[msg FOODCOURT_MES_DONTENTER__3 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 9 65535 1][f 4 9 1 1 5 0 5][f 4 9 14 1 5 0 5]We haven't picked up enough info[n]on Rise yet...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 3 65535 1]Kuma won't know where to start at[n]this rate, so let's pick up the search[n]and get more info![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 586]Sensei, what'll we do today?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 585]Sensei, what'll we do today?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 588]I was called out here. What's going on?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 587]I was called out here. What's going on?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 863]Hello, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]What'll we do today?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_6 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 862]Hello, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]What'll we do today?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_7 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1][f 3 1 3 0 6 682]It's so hot...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's even hotter with this on...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_8 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1][f 3 1 3 0 6 681]It's so hot...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_9 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1][f 3 1 3 0 6 684]It's kinda chilly today...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_10 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1][f 3 1 3 0 6 683]It's collllld...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_11 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 877]Happy New Year![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_12 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1][f 3 1 3 0 6 876]Happy New Year![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_13 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1][f 3 1 3 0 6 879]It's raining...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_14 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1][f 3 1 3 0 6 878]It's raining...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_9 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 590]We're all here![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_10 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 589]That makes all of us![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_11 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 592]Sensei! I'm all ready to go![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_12 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 591]Sensei! I'm all ready to go![n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__21 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1][f 3 1 3 0 6 594]Hm? I'm going in too?[n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__22 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1][f 3 1 3 0 6 593]Hm? I'm going in too?[n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__23 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1][f 3 1 3 0 6 596]Wait for me, Sensei![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__24 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1][f 3 1 3 0 6 595]Wait for me, Sensei![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__25 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 964]Woohoo![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm going too![n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__26 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 963]Woohoo![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm going too![n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__27 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1][f 3 1 3 0 6 594]Huh? I'm going too?[n][f 1 1][e]
[f 0 5 65278][f 2 1]W-Wait... Don't leave meeeee.[n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__28 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1][f 3 1 3 0 6 593]Huh? I'm going too?[n][f 1 1][e]
[f 0 5 65278][f 2 1]W-Wait... Don't leave meeeee.[n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__39 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 598]I'll do my furry best![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__40 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 597]I'll do my furry best![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__41 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 600]Let's go, Sensei![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__42 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 599]Let's go, Sensei![n][f 1 3 65535][f 1 1][e]