[sel FOODCOURT_MES_01_SEL top]
[f 0 5 65278][f 2 1]Adachi and Namatame[e]
[f 0 5 65278][f 2 1]Kuma and Shadows[e]
[f 0 5 65278][f 2 1]Nothing[e]

[msg FOODCOURT_MES_01_02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]My head's all steamy, like a boiling pot![n]I'm never, ever, ever ever ever gonna[n]forgive him![n][f 1 1][e]
[f 0 5 65278][f 2 1]How did a jerk like Adachi, who only[n]thinks about himself, get the power to[n]enter TVs...?[n][f 1 1][e]
[f 0 5 65278][f 2 1]And Namatame, too... How did someone[n]who didn't understand anything get a power[n]like that?[n][f 1 1][e]
[f 0 5 65278][f 2 1]What's wrong with this world!?[n]Or the other one!?[n][f 1 1][e]

[msg FOODCOURT_MES_01_02a [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 4 9 7 3 5 0 5][f 4 9 19 1 5 0 5]My head's all steamy, like a boiling pot![n]I'm never, ever, ever ever ever gonna[n]forgive him![n][f 1 1][e]
[f 0 5 65278][f 2 1]How did a jerk like Adachi, who only[n]thinks about himself, get the power to[n]enter TVs...?[n][f 1 1][e]
[f 0 5 65278][f 2 1]And Namatame, too... How did someone[n]who didn't understand anything get a power[n]like that?[n][f 1 1][e]
[f 0 5 65278][f 2 1]What's wrong with this world!?[n]Or the other one!?[n][f 1 1][e]

[msg FOODCOURT_MES_02_01 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Let's hurry and beat up Adachy-baby,[n]and end this rotten case![n][f 1 1][e]

[msg FOODCOURT_MES_02_01a [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 4 9 7 3 5 0 5][f 4 9 19 1 5 0 5]Let's hurry and beat up Adachy-baby,[n]and end this rotten case![n][f 1 1][e]

[msg FOODCOURT_MES_02_03 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 1 65535 1][f 4 9 8 14 5 13 5][f 4 9 16 14 5 13 5]You know... It's pretty mysterious.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Kuma was originally a Shadow, right?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Out of all the Shadows over there, why did[n]Kuma like peace and want to be friends[n]with us?[n][f 1 1][e]

[msg FOODCOURT_MES_02_04 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]At first, I only wanted the world I lived in[n]to go back to normal.[n][f 1 1][e]
[f 0 5 65278][f 2 1]But after getting to know you guys, and[n]helping with the rescue missions...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]Before I knew it, I was a friendly,[n]lovable bear.[n][f 1 1][e]

[msg FOODCOURT_MES_02_04a [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1][f 4 9 7 3 5 0 5][f 4 9 19 1 5 0 5]At first, I only wanted the world I lived in[n]to go back to normal.[n][f 1 1][e]
[f 0 5 65278][f 2 1]But after getting to know you guys, and[n]helping with the rescue missions...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]Before I knew it, I was a friendly,[n]lovable bear.[n][f 1 1][e]

[msg FOODCOURT_MES_02_08 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]I bet there's another one with the same[n]destiny as me, somewhere in this great[n]big world![n][f 1 1][e]
[f 0 5 65278][f 2 1]I know it.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]He'd have dashing looks like me, hiding[n]beneath them a dangerous ladykiller[n]who scores with all the girls![n][f 1 1][e]

[msg FOODCOURT_MES_02_08a [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1][f 4 9 7 3 5 0 5][f 4 9 19 1 5 0 5]I bet there's another one with the same[n]destiny as me, somewhere in this great[n]big world![n][f 1 1][e]
[f 0 5 65278][f 2 1]I know it.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1]He'd have dashing looks like me, hiding[n]beneath them a dangerous ladykiller[n]who scores with all the girls![n][f 1 1][e]

[msg FOODCOURT_MES_02_10 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 5 1 65535 1][f 4 9 10 14 5 13 5][f 4 9 18 14 5 13 5]Kuma's a Shadow who blended in with us.[n]Adachi, on the other hand, is a human[n]who likes watching people suffer...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 5 2 65535 1]I guess it all depends on how you choose[n]to live.[n][f 1 1][e]

[msg FOODCOURT_MES_04_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1][f 4 9 19 1 5 0 5]ペルソナむっつり出た時も、センセイは[n]“もう一人"が暴走したりしなかったクマ。[n][f 1 1][e]

[msg FOODCOURT_MES_05_07 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 10 0 1][f 4 9 19 1 5 0 5]クマも、ナナチャンの時は、[n]体ちっちゃいお相手だって、言ったクマよ。[n][f 1 1][e]

[msg FOODCOURT_MES_B_01_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Ooh, I'm getting a sack? Is it full[n]of money? Or candy!?[n][f 1 1][e]

[msg FOODCOURT_MES_B_02_07 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Huh!? We're gonna stay at a shrine[n]for two years!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]But by the time we come out, Chie-chan[n]and Yuki-chan will be old ladies![n][f 1 1][e]

[msg FOODCOURT_MES_B_02_09 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 1 65535 1][f 4 9 8 14 5 13 5][f 4 9 16 14 5 13 5]...Wait. Kuma, do you think we'll be[n]old ladies in two years?[n][f 1 1][e]

[msg FOODCOURT_MES_B_02_10 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Y-Yuki-chan... Your pretty mouth[n]is smiling, but your pretty eyes[n]say otherwise...[n][f 1 1][e]

[msg FOODCOURT_MES_B_03_07 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]The scene: A moonlit shrine, in the[n]bustling city... A young man and woman[n]meet behind the temple...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Their wish: a future, together...![n][f 1 1][e]

[msg FOODCOURT_MES_B_04_07 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]I was busy, too![n][f 1 1][e]
[f 0 5 65278][f 2 1]I ate rice cakes, took naps, played games,[n]ate more rice cakes...[n][f 1 1][e]

[msg FOODCOURT_MES_B_04_08 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 1 65535 1][f 4 9 8 14 5 13 5][f 4 9 16 14 5 13 5]It sounds like you really enjoyed your[n]New Year's, then, Kuma.[n][f 1 1][e]

[msg FOODCOURT_MES_B_04_09 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Oh, yeah! New Year's was fun![n][f 1 1][e]

[msg FOODCOURT_MES_B_05_06 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]I'm glad this world's peaceful now.[n]My world's still the same, though...[n][f 1 1][e]

[msg FOODCOURT_MES_B_05_07 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 1 65535 1][f 4 9 8 14 5 13 5][f 4 9 16 14 5 13 5]Don't worry, Kuma. If everyone's heart[n]keeps slowly changing like they have[n]been...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm sure your world will become peaceful[n]one day, too.[n][f 1 1][e]

[msg FOODCOURT_MES_B_05_08 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Yuki-chan... You're right...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Alrighty then! I'll do my best with Sensei[n]and everyone else until that day comes![n][f 1 1][e]

[msg FOODCOURT_MES_B_06_07 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Okay! But if nothing happens and you[n]still want to call me, that's cool, too![n][f 1 1][e]

[msg FOODCOURT_MES_06_00 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Snow, snow, snow![n]I want even more of it![n][f 1 1][e]

[msg FOODCOURT_MES_06_04 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 2 65535 1][f 4 9 3 14 5 13 5][f 4 9 16 14 5 13 5]But I'm glad Kuma was with you...[n]He took care of you the whole time, right?[n][f 1 1][e]

[msg FOODCOURT_MES_06_05 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Oh, yeah! I mean, Sensei's face was all[n]blue at one point...![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]I will keep Sensei safe until Nana-chan[n]and Pops come back! His life is in my hands![n][f 1 1][e]

[msg FOODCOURT_MES_07_06 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Oh ho hooooooh... Could it be that you're[n]all pining for some excitement? Maybe[n]I could set up a surprise...[n][f 1 1][e]

[msg FOODCOURT_MES_08_01 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Yaaaaay! Let's throw her a party to[n]celebrate her return![n][f 1 1][e]

[msg FOODCOURT_MES_09_04 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Nana-chan's a genius at finding people![n]She found me quickly, too![n][f 1 1][e]

[msg FOODCOURT_MES_09_07 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]She was in a refrigerator![n]Completely untraceable![n][f 1 1][e]

[msg FOODCOURT_MES_10_10 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 4 9 7 1 5 0 5][f 4 9 19 1 5 0 5]Hee! Looks like we might have to[n]worry about Yosuke the most![n]You'd better not drag everyone down.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]This'll be our last surprise chance to do[n]something awesome this winter! I'm gonna[n]make tons of memories with Sensei![n][f 1 1][e]

[msg FOODCOURT_MES_DONTENTER_ [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 4 65535 1][f 4 9 3 14 5 13 5][f 4 9 16 14 5 13 5]We haven't been able to gather enough[n]information on Kanji-kun yet...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Even if we go see Kuma now, I don't[n]think he'll be able to figure out[n]where Kanji-kun is.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 3 65535 1]So we should hurry and gather more[n]information ourselves, and then go[n]see him once we have it![n][f 1 1][e]

[msg FOODCOURT_MES_DONTENTER__2 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 9 65535 1][f 4 9 1 1 5 0 5][f 4 9 14 1 5 0 5]We haven't picked up enough info[n]on Rise yet...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 3 65535 1]Kuma won't know where to start at[n]this rate, so let's pick up the search[n]and get more info![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 586]Sensei, what'll we do today?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 585]Sensei, what'll we do today?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 588]I was called out here. What's going on?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 587]I was called out here. What's going on?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 863]Hello, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]What'll we do today?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_6 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 11 0 1][f 3 1 3 0 6 862]Hello, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]What'll we do today?[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_7 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1][f 3 1 3 0 6 682]It's so hot...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's even hotter with this on...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_8 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1][f 3 1 3 0 6 681]It's so hot...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_9 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1][f 3 1 3 0 6 684]It's kinda chilly today...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_10 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1][f 3 1 3 0 6 683]It's collllld...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_11 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 877]Happy New Year![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_12 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1][f 3 1 3 0 6 876]Happy New Year![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_13 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1][f 3 1 3 0 6 879]It's raining...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_KUMA_14 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 13 0 1][f 3 1 3 0 6 878]It's raining...[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_9 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 590]We're all here![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_10 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 589]We're all here![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_11 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 592]Sensei! I'm all ready to go![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_12 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 591]Sensei! I'm all ready to go![n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__21 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1][f 3 1 3 0 6 594]Hm? I'm going in, too?[n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__22 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1][f 3 1 3 0 6 593]Hm? I'm going in, too?[n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__23 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1][f 3 1 3 0 6 596]Wait for me, Sensei![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__24 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1][f 3 1 3 0 6 595]Wait for me, Sensei![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__25 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 964]Woohoo![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm going too![n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__26 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 963]Woohoo![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm going too![n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__27 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1][f 3 1 3 0 6 594]Huh? I'm going too?[n][f 1 1][e]
[f 0 5 65278][f 2 1]W-Wait... Don't leave meeeee.[n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__28 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1][f 3 1 3 0 6 593]Huh? I'm going too?[n][f 1 1][e]
[f 0 5 65278][f 2 1]W-Wait... Don't leave meeeee.[n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__43 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 598]I'll do my furry best![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__44 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 597]I'll do my furry best![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__45 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 600]Let's go, Sensei![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__46 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 599]Let's go, Sensei![n][f 1 3 65535][f 1 1][e]