[msg FOODCOURT_MES_C_01_07 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]That place will be cut off soon... We gotta[n]hurry and rescue Marie-chan![n][f 1 1][e]

[msg FOODCOURT_MES_C_02_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]That foxy lady Sensei knows said so![n][f 1 1][e]

[msg FOODCOURT_MES_C_02_05 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 1 65535 1][f 4 9 3 23 5 22 5]Well, we confirmed that since we had[n]Rise-chan and Kuma look into it.[n][f 1 1][e]

[msg FOODCOURT_MES_C_03_02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]よよよ…1人は寂しいクマ。[n]クマだったら寂死しちゃう。[n][f 1 1][e]

[msg FOODCOURT_MES_C_04_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]あっち側に作られる場所には、[n]中に入った人の心が影響するクマ。[n][f 1 1][e]
[f 0 5 65278][f 2 1]だから、あの場所はマリチャンの[n]思い出した記憶と関係があるはずクマよ。[n][f 1 1][e]

[msg FOODCOURT_MES_C_05_09 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]その通りクマ![n]ここまで来たら、突撃あるのみクマよ![n][f 1 1][e]
[f 0 5 65278][f 2 1]皆の衆、センセイに続け～![n]全力でマリチャンを救出するクマ![n][f 1 1][e]

[msg FOODCOURT_MES_IN_00 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We're here![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_9 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 590]We're all here now.[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_10 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 589]We're all here now.[n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_11 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 592]Sensei! I'm all ready to go![n][f 1 1][e]

[msg FOODCOURT_MES_HELLO_CAPT_12 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 591]Sensei! I'm all ready to go![n][f 1 1][e]

[msg FOODCOURT_MES_WEATHER_A__3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]Feel free to ask me anytime, Sensei![n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__21 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1][f 3 1 3 0 6 594]Hm? I'm going in, too?[n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__22 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1][f 3 1 3 0 6 593]Hm? I'm going in, too?[n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__23 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1][f 3 1 3 0 6 596]Wait for me, Sensei![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__24 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1][f 3 1 3 0 6 595]Wait for me, Sensei![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__25 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1][f 3 1 3 0 6 964]Woohoo![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm going in too![n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__26 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 963]Woohoo![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm going in too![n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__27 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1][f 3 1 3 0 6 594]Hm? I'm going in, too?[n][f 1 1][e]
[f 0 5 65278][f 2 1]W-Wait... Don't leave me behiiiiind.[n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__28 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1][f 3 1 3 0 6 593]Hm? I'm going in, too?[n][f 1 1][e]
[f 0 5 65278][f 2 1]W-Wait... Don't leave me behiiiiind.[n][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__43 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 598]I'll do my furry best![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__44 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 597]I'll do my furry best![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__45 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 600]Let's go, Sensei![n][f 1 3 65535][f 1 1][e]

[msg FOODCOURT_MES_GODUNGEON__46 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 12 0 1][f 3 1 3 0 6 599]Let's go, Sensei![n][f 1 3 65535][f 1 1][e]