[msg KUMA_BYE_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I see...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sayonara! Bye-bye! Come again soon![n][f 1 1][e]

[msg KUMA_BYE_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]As usual, everyone did great today![n]Well done![n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's all go home![n][f 1 1][e]

[msg KUMA_BYE_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]...Oh well.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Let's try even harder tomorrow![n][f 1 1][e]

[msg KUMA_BYE_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]...Are we going back?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Okay... then I'll go back too.[n][f 1 1][e]

[msg KUMA_BYE_TOMB [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Let's go back.[n][f 1 1][e]

[msg KUMA_ITEM [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh, that's right![n][f 1 1][e]
[f 0 5 65278][f 2 1]Take this with you.[n][f 1 1][e]

[msg KUMA_ITEM_ADD [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Take this too.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I gathered these all by myself.[n]You can have them, Sensei![n][f 1 1][e]

[msg KUMA_ITEM_RETURN [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]If it becomes too tough to walk back,[n]use that to come back here.[n][f 1 1][e]

[msg DNG_ORDER_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 0 4 255]What's up?[n][e]

[sel DUNGEON_SEL top]
[f 0 5 65278][f 2 1]Talk to the others[e]
[f 0 5 65278][f 2 1]Talk to Kuma[e]
[f 0 5 65278][f 2 1]Talk to Rise[e]
[f 0 5 65278][f 2 1]Change battle tactics[e]
[f 0 5 65278][f 2 1]Move on to next floor[e]
[f 0 5 65278][f 2 1]Return to previous floor[e]
[f 0 5 65278][f 2 1]Return to entrance[e]
[f 0 5 65278][f 2 1]Nothing[e]
[f 0 5 65278][f 2 1]Debug mode[e]

[msg PARTY_RE_ORDER_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 0 4 255]Are you done yet?[n][e]

[sel PARTY_SEL top]
[f 0 5 65278][f 2 1]Yosuke ([f 2 4 0])[e]
[f 0 5 65278][f 2 1]Chie ([f 2 4 1])[e]
[f 0 5 65278][f 2 1]Yukiko ([f 2 4 2])[e]
[f 0 5 65278][f 2 1]Kanji ([f 2 4 3])[e]
[f 0 5 65278][f 2 1]Naoto ([f 2 4 4])[e]
[f 0 5 65278][f 2 1]Kuma ([f 2 4 5])[e]
[f 0 5 65278][f 2 1]Never mind[e]

[sel TALK_SEL top]
[f 0 5 65278][f 2 1]Yosuke[e]
[f 0 5 65278][f 2 1]Chie[e]
[f 0 5 65278][f 2 1]Yukiko[e]
[f 0 5 65278][f 2 1]Kanji[e]
[f 0 5 65278][f 2 1]Naoto[e]
[f 0 5 65278][f 2 1]Kuma[e]
[f 0 5 65278][f 2 1]Rise[e]
[f 0 5 65278][f 2 1]Never mind[e]

[msg ORDER_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Did you call me?[n]   (Current tactic: [f 0 1 1][f 2 4 5][f 0 1 0])[n][f 1 1][e]

[msg ORDER_OK_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Roger that![n][f 1 1][e]

[msg TALK_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]I'm gonna power up to reach new heights[n]in the Legend of Kuma![n][f 1 1][e]
[f 0 5 65278][f 2 1]First off, since we're dealing with[n]Shadows... I'm gonna Shadow box![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]...Teehee.[n][f 1 1][e]

[msg TALK_KUMA_MITSUO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]My Persona's all powered up! I can't[n]wait to catch this guy![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Once this is over, it'll finally get[n]peaceful here! I'm gonna do my best![n][f 1 1][e]

[msg TALK_KUMA_MITSUO_C [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Do we get a loooong vacation now?[n]If so, then...[n][f 1 1][e]
[f 0 5 65278][f 2 1]You have the perfect opportunity to[n]come and play with me![n][f 1 1][e]
[f 0 5 65278][f 2 1]C'mon, Sensei! You gotta use all your[n]strength so we can have fun together![n][f 1 1][e]

[msg TALK_KUMA_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Body alterations...[n][f 1 1][e]
[f 0 5 65278][f 2 1]...If I wasn't Kuma anymore, that[n]means this body wouldn't be Kuma's,[n]so I'd be...[n][f 1 1][e]
[f 0 5 65278][f 2 1].........[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Now I'm all confused.[n][f 1 1][e]

[msg TALK_KUMA_NAMATAME [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Sensei... She'll be okay, right?[n]Right?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Nana-chan... We're coming to rescue you[n]as fast as we can...![n][f 1 1][e]

[msg TALK_KUMA_NAMATAME_C [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1].........[n][f 1 1][e]
[f 0 5 65278][f 2 1]Hey, Sensei.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Nana-chan will get better, right?[n][f 1 1][e]

[msg TALK_KUMA_ADACHI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]That Adachy-baby![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm gonna get him good![n][f 1 1][e]

[msg TALK_KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]This really is the end![n][f 1 1][e]

[msg TALK_KUMA_MARY_OUT [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whaaa? What about Emmy-chan?[n][f 1 1][e]

[msg TALK_KUMA_MARY_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Let's go, Sensei! We'll save Emmy-chan![n][f 1 1][e]

[msg TALK_KUMA_MARY_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It'll all work out in the end.[n]Right, Sensei?[n][f 1 1][e]

[msg TALK_KUMA_MARY_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]If Emmy-chan doesn't die, the[n]world will disappear? Sensei,[n]what are we going to do...?[n][f 1 1][e]

[msg TALK_H_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1]It's not dangerous today and everyone's[n]here. So I'm kinda happy.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh, but don't push yourself too hard![n]Come back when you can't go on anymore![n][f 1 1][e]

[msg TALK_H_KUMA_CHIE [Kuma]]
[f 0 5 65278][f 2 1]I wonder how far in she went...[n]She doesn't have glasses on! It's too[n]dangerous for her in there![n][f 1 1][e]

[msg TALK_H_KUMA_YUKIKO [Kuma]]
[f 0 5 65278][f 2 1]I've been wondering all this time...[n][f 1 1][e]
[f 0 5 65278][f 2 1]What's "scoring a hot stud"...?[n][f 1 1][e]

[msg TALK_H_KUMA_KANJI_1 [Kuma]]
[f 0 5 65278][f 2 1]My fur's getting matted from all this[n]moisture...[n][f 1 1][e]

[msg TALK_H_KUMA_KANJI_2 [Kuma]]
[f 0 5 65278][f 2 1]Huh? You okay about Kanji?[n][f 1 1][e]

[msg TALK_H_KUMA_RISE [Kuma]]
[f 0 5 65278][f 2 1]Strip... like what zebras have...[n][f 1 1][e]

[msg TALK_H_RISE_ADACHI [Rise]]
[f 0 5 65278][f 2 1]Senpai... I'll find him no matter what![n][f 1 1][e]
[f 0 5 65278][f 2 1]We've got Kuma and the others with us![n]Let's all take him down together![n][f 1 1][e]

[msg KUMA_YA_1 [Kuma]]
[f 0 5 65278][f 2 1]Heehee, I'm all for more girls joining[n]the team![n][f 1 1][e]
[f 0 5 65278][f 2 1]Carry on, I say![n][f 1 1][e]

[msg KUMA_YA_4 [Kuma]]
[f 0 5 65278][f 2 1]Everyone seems different than usual.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Did I miss something?[n][f 1 1][e]

[msg KUMA_KA_1 [Kuma]]
[f 0 5 65278][f 2 1]Senpai!! Could you tell him to keep his[n]hands off me!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Every time I let my guard down...[n]I can sense someone behind me...![n][f 1 1][e]

[msg KUMA_KA_3 [Kuma]]
[f 0 5 65278][f 2 1]They're so cute! All the girls have[n]changed their outfits![n][f 1 1][e]
[f 0 5 65278][f 2 1]Huh?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I don't pay attention to the guys.[n][f 1 1][e]

[msg CHIE_RA_1 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 14 65535 1]An idol who can use a Persona...[n]Isn't that wild!?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 11 65535 1]Kuma can fight now too, so that might[n]make battles easier for us.[n][f 1 1][e]

[msg YUKIKO_RA_1 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 21 65535 1]Yep, our group's gotten bigger.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Now that Kuma's on the front lines,[n]I need to do my best too.[n][f 1 1][e]

[msg KUMA_RA_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Rise-chan's definitely talented![n]I can relax and leave the rest to her...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]I'm gonna go full throttle! I've got[n]your back, Senpai![n][f 1 1][e]

[msg KUMA_RA_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If the culprit's caught, will it become[n]peaceful here again? I hope he gets[n]arrested soon.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...But you guys look sad. Are you okay?[n][f 1 1][e]

[msg KUMA_RA_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Exams... That's the second time I've[n]heard that term.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Kuma the Outcast Returns...[n][f 1 1][e]

[msg KUMA_RA_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It seems like these exam thingies were[n]pretty tough.[n][f 1 1][e]
[f 0 5 65278][f 2 1]How did you do, Sensei?[n][f 1 1][e]

[msg YOSUKE_MA_1a [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 13 65535 1]*sigh*[n][f 1 1][e]
[f 0 5 65278][f 2 1]I know you sent through hell with[n]remedial lessons, but it was hell[n]at Junes, too...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 14 65535 1]Seriously, too many customers![n]Too few part-timers![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 13 65535 1]I've never been so thankful before to[n]have Kuma around...[n][f 1 1][e]

[msg KUMA_MA_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Kuma, the dependable super-employee[n]of Junes! One step at a time, I'm slowly[n]closing in on that title...[n][f 1 1][e]
[f 0 5 65278][f 2 1]You saw how hard I worked, right Sensei!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Bring Nana-chan next time and come see![n][f 1 1][e]

[msg KUMA_MA_1a [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Kuma, the dependable super-employee[n]of Junes! One step at a time, I'm slowly[n]closing in on that title...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Come see how hard I'm working, Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]Don't forget to bring Nana-chan along![n][f 1 1][e]

[msg KUMA_MA_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Nana-chan, Yosuke, Sensei... everyone's[n]doing homework...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I felt lonely and a little mad,[n]so I tried doing homework too.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]...It made me even lonelier...[n][f 1 1][e]

[msg YOSUKE_MA_3 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 10 65535 1]Geez, first the campout and now this...[n]Our school has some seriously lame events.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Well, since the usual gang is coming[n]along, at least we won't get bored.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 14 65535 1]Oh, that's right! We need to remember[n]to get a souvenir for Kuma, too.[n][f 1 1][e]

[msg KUMA_MA_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Port Island, huh? You guys are going[n]pretty far away from here...[n][f 1 1][e]
[f 0 5 65278][f 2 1]How many bananas are you allowed[n]to bring?[n][f 1 1][e]

[msg YOSUKE_MA_4 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 11 65535 1]Did Nanako-chan like the souvenir you[n]bought her?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Didn't she miss you? You were gone for[n]three days...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I know the part-time girls at Junes[n]were freaking out with Kuma gone.[n][f 1 1][e]

[msg KUMA_MA_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I had so many new experiences...[n]I'm glad I had the guts to go through[n]with it.[n][f 1 1][e]
[f 0 5 65278][f 2 1]The world over there is so big![n]I was seriously impressed.[n][f 1 1][e]

[msg KUMA_MA_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I heard about what happened. It's about[n]that boy I saw during the trip, right?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I have a feeling that he's planning[n]something... He didn't seem like an[n]ordinary kid.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I mean, he's right behind me in the[n]pretty boy rankings...[n][f 1 1][e]

[msg KUMA_NA_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]Heehee, more girls are always welcome[n]in our group![n][f 1 1][e]
[f 0 5 65278][f 2 1]Wow, she's a beaut. She brings that[n]flowery touch a group like ours needs![n][f 1 1][e]

[msg KUMA_NA_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]So it's that time of year again...[n]I'm always left out when you guys start[n]talking about exams.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Hmph, that's fine with me. I'll just[n]work at Junes. I wonder if Nana-chan[n]will come by to play...[n][f 1 1][e]

[msg KUMA_NA_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Urrgh, exams... Maaaan, if only we[n]didn't have to put up with these...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]That was my Yosuke impression.[n]Did it sound like him?[n][f 1 1][e]

[msg KUMA_NA_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]The girls will finally come back to[n]Junes now! I'm one happy bear![n][f 1 1][e]
[f 0 5 65278][f 2 1]I was getting tired of the slow period[n]during your examinations.[n][f 1 1][e]

[msg KUMA_NA_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Other people can go to the Culture[n]Festival too!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Mwahahahaha... My hour at last![n][f 1 1][e]

[msg YUKIKO_NA_6 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 23 65535 1]I'm a little disappointed that Kuma[n]walked away with the trophy.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I thought you were quite pretty when I[n]finished with you, [f 4 2]-kun...[n][f 1 1][e]

[msg KUMA_NA_6 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It was kinda depressing at the end,[n]but I still had a lot of fun![n][f 1 1][e]
[f 0 5 65278][f 2 1]School is a fun place![n][f 1 1][e]

[msg KUMA_NAM_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Something's not right lately...[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Sometimes I can't tell where I am...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Am I in this world or that one...[n][f 1 1][e]
[f 0 5 65278][f 2 1]...I wanna see Nana-chan.[n][f 1 1][e]

[msg MSG_HEYA_SUGUNERU_EVT_02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]Huh...?[n][f 1 1][e]

[msg MSG_HEYA_SUGUNERU_EVT_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 14 0 1]S-S-S-S-Sensei!?[n][f 1 1][e]

[msg MSG_HEYA_SUGUNERU_EVT_04]
[f 0 5 65278][f 2 1]> You can hear Kuma's voice from[n]far away...[n][f 1 1][e]

[msg MSG_0109_STOP]
[f 0 5 65278][f 2 1]> Rise and Kuma are gathering information[n]on that other world right now...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You shouldn't summon your friends to[n]the food court today...[n][f 1 1][e]

[msg DRINK_1 [Kuma]]
[f 0 5 65278][f 2 1]You drank [f 2 4 0].[n][f 1 1][e]

[msg DRINK_2 [Kuma]]
[f 0 5 65278][f 2 1]You drank [f 2 4 1].[n][f 1 1][e]

[msg NOT_DRINK [Kuma]]
[f 0 5 65278][f 2 1]You decided not to drink anything.[n][f 1 1][e]

[msg DEBUG_CHK_NPC]
[f 0 5 65278][f 2 1]High: [f 2 4 0][n]Low: [f 2 4 1][n]Number of NPC that can be placed: [f 2 4 2][n][f 1 1][e]
[f 0 5 65278][f 2 1]Yosuke: [f 2 4 3] / Chie: [f 2 4 4] / Yukiko: [f 2 4 5][n]Kanji: [f 2 4 6] / Naoto: [f 2 4 7] / Kuma: [f 2 4 8][n]Fox: [f 2 4 9]  (Where each of them will be placed)[n][f 1 1][e]

[msg MSG_GOJITUDAN_GUIDE_YOUS]
[f 0 5 65278][f 2 1]> Come to think of it, you have yet[n]to say goodbye to Yosuke and Kuma...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> You should visit the [f 0 1 2]Junes'[n]food court[f 0 1 0]...[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_10]
[f 0 5 65278][f 2 1]> Come to think of it, you have yet[n]to greet Kuma...[n][f 1 1][e]
[f 0 5 65278][f 2 1]> If you visit [f 0 1 2]Junes[f 0 1 0],[n]will you be able to meet him...?[n][f 1 1][e]

[msg MSG_NEWYEAR_GREETING_GUI_11]
[f 0 5 65278][f 2 1]> Come to think of it, you have yet[n]to greet Kuma...[n][f 1 1][e]