[msg KANJI_W_NAOTO_LV4_4 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 14 65535 1]Oh... Really? Sorry! Er, Kuma told[n]me that, so...[n][f 1 1][e]

[msg KANJI_W_KUMA_LV0_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yes there is![n][f 1 1][e]

[msg KANJI_W_KUMA_LV0_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1]Be honest, Kanji. Did you secretly join[n]our group just to hit on Sensei!?[n][f 1 1][e]

[msg KANJI_W_KUMA_LV1_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Cash... Is that juicy?[n][f 1 1][e]

[msg KANJI_W_KUMA_LV1_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]No way, Mister.[n][f 1 1][e]

[msg KANJI_W_KUMA_LV2_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]But one day, you'll go around the[n]corner, bump into that officer,[n]and fall in love...[n][f 1 1][e]

[msg KANJI_W_KUMA_LV2_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Heeheehee... A perfect match then,[n]rawrrr.[n][f 1 1][e]

[msg KANJI_W_KUMA_LV3_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Kanji... Did you do something bad to[n]Sensei again?[n][f 1 1][e]
[f 0 5 65278][f 2 1]What was it this time? I'll forgive[n]you if you just tell the truth.[n][f 1 1][e]

[msg KANJI_W_KUMA_LV3_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]S-So you are after my body!?[n][f 1 1][e]

[msg KANJI_W_KUMA_LV4_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You shouldn't worry about it. That stuff[n]is what makes you special.[n][f 1 1][e]

[msg KANJI_W_KUMA_LV5_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'm not sure what you mean, but I think[n]a bear would be nice. People all over[n]the world love bears![n][f 1 1][e]

[msg KANJI_W_KUMA_LV5_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Kanji... Don't tell me you're seriously[n]after me...?[n][f 1 1][e]

[msg KANJI_W_KUMA_LV6_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Want me to say it too?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Thank you, raawr! Thank you, raawr![n]...How's that?[n][f 1 1][e]

[msg KANJI_W_KUMA_LV6_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]I can't be a bear and not say raawr![n][f 1 1][e]

[msg KANJI_W_KUMA_LV7_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I know, I know! My shoulders are all[n]tense too.[n][f 1 1][e]

[msg KANJI_W_KUMA_LV7_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Yaaay, go right ahea--*gasp*[n]Are you pretending to be nice just to[n]feel my fur!?[n][f 1 1][e]

[msg KANJI_W_KUMA_LV8_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Kanji, you dunno what Ma means?[n]You're such a hopeless idiot.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Now listen up. A Ma- skill is like[n]a regular skill, but it affects[n]all the enemies...[n][f 1 1][e]

[msg KANJI_W_KUMA_LV9_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Kanji... Are you going to the[n]sauna again?[n][f 1 1][e]

[msg KANJI_W_KUMA_LV10_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Kanji gave me a bear-shaped "phone strap"[n]thingy too, but...[n][f 1 1][e]

[msg KANJI_W_KUMA_LV10_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I don't need a gimmick like that...[n][f 1 1][e]