[msg KUMA_F_KUBO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I think this is going pretty well![n]Of course, I haven't found any[n]clues yet.[n][f 1 1][e]

[msg KUMA_F_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]What's important now is to rescue him![n]Let's leave the teddie-ous stuff for[n]later![n][f 1 1][e]
[f 0 5 65278][f 2 1]...Snrk.[n][f 1 1][e]

[msg KUMA_F_NANAKO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Sensei... Let's do everything we can[n]to rescue Nana-chan![n][f 1 1][e]

[msg KUMA_F_ADATI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]That stupid Adachy-baby... He sure[n]talks big for such a lame cop![n][f 1 1][e]

[msg KUMA_F_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]The culprit's around here...[n]This is going to be pretty tough...[n][f 1 1][e]

[msg KUMA_F_OUT [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]We can't let our guard down, Sensei![n]Shadows are around, so be on the lookout.[n][f 1 1][e]

[msg KUMA_F_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]There's a bunch of Shadows here too.[n]Be careful, Sensei![n][f 1 1][e]

[msg KUMA_A_KUBO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]We'll catch the culprit![n][f 1 1][e]

[msg KUMA_A_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Time to show my stuff![n][f 1 1][e]

[msg KUMA_A_NANAKO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I know we can't rescue her without you,[n]Sensei. Give us good orders, okay?[n][f 1 1][e]

[msg KUMA_A_ADATI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]We'll pursue him like, raaawr![n]And then we'll crush him like, squaaash![n][f 1 1][e]

[msg KUMA_A_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]This looks like the end. You can do[n]it, Sensei... I believe in you.[n][f 1 1][e]

[msg KUMA_A_OUT [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Just do your best, Sensei.[n]I'll be rooting for you![n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV7Y [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yosuke's thinking about something.[n]Sometimes his face makes him look like[n]an adult...[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV2_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It feels so refreshing to walk around[n]inside here![n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's too bad Yosuke had to come...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I wanted to hang out with Yuki-chan[n]or Chie-chan![n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV2_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yosuke is acting like me?[n]...Wanna try wearing this?[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV3_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mais oui, should we be talking at[n]a time like this? You're a pretty[n]easygoing bear, Sensei.[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV3_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Thank you Captain Obvious, whose secret[n]identity is Yosuke Hanamura! You're on[n]a roll again today.[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV3_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'm sorry.[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV4_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I want to play with Nana-chan again.[n]She's so kind and cute... She's a really[n]good girl.[n][f 1 1][e]
[f 0 5 65278][f 2 1]When can I go over and see her again?[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV4_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh, you can't come, Yosuke.[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV5_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]When times are tough, I remember that[n]great feeling from the night of the[n]school trip...[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV5_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mwahaha, I embraced Yuki-chan.[n]I had no choice! It was on the[n]king's orders... rawr.[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV5_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sorry, I didn't hear that, raawr.[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV6_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]X-rays couldn't do the trick either...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I wonder what I am...[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV6_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]I'm a brown bear!?[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV7_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If I am a king, then that makes sense[n]in some ways.[n][f 1 1][e]
[f 0 5 65278][f 2 1]My dignified face, delicate behavior,[n]and romantic bearing...[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV7_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...C'mon, Yosuke! Now's your chance![n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV8_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]The school trip, the hot springs...[n]So many great memories.[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Thank you, Sensei.[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV8_2 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 11 65535 1]Are you crying, Kuma?[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV8_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'm not... crying... *sniff*[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV8_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...Mm. Thanks, Yosuke...[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV9_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I'm worried about Nana-chan...[n]Can I stay here...?[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV10_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Alrighty![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm gonna do everything I can![n]I'm gonna give it my all![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm ready on so many levels![n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV10_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yosuke, if you aren't up for this,[n]we're gonna leave you behind.[n][f 1 1][e]

[msg KUMA_W_YOSUKE_LV10_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Ooooh, a challenge...[n][f 1 1][e]
[f 0 5 65278][f 2 1]...The winner gets the manager's[n]position at Junes.[n][f 1 1][e]

[msg KUMA_RVS_ALL [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sensei, just between you and me...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's been pretty awkward lately...[n]It's getting in the way of our search...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Did you do something?[n][f 1 1][e]

[msg KUMA_BRO_CHIE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I won't say any more. You must know[n]what you're doing, Sensei...[n][f 1 1][e]
[f 0 5 65278][f 2 1]...But Chie-chan's been really scary all[n]this time! Hurry and make up with her,[n]pleeeease![n][f 1 1][e]

[msg KUMA_W_CHIE_LV2_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It feels so refreshing to walk around[n]inside here.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Chie-chan's with us too... Teeheehee![n][f 1 1][e]

[msg KUMA_W_CHIE_LV3_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mais oui, should we be talking at[n]a time like this? You're a pretty[n]easygoing bear, Sensei.[n][f 1 1][e]

[msg KUMA_W_CHIE_LV3_2 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 11 65535 1]Whoa, you seem fired up, Kuma![n]Let's all do our best![n][f 1 1][e]

[msg KUMA_W_CHIE_LV3_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Teeheehee, I'll do my best with you,[n]Chie-chan![n][f 1 1][e]
[f 0 5 65278][f 2 1]...You guys go somewhere else, rawr.[n][f 1 1][e]

[msg KUMA_W_CHIE_LV4_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I want to play with Nana-chan again.[n]She's so kind and cute... She's a really[n]good girl.[n][f 1 1][e]
[f 0 5 65278][f 2 1]When can I go over and see her again?[n][f 1 1][e]

[msg KUMA_W_CHIE_LV4_2 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 12 65535 1]Kuma, don't tell me... You're not[n]after a sweet girl like her, are you...?[n][f 1 1][e]

[msg KUMA_W_CHIE_LV4_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]After?[n][f 1 1][e]
[f 0 5 65278][f 2 1]...I don't get what you mean, but the[n]ones I want to score with are you and[n]the other girls.[n][f 1 1][e]

[msg KUMA_W_CHIE_LV4_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Heehee, that's what they call "jealousy"![n][f 1 1][e]

[msg KUMA_W_CHIE_LV5_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]When times are tough, I remember that[n]great feeling from the night of the[n]school trip...[n][f 1 1][e]

[msg KUMA_W_CHIE_LV6_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]X-rays couldn't do the trick either...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I wonder what I am...[n][f 1 1][e]

[msg KUMA_W_CHIE_LV6_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]My policy is to not reflect on the past.[n][f 1 1][e]

[msg KUMA_W_CHIE_LV7_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If I am a king, then that makes sense[n]in some ways.[n][f 1 1][e]
[f 0 5 65278][f 2 1]My dignified face, delicate behavior,[n]and romantic bearing...[n][f 1 1][e]

[msg KUMA_W_CHIE_LV7_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Why don't we make Chie-chan a princess?[n][f 1 1][e]

[msg KUMA_W_CHIE_LV8_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]The school trip, the hot springs...[n]So many great memories.[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Thank you, Sensei.[n][f 1 1][e]

[msg KUMA_W_CHIE_LV8_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Chie-chan... Thanks...[n][f 1 1][e]

[msg KUMA_W_CHIE_LV9_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I'm worried about Nana-chan...[n]What should I do...?[n][f 1 1][e]

[msg KUMA_W_CHIE_LV9_2 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 13 65535 1]Kuma...[n][f 1 1][e]

[msg KUMA_W_CHIE_LV10_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Alrighty![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm gonna do everything I can![n]I'm gonna give it my all![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm ready on so many levels![n][f 1 1][e]

[msg KUMA_W_CHIE_LV10_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I-I wonder what bear that could be...[n][f 1 1][e]

[msg KUMA_W_CHIE_LV10_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Chie-chan, who once ran off heedlessly[n]on her own, has finally become an[n]adult... I'm moved to tears... *sniff*[n][f 1 1][e]

[msg KUMA_BRO_YUKIKO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I won't say any more. You must know[n]what you're doing, Sensei...[n][f 1 1][e]
[f 0 5 65278][f 2 1]...But Yuki-chan's been really scary all[n]this time! Hurry and make up with her,[n]pleeeease![n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV2_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It feels so refreshing to walk around[n]inside here.[n][f 1 1][e]
[f 0 5 65278][f 2 1]My heart's all throbbing, since[n]Yuki-chan's with us.[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV2_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I-I won't say it anymore! I swear![n][f 1 1][e]
[f 0 5 65278][f 2 1]All those embarrassing things about[n]Yuki-chan, like scoring and princes,[n]will never be mentioned--[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV3_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mais oui, should we be talking at[n]a time like this? You're a pretty[n]easygoing bear, Sensei.[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV3_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I see... you're absolutely right,[n]Yuki-chan! Why don't you and I take[n]a break here for a while?[n][f 1 1][e]
[f 0 5 65278][f 2 1]...What're you waiting for?[n]You guys can hurry on, Sensei.[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV4_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I want to play with Nana-chan again.[n]She's so kind and cute... She's a really[n]good girl.[n][f 1 1][e]
[f 0 5 65278][f 2 1]When can I go over and see her again?[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV4_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]C-C-Call her!?[n]Whoa... I feel so nervous![n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV5_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]When times are tough, I remember that[n]great feeling from the night of the[n]school trip...[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV5_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Teeheehee... I'm not telling.[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV6_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]X-rays couldn't do the trick either...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I wonder what I am...[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV6_2 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 20 65535 1]Kuma's Kuma.[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV6_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Y-Yuki-chan...[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV6_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yuki-chan... Marry me![n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV7_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If I am a king, then that makes sense[n]in some ways.[n][f 1 1][e]
[f 0 5 65278][f 2 1]My dignified face, delicate behavior,[n]and romantic bearing...[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV7_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]R-Really? Teeheehee, Yuki-chan[n]praised me![n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV8_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]The school trip, the hot springs...[n]So many great memories.[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Thank you, Sensei.[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV8_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yuki-chan... Thanks...[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV9_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I'm worried about Nana-chan...[n]What should I do...?[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV10_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Alrighty![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm gonna do everything I can![n]I'm gonna give it my all![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm ready on so many levels![n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV10_2 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 21 65535 1]Ahaha, you seem serious this time,[n]Kuma. You're much different than[n]when we first met you.[n][f 1 1][e]

[msg KUMA_W_YUKIKO_LV10_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hmhmhm, have I become a dandy bear?[n]I'm an elderly gentleman now![n][f 1 1][e]

[msg KUMA_W_KANJI_LV2_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It feels so refreshing to walk around[n]inside here![n][f 1 1][e]
[f 0 5 65278][f 2 1]...It would be more fun if Kanji[n]wasn't here, though.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm still in danger, just in[n]a different way.[n][f 1 1][e]

[msg KUMA_W_KANJI_LV2_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...I haven't said anything yet.[n]Don't glare at me like that...[n][f 1 1][e]

[msg KUMA_W_KANJI_LV3_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mais oui, should we be talking at[n]a time like this? You're a pretty[n]easygoing bear, Sensei.[n][f 1 1][e]

[msg KUMA_W_KANJI_LV3_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...I won't let you pet me, even if you[n]praise me like that.[n][f 1 1][e]

[msg KUMA_W_KANJI_LV4_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I want to play with Nana-chan again.[n]She's so kind and cute... She's a really[n]good girl.[n][f 1 1][e]
[f 0 5 65278][f 2 1]When can I go over and see her again?[n][f 1 1][e]

[msg KUMA_W_KANJI_LV4_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]No spoiled children allowed. A true man[n]keeps his mouth shut and eats it down![n][f 1 1][e]
[f 0 5 65278][f 2 1]You're a man, Kanji![n][f 1 1][e]

[msg KUMA_W_KANJI_LV5_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]When times are tough, I remember that[n]great feeling from the night of the[n]school trip...[n][f 1 1][e]

[msg KUMA_W_KANJI_LV5_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Headbutt? What're you talking about?[n][f 1 1][e]

[msg KUMA_W_KANJI_LV6_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]X-rays couldn't do the trick either...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I wonder what I am...[n][f 1 1][e]

[msg KUMA_W_KANJI_LV6_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Kanji...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Y-You can do whatever you want to me...[n][f 1 1][e]

[msg KUMA_W_KANJI_LV7_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If I am a king, then that makes sense[n]in some ways.[n][f 1 1][e]
[f 0 5 65278][f 2 1]My dignified face, delicate behavior,[n]and romantic bearing...[n][f 1 1][e]

[msg KUMA_W_KANJI_LV7_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...You still can't touch it.[n][f 1 1][e]

[msg KUMA_W_KANJI_LV8_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]The school trip, the hot springs...[n]So many great memories.[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Thank you, Sensei.[n][f 1 1][e]

[msg KUMA_W_KANJI_LV8_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...Yeah. Thanks to you too, Kanji.[n][f 1 1][e]

[msg KUMA_W_KANJI_LV9_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I'm worried about Nana-chan...[n]What should I do...?[n][f 1 1][e]

[msg KUMA_W_KANJI_LV9_2 [Kanji]]
[f 0 5 65278][f 2 1][f 4 6 6 10 65535 1]Kuma...[n][f 1 1][e]

[msg KUMA_W_KANJI_LV10_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Alrighty![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm gonna do everything I can![n]I'm gonna give it my all![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm ready on so many levels![n][f 1 1][e]

[msg KUMA_W_KANJI_LV10_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...That's just for dramatic effect,[n]so as not to forget a young boy's[n]innocence.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Besides, Kanji, you fixed it up with[n]your sewing kit in a--[n][f 1 1][e]

[msg KUMA_BRO_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I won't say any more. You must know[n]what you're doing, Sensei...[n][f 1 1][e]
[f 0 5 65278][f 2 1]...But Nao-chan's been really scary all[n]this time! Hurry and make up with her,[n]pleeeease![n][f 1 1][e]

[msg KUMA_W_NAOTO_LV5_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]When times are tough, I remember that[n]great feeling from the night of the[n]school trip...[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV5_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]What a pity! Then I could've enjoyed[n]it again and again...[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV6_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]X-rays couldn't do the trick either...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I wonder what I am...[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV6_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Raaawr! Nao-chan is so kind![n][f 1 1][e]
[f 0 5 65278][f 2 1]You can score with me if you want.[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV7_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If I am a king, then that makes sense[n]in some ways.[n][f 1 1][e]
[f 0 5 65278][f 2 1]My dignified face, delicate behavior,[n]and romantic bearing...[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV7_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...No! You need to pick on me more,[n]Nao-chan![n][f 1 1][e]

[msg KUMA_W_NAOTO_LV8_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]The school trip, the hot springs...[n]So many great memories.[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Thank you, Sensei.[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV8_2 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 11 65535 1]My memories of all my senpai have been[n]wonderful... Well, perhaps not all,[n]but I treasure them nonetheless.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Right, Kuma?[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV8_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yeah, Nao-chan...[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV9_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I'm worried about Nana-chan...[n]What should I do...?[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV9_2 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 13 65535 1]Kuma...[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV10_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Alrighty![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm gonna do everything I can![n]I'm gonna give it my all![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm ready on so many levels![n][f 1 1][e]

[msg KUMA_W_NAOTO_LV10_2 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 10 65535 1]You're quite spirited, Kuma. It's very[n]different from when you were troubled.[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV10_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Have I gotten cooler?[n][f 1 1][e]

[msg KUMA_W_NAOTO_LV10_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]W-Wait! Tell me more about how[n]I'm cooler![n][f 1 1][e]

[msg KUMA_W_FOX_LV2_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It feels so refreshing to walk around[n]inside here![n][f 1 1][e]
[f 0 5 65278][f 2 1]If me and Foxy-chan walked together,[n]we'd make a cute picture.[n][f 1 1][e]

[msg KUMA_W_FOX_LV3_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mais oui, should we be talking at[n]a time like this? You're a pretty[n]easygoing bear, Sensei.[n][f 1 1][e]

[msg KUMA_W_FOX_LV4_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I want to play with Nana-chan again.[n]She's so kind and cute... She's a really[n]good girl.[n][f 1 1][e]
[f 0 5 65278][f 2 1]When can I go over and see her again?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh, that's right.[n]You wanna come too, Foxy-chan?[n][f 1 1][e]

[msg KUMA_W_FOX_LV5_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]When times are tough, I remember that[n]great feeling from the night of the[n]school trip...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Did you want to come too, Foxy-chan?[n]You'll have to make do with the stories[n]I brought back.[n][f 1 1][e]

[msg KUMA_W_FOX_LV6_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]X-rays couldn't do the trick either...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I wonder what I am...[n][f 1 1][e]
[f 0 5 65278][f 2 1]And I wonder what Foxy-chan is...[n][f 1 1][e]

[msg KUMA_W_FOX_LV7_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If I am a king, then that makes sense[n]in some ways.[n][f 1 1][e]
[f 0 5 65278][f 2 1]My dignified face, delicate behavior,[n]and romantic bearing...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Right, Foxy-chan!?[n][f 1 1][e]

[msg KUMA_W_FOX_LV8_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]The school trip, the hot springs...[n]So many great memories.[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Thank you, Sensei.[n][f 1 1][e]

[msg KUMA_W_FOX_LV8_2]
[f 0 5 65278][f 2 1]> The fox gazes kindly up at Kuma...[n][f 1 1][e]

[msg KUMA_W_FOX_LV9_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I'm worried about Nana-chan...[n]What should I do...?[n][f 1 1][e]

[msg KUMA_W_FOX_LV9_2]
[f 0 5 65278][f 2 1]> The fox is looking up at Kuma with[n]a concerned expression...[n][f 1 1][e]

[msg KUMA_W_FOX_LV10_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Alrighty![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm gonna do everything I can![n]I'm gonna give it my all![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm ready on so many different levels![n][f 1 1][e]
[f 0 5 65278][f 2 1]Watch me, Foxy-chan![n][f 1 1][e]

[msg KUMA_ITEM_01 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]That's right, Sensei![n]This is for you... Here.[n][f 1 1][e]

[msg KUMA_ITEM_02 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sensei, how would you like this?[n][f 1 1][e]

[msg KUMA_ITEM_03 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh, that reminds me...[n]Do you want this, Sensei?[n][f 1 1][e]
[f 0 5 65278][f 2 1]They gave me a lot of them at Junes.[n]...But keep it a secret from Yosuke,[n]all right?[n][f 1 1][e]

[msg KUMA_ITEM_04 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'll give you this. It's a rare delicacy[n]that made this bear's cheeks drop![n][f 1 1][e]