[msg MSG_NPC_16_01_1]
[f 0 5 65278][f 2 1]> You've gathered enough information.[n]You should report to Kuma tomorrow.[n][f 1 1][e]

[msg MSG_NPC_16_01_2]
[f 0 5 65278][f 2 1]> You should report to Kuma as soon[n]as possible.[n][f 1 1][e]

[msg MSG_NPC_RISE_01 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 5 4 65535 1]I've been asking around about Kuma too,[n]but I'm surprised how many people actually[n]remember him.[n][f 1 1][e]
[f 0 5 65278][f 2 1]They're all like, "Oh yeah, that guy[n]in the bear suit from Junes..."[n][f 1 1][e]
[f 0 5 65278][f 2 1]But nobody has seen him, yesterday or[n]today...[n][f 1 1][e]
[f 0 5 65278][f 2 1]He's loved by so many different people...[n]Where the heck could he have gone...?[n][f 1 1][e]