[msg MSG_NPC_SEAFISH_WAIT_KUM [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If we catch the legendary fish, we can[n]have a legendary hot pot party with it![n]Oh, Sensei! We have to do this![n][f 1 1][e]

[msg MSG_NPC_SEAFISH_TALK_KUM [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sensei, let's go to the beach![n]I'll cheer you on the whole time![n][f 1 1][e]

[msg MSG_NPC_SEAFISH_WITH_KUM]
[f 0 5 65278][f 2 1]> You decided to go sea fishing with[n]Kuma...[n][f 1 1][e]