[msg TALK_YOSUKE_MITSUO_C [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 10 65535 1]There's no reason to be here anymore,[n]is there...?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 11 65535 1]Haha, but if we don't come, Kuma's gonna[n]sulk like there's no tomorrow![n][f 1 1][e]

[msg TALK_YUKIKO_RISE_C [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 21 65535 1]It's great that we were able to save[n]her... right, [f 4 2]-kun?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 4 20 65535 1]Kuma was a handful, though...[n][f 1 1][e]

[msg GO_DUNGEON_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Okay! Let me show you the way![n][f 1 1][e]

[msg TALK_KUMA_MARY [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sensei! Emmy-chan isn't in this part of[n]the TV world![n][f 1 1][e]

[msg TALK_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]What do you want to do today?[n][f 1 1][e]

[msg TALK_KUMA_GK_CASTLE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Are you going to get rid of that Shadow[n]in the castle?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Umm, to be honest...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I-I sort of forgot where the castle is...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]B-But I'm sure Chie-chan and Yuki-chan[n]didn't forget![n][f 1 1][e]
[f 0 5 65278][f 2 1]You should ask one of them to show you[n]where it is.[n][f 1 1][e]

[msg TALK_KUMA_GK_SAUNA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Are you going to get rid of the Shadow[n]in that steamy place?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I... forgot where it was...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]B-But I'm sure Kanji must remember![n][f 1 1][e]
[f 0 5 65278][f 2 1]He can help you![n][f 1 1][e]

[msg TALK_KUMA_MOROKIN_DEAD [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I made my miraculous recovery! So why[n]is everyone feeling down?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Sensei, is it not my time to shine yet?[n][f 1 1][e]

[msg TALK_KUMA_YUKIKO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Leave it to me to show the way![n][f 1 1][e]

[msg TALK_KUMA_YUKIKO_C [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'm glad you found her. But what is[n]the culprit trying to do!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's really annoying me. All I can do[n]is leave it to Sensei![n][f 1 1][e]

[msg TALK_KUMA_KANJI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sensei, are you leaving?[n][f 1 1][e]

[msg TALK_KUMA_KANJI_C [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Good work, Sensei! I always knew[n]you were amazing![n][f 1 1][e]

[msg TALK_KUMA_RISE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh, you're leaving?[n][f 1 1][e]

[msg TALK_KUMA_RISE_C [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]From now on, I'll help you search![n]I got the power![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'll give it my best shot as a[n]helpful bear![n][f 1 1][e]

[msg TALK_KUMA_MITSUO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]From now on, Rise-chan will show you[n]where to go.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'll be on the front line with Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]Is it my turn yet? Just wait until you[n]see the new and improved Kuma![n][f 1 1][e]

[msg TALK_KUMA_MITSUO_C [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]It's finally going to be peaceful here[n]again! Sensei... thank you![n][f 1 1][e]

[msg TALK_KUMA_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Another incident... The plot thickens.[n]Kuma thickens too.[n][f 1 1][e]

[msg TALK_KUMA_NAOTO_C [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Need some more glasses, don't you?[n]Mwahaha, I'm already making a pair![n][f 1 1][e]

[msg TALK_KUMA_NAMATAME [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Sensei! Nana-chan... Nana-chan is--![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]W-We gotta save her quick![n][f 1 1][e]

[msg TALK_KUMA_NAMATAME_C [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]We'll be able to play again, right...?[n]I promised Nana-chan...[n][f 1 1][e]
[f 0 5 65278][f 2 1]...I hope she gets better soon...[n][f 1 1][e]

[msg TALK_KUMA_ADACHI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Alright! Let's catch Adachy-baby![n][f 1 1][e]

[msg TALK_KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'm ready to go, Sensei![n]Raaaaaaawr![n][f 1 1][e]

[msg SARCH_KANJI_A [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You need to find out something that[n]shows what Kanji is like. Then I can[n]use it as a clue to find him.[n][f 1 1][e]
[f 0 5 65278][f 2 1]If you don't, I won't be able to pick[n]up his scent.[n][f 1 1][e]

[msg SARCH_KANJI_B [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 3 0 6 172]Oh, you found out more about Kanji![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 173]Hmmhmm, a complex...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 174]......[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1][f 3 1 3 0 6 175]Th-That's it!? That's all I have to go[n]on? You're working me to the stuffing...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 176]Oh well... Then I'll open my nose up[n]real wide and sniff real hard![n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1][f 3 1 3 0 6 177]Hrmmmm...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1][f 3 1 3 0 6 178]Oh, I think I found something! It feels[n]like our target! Is this it!?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 3 0 6 179]Follow me![n][f 1 3 65535][f 1 1][e]

[msg SARCH_RISE_A [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I want you to find out something that[n]gives me a clear idea of what this[n]Rise-chan is like.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I'm a little low on confidence now...[n]So it'd be nice if you could give me[n]a little hint about her...[n][f 1 1][e]

[msg SARCH_RISE_B [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1][f 3 1 3 0 6 180]Did you find out more about this[n]girl Rise-chan?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 181]Hmhm... Her real self...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 182]I see... She's just like me.[n]The delicate, sentimental type.[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 183]Then... Hrmmm...[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 184]Whaah!? There's something out there![n]Is this it? Did I find her!?[n][f 1 3 65535][f 1 1][e]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 185]Follow me![n][f 1 3 65535][f 1 1][e]

[msg FOX_FIRST_KUMA [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Hmm!? What's that weird thing with[n]the red apron?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Huh? Sensei's helper?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Amazing! Sensei sure knows some[n]neat people![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]Nice to meet you, Mr. Fox![n]Let's both do our best![n][f 1 1][e]

[msg TALK_RISE_ADACHI [Rise]]
[f 0 5 65278][f 2 1][f 4 6 5 10 65535 1]*chuckle* Kuma's happy that he got to[n]show his stuff.[n][f 1 1][e]
[f 0 5 65278][f 2 1]He's all fired up now![n][f 1 1][e]

[msg COSTUME_EYEGLASS_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Oh, yeah![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hehehe... I made these the right way[n]this time...[n][f 1 1][e]

[msg COSTUME_EYEGLASS_2]
[f 0 5 65278][f 2 1]> Kuma rummaged around before producing[n]something.[n][f 1 1][e]

[msg COSTUME_EYEGLASS_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Tadaaaaa![n][f 1 1][e]
[f 0 5 65278][f 2 1]Braaaaand-new gag glasses![n][f 1 1][e]
[f 0 5 65278][f 2 1]Per Yuki-chan's request, they have lenses[n]in them.[n][f 1 1][e]

[msg COSTUME_EYEGLASS_4 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 21 65535 1]Oh, really? Thanks, Kuma![n][f 1 1][e]
[f 0 5 65278][f 2 1]Hey, Chie! Let's put these on![n][f 1 1][e]

[msg COSTUME_EYEGLASS_5 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 13 65535 1]This again...? We did it before. There's no[n]need to do it again...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 3 12 65535 1]Come on, Kuma! Don't get all excited just[n]because Yukiko's a goof![n][f 1 1][e]

[msg COSTUME_EYEGLASS_6 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1]Ehehe, you're too kind![n][f 1 1][e]

[msg COSTUME_MARTIAL_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hey, what about me?[n][f 1 1][e]
[f 0 5 65278][f 2 1]You have anything for me?[n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Nothing?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Awww...[n][f 1 1][e]

[msg COSTUME_ZOKU_5 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hey, what about me?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Something for the bear?[n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Nothing?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Phooey...[n][f 1 1][e]

[msg COSTUME_PRINCE_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Oh my...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Foxy... Could it be...?[n][f 1 1][e]

[msg COSTUME_PRINCE_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Really!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]You're really giving me this, Foxy?[n]Somebody pinch me! I must be dreaming![n][f 1 1][e]

[msg COSTUME_PRINCE_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Whoah...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]I understand exactly what you're trying[n]to tell me![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'll become an amazing prince, beloved[n]by all![n][f 1 1][e]
[f 0 5 65278][f 2 1]A great prince...[n][f 1 1][e]
[f 0 5 65278][f 2 1]And once I have everyone's love...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'll be a KING![n]A PIRATE king![n][f 1 1][e]

[msg COSTUME_JERSY_3 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 12 65535 1]It's not a catsuit![n][f 1 1][e]
[f 0 5 65278][f 2 1]Hey, Kuma![n]Don't you start blushing![n][f 1 1][e]

[msg COSTUME_JERSY_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1]......[n][f 1 1][e]