[sel PARTY_SEL top]
[f 0 5 65278][f 2 1]Yosuke[e]
[f 0 5 65278][f 2 1]Chie[e]
[f 0 5 65278][f 2 1]Yukiko[e]
[f 0 5 65278][f 2 1]Kanji[e]
[f 0 5 65278][f 2 1]Naoto[e]
[f 0 5 65278][f 2 1]Kuma[e]
[f 0 5 65278][f 2 1]Done[e]

[msg TALK_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]This place is creepy...[n][f 1 1][e]

[msg TALK_KUMA_ADACHI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Let's catch Adachy-baby![n][f 1 1][e]

[msg TALK_KUMA_ADACHI2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]I have a bad feeling about this...[n]Sensei, let's catch him soon![n][f 1 1][e]

[msg TALK_KUMA_ADACHI3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]The smells from here and there are[n]all mixed up and cluttered...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Not good! We need to catch him quick![n][f 1 1][e]

[msg TALK_KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Soon we won't have to come here anymore![n][f 1 1][e]

[msg KUMA_OUT_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I get it. I'll try even harder now![n][f 1 1][e]

[msg KUMA_OUT_TRY [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Be careful, Sensei. I don't know[n]what's out there![n][f 1 1][e]

[msg KUMA_IN_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Leave it to me![n]...In moderation.[n][f 1 1][e]

[msg KUMA_IN_TRY [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'll be useful until the end![n]Treat me nice, okay Sensei?[n][f 1 1][e]

[msg KUMA_CHANGE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whoa, it's a full house. You could[n]always switch someone out...[n][f 1 1][e]