[sel PARTY_SEL top]
[f 0 5 65278][f 2 1]Yosuke[e]
[f 0 5 65278][f 2 1]Chie[e]
[f 0 5 65278][f 2 1]Yukiko[e]
[f 0 5 65278][f 2 1]Kanji[e]
[f 0 5 65278][f 2 1]Naoto[e]
[f 0 5 65278][f 2 1]Kuma[e]
[f 0 5 65278][f 2 1]Quit[e]

[msg TALK_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It's been a long time since I came here.[n][f 1 1][e]

[msg TALK_KUMA_KANJI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]What's wrong? Did you forget to do[n]something here?[n][f 1 1][e]

[msg TALK_KUMA_RISE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Sensei and Yosuke have grown a lot[n]since I first met you guys here...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I need to grow some, too.[n][f 1 1][e]

[msg TALK_KUMA_MITSUO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Lately I've been letting you down...[n][f 1 1][e]
[f 0 5 65278][f 2 1]My nose hasn't been helpful either...[n][f 1 1][e]

[msg TALK_KUMA_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'll try to grow up some too.[n][f 1 1][e]

[msg TALK_KUMA_NAMATAME [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Nana-chan...[n][f 1 1][e]

[msg TALK_KUMA_ADACHI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I don't smell anything here. But I can[n]feel that he's close...[n][f 1 1][e]

[msg TALK_KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]I met Sensei here... So many memories...[n][f 1 1][e]

[msg KUMA_OUT [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Okie-dokie. I'll hold the fort while[n]you're gone![n][f 1 1][e]

[msg KUMA_IN [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Leave it to me![n]...But not too much.[n][f 1 1][e]

[msg KUMA_CHANGE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whoa, it's a full house. You could[n]always switch someone out...[n][f 1 1][e]

[msg TALK_RISE_ADACHI [Rise]]
[f 0 5 65278][f 2 1][f 4 6 5 10 65535 1]Are there some clues here?[n]Kuma doesn't seem to be picking up[n]on anything...[n][f 1 1][e]

[msg TALK_RISE_LAST [Rise]]
[f 0 5 65278][f 2 1][f 4 6 5 10 65535 1]Kuma just told me.[n]This is where it all began...[n][f 1 1][e]

[msg TALK_NAOTO_ADACHI [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 10 65535 1]Is this place related to Adachi's[n]crimes...? Kuma's nose isn't[n]responding, is it?[n][f 1 1][e]