[sel PARTY_SEL top]
[f 0 5 65278][f 2 1]Yosuke[e]
[f 0 5 65278][f 2 1]Chie[e]
[f 0 5 65278][f 2 1]Yukiko[e]
[f 0 5 65278][f 2 1]Kanji[e]
[f 0 5 65278][f 2 1]Naoto[e]
[f 0 5 65278][f 2 1]Kuma[e]
[f 0 5 65278][f 2 1]Quit[e]

[msg TALK_YOSUKE_YUKIKO_1A [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 10 65535 1]I can never tell if Kuma is being[n]serious when he says this stuff...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Chie's definitely serious, though...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 13 65535 1]Well, she is Yukiko's best friend,[n]so of course she'd be worried...[n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Well, it's... You know...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's at times like these that you and[n]me gotta stay calm.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 11 65535 1]Between you and me, we can handle[n]anything! Right, [f 4 2]?[n][f 1 1][e]

[msg TALK_YOSUKE_YUKIKO_1B [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 10 65535 1]It's not raining today. So based on what[n]Kuma said...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 13 65535 1]If the fog hasn't cleared up on this side,[n]it shouldn't get foggy on that side.[n][f 1 1][e]
[f 0 5 65278][f 2 1]We're the only ones who can save Yukiko,[n]but things aren't critical yet.[n][f 1 1][e]
[f 0 5 65278][f 2 1]If we're not strong enough to keep going[n]here, we have time to get stronger.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 2 10 65535 1]Let's take it slowly but surely.[n][f 1 1][e]

[msg RESCUE_YUKIKO_DAY1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]The fog here isn't going anywhere soon,[n]but we should hurry anyway.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Evidence?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I haven't heard of that kind of food...[n][f 1 1][e]

[msg RESCUE_YUKIKO_DAY2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It's about time the fog in this world[n]cleared... I was getting tired of[n]the smell![n][f 1 1][e]

[msg RESCUE_YUKIKO_DAY3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Pretty soon...[n][f 1 1][e]
[f 0 5 65278][f 2 1]By the way...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Why do Yosuke and Chie-chan always[n]have such gloomy faces?[n][f 1 1][e]

[msg TALK_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Getting hit on by girls...[n]What a shocking encounter...![n][f 1 1][e]

[msg TALK_KUMA_CHIE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]That girl ran off on her own...[n]That's kinda dangerous![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 7 0 1]We should catch up to her quick, Sensei![n][f 1 1][e]

[msg TALK_KUMA_KANJI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Did you forget something?[n][f 1 1][e]

[msg TALK_KUMA_RISE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Is there something for us to do here?[n][f 1 1][e]

[msg TALK_KUMA_MITSUO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sensei, is it okay not to go after him?[n]This isn't the right place, is it...?[n][f 1 1][e]

[msg TALK_KUMA_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Even with my dull nose, I can tell[n]that this isn't where we should be.[n][f 1 1][e]

[msg TALK_KUMA_NAMATAME [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Nana-chan...[n][f 1 1][e]

[msg TALK_KUMA_ADACHI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Could you smell Adachi's scent all the[n]way here?[n][f 1 1][e]

[msg TALK_KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...I have my own memories of this[n]place, too...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's where I first learned about[n]scoring...[n][f 1 1][e]

[msg KUMA_NOT_RESCUE_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]This is bad, Sensei... This atmosphere[n]rubs me the wrong way...[n][f 1 1][e]

[msg KUMA_NOT_RESCUE_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]This isn't the time to be here![n]Sensei... We need to hurry![n][f 1 1][e]

[msg KUMA_NOT_CATCH_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Nrrrrgh... Sensei! I can't just[n]sit around...![n][f 1 1][e]
[f 0 5 65278][f 2 1]If we don't capture the culprit soon,[n]the fog is going to come...[n][f 1 1][e]

[msg KUMA_NOT_CATCH_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We need to go after the culprit...[n]This isn't the time to be laying around![n][f 1 1][e]

[msg KUMA_NOT_CATCH_A1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]This isn't where we need to be![n][f 1 1][e]

[msg KUMA_NOT_CATCH_A2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We should be going after Adachi![n]I get a funky smell from him...[n][f 1 1][e]

[msg KUMA_OUT_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I understand. I'll stay here.[n][f 1 1][e]

[msg KUMA_OUT_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mm, I understand. Is it okay to be[n]here...?[n][f 1 1][e]

[msg KUMA_OUT_MISSING_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...Okay. I understand.[n][f 1 1][e]

[msg KUMA_IN_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Leave it to me![n]...In moderation.[n][f 1 1][e]

[msg KUMA_IN_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I understand. But is it okay...?[n][f 1 1][e]

[msg KUMA_IN_MISSING_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh-kay...[n][f 1 1][e]

[msg KUMA_CHANGE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whoa, it's a full house. You could[n]always switch someone out...[n][f 1 1][e]

[msg KUMA_ITEM [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Ah, that's right![n][f 1 1][e]
[f 0 5 65278][f 2 1]Here, take this.[n][f 1 1][e]

[msg KUMA_ITEM_ADD [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh, this too.[n][f 1 1][e]
[f 0 5 65278][f 2 1]I gathered all of these myself.[n]I'll give them to you, Sensei![n][f 1 1][e]

[msg KUMA_CHASE_CHIE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Well, off you go.[n][f 1 1][e]

[msg KUMA_ITEM_RETURN [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If it's ever too hard to return,[n]use those.[n][f 1 1][e]

[msg NAOTO_NOT_RESCUE_2 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 13 65535 1]The weather report, and what Kuma[n]has told us... There is a time factor[n]here, [f 4 2]-san...[n][f 1 1][e]