[sel PARTY_SEL top]
[f 0 5 65278][f 2 1]Yosuke[e]
[f 0 5 65278][f 2 1]Chie[e]
[f 0 5 65278][f 2 1]Yukiko[e]
[f 0 5 65278][f 2 1]Kanji[e]
[f 0 5 65278][f 2 1]Naoto[e]
[f 0 5 65278][f 2 1]Kuma[e]
[f 0 5 65278][f 2 1]Quit[e]

[msg TALK_CHIE_KANJI2 [Chie]]
[f 0 5 65278][f 2 1][f 4 6 3 10 65535 1]Did you see the weather forecast...?[n]Kuma says it'll be okay, but...[n][f 1 1][e]

[msg RESCUE_KANJI_DAY1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]No need to worry! This fog won't clear[n]for a while.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Evidence...?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I told you I don't know what that is.[n]Is it tasty?[n][f 1 1][e]

[msg RESCUE_KANJI_DAY2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It seems like the fog over there[n]will clear...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Yep, I'm sure it'll clear up soon![n][f 1 1][e]

[msg RESCUE_KANJI_DAY3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]The fog is going to clear soon.[n]If we don't get moving...[n][f 1 1][e]
[f 0 5 65278][f 2 1]We have to work hard, Sensei, or it'll[n]get more dangerous from here on.[n][f 1 1][e]

[msg TALK_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]My fur has gotten all matted...[n][f 1 1][e]

[msg TALK_KUMA_RISE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]This isn't the right place. But I[n]don't have much faith in my nose...[n][f 1 1][e]

[msg TALK_KUMA_MITSUO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sensei, weren't we supposed to go[n]after him? He's not here, is he?[n][f 1 1][e]

[msg TALK_KUMA_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Shouldn't we be going after Nao-chan[n]pretty soon?[n][f 1 1][e]

[msg TALK_KUMA_NAMATAME [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Nana-chan...[n][f 1 1][e]

[msg TALK_KUMA_ADACHI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I don't really smell Adachi here...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]All I can smell here is sweat. Pee-yew![n][f 1 1][e]

[msg TALK_KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yikes... This smell again...[n][f 1 1][e]

[msg KUMA_NOT_RESCUE_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]This is bad, Sensei... There's something[n]creepy about this atmosphere...[n][f 1 1][e]

[msg KUMA_NOT_RESCUE_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]This isn't where we're supposed to be![n]Sensei! Let's hurry![n][f 1 1][e]

[msg KUMA_NOT_CATCH_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Sensei... We can't take it easy now.[n][f 1 1][e]
[f 0 5 65278][f 2 1]We need to hurry and catch the culprit[n]before the fog lifts...[n][f 1 1][e]

[msg KUMA_NOT_CATCH_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We came to catch the culprit...[n]This isn't the time to be hanging[n]around here![n][f 1 1][e]

[msg KUMA_NOT_CATCH_A1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We shouldn't be here![n][f 1 1][e]

[msg KUMA_NOT_CATCH_A2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We should be going after Adachi.[n]I'm catching a whiff of something[n]dangerous...[n][f 1 1][e]

[msg KUMA_OUT_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]That's okay. I'll stay here and[n]look after the place.[n][f 1 1][e]

[msg KUMA_OUT_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mm, I understand... Is it okay to[n]go there?[n][f 1 1][e]

[msg KUMA_OUT_MISSING_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...Okie-dokie.[n][f 1 1][e]

[msg KUMA_IN_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Leave it to me![n]...In moderation.[n][f 1 1][e]

[msg KUMA_IN_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I understand... But is this okay?[n][f 1 1][e]

[msg KUMA_IN_MISSING_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yeah...[n][f 1 1][e]

[msg KUMA_CHANGE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whoa, it's a full house. You could[n]always switch someone out...[n][f 1 1][e]

[msg NAOTO_NOT_RESCUE_2 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 12 65535 1]According to the weather report and[n]Kuma's information... There is[n]a time factor, [f 4 2]-san...[n][f 1 1][e]