[sel PARTY_SEL top]
[f 0 5 65278][f 2 1]Yosuke[e]
[f 0 5 65278][f 2 1]Chie[e]
[f 0 5 65278][f 2 1]Yukiko[e]
[f 0 5 65278][f 2 1]Kanji[e]
[f 0 5 65278][f 2 1]Naoto[e]
[f 0 5 65278][f 2 1]Kuma[e]
[f 0 5 65278][f 2 1]Quit[e]

[msg TALK_YUKIKO_LAST [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 21 65535 1]A lot of things happened here too...[n]That thing with Kuma and all.[n][f 1 1][e]

[msg RESCUE_RISE_DAY1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It's still all right! It doesn't seem[n]like the fog will clear![n][f 1 1][e]
[f 0 5 65278][f 2 1]Proof?[n][f 1 1][e]
[f 0 5 65278][f 2 1]The proof is my good ol' nose![n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]It hasn't been so good lately, but...[n]That's beside the point.[n][f 1 1][e]

[msg RESCUE_RISE_DAY2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]It'll be dangerous pretty soon...[n]But we still have some time.[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Sensei, it'd be best if we hurried![n][f 1 1][e]

[msg RESCUE_RISE_DAY3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Everyone seems down...[n]Even I can understand why...[n][f 1 1][e]
[f 0 5 65278][f 2 1]The fog will clear up pretty soon.[n]We better save her... fast...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]I-I'll give it my best![n]Sensei, let's go full steam ahead![n][f 1 1][e]

[msg TALK_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Coming here makes my soft fur stand[n]up on end...[n][f 1 1][e]

[msg TALK_KUMA_MITSUO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh, are we warming up? Then it's time[n]to show you my real strength![n][f 1 1][e]

[msg TALK_KUMA_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]We need to go save Nao-chan, quick![n]Sensei, this is the wrong place![n][f 1 1][e]

[msg TALK_KUMA_NAMATAME [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Nana-chan...[n][f 1 1][e]

[msg TALK_KUMA_ADACHI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I don't smell Adachi's stink anywhere[n]around here.[n][f 1 1][e]

[msg TALK_KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]This place is part of my memories.[n]My feelings haven't changed...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'll protect everyone![n]Phoenix Ranger Featherman Bear![n][f 1 1][e]

[msg KUMA_NOT_RESCUE_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]This is bad, Sensei... I don't like[n]how this place feels...[n][f 1 1][e]

[msg KUMA_NOT_RESCUE_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We don't have time to be here![n]Sensei, let's hurry![n][f 1 1][e]

[msg KUMA_NOT_CATCH_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]...Sensei. We can't waste time![n][f 1 1][e]
[f 0 5 65278][f 2 1]We need to catch the culprit before the[n]fog clears...[n][f 1 1][e]

[msg KUMA_NOT_CATCH_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We need to catch the culprit...[n]This isn't the time to be hanging[n]around here![n][f 1 1][e]

[msg KUMA_NOT_CATCH_A1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We shouldn't be here![n][f 1 1][e]

[msg KUMA_NOT_CATCH_A2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]It'd be better if we went after Adachi.[n]I'm picking up a dangerous scent...[n][f 1 1][e]

[msg KUMA_OUT_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Okie-dokie.[n][f 1 1][e]

[msg KUMA_OUT_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mm, alrighty then.[n][f 1 1][e]

[msg KUMA_OUT_MISSING_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...I understand.[n][f 1 1][e]

[msg KUMA_IN_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Leave it to me![n]...In moderation.[n][f 1 1][e]

[msg KUMA_IN_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I understand... But, is this okay?[n][f 1 1][e]

[msg KUMA_IN_MISSING_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Okay...[n][f 1 1][e]

[msg KUMA_CHANGE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whoa, it's a full house. You could[n]always switch someone out...[n][f 1 1][e]

[msg NAOTO_NOT_RESCUE_2 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 13 65535 1]Between the weather report and Kuma's[n]information... We are dealing with[n]a deadline here, [f 4 2]-san...[n][f 1 1][e]