[sel PARTY_SEL top]
[f 0 5 65278][f 2 1]Yosuke[e]
[f 0 5 65278][f 2 1]Chie[e]
[f 0 5 65278][f 2 1]Yukiko[e]
[f 0 5 65278][f 2 1]Kanji[e]
[f 0 5 65278][f 2 1]Naoto[e]
[f 0 5 65278][f 2 1]Kuma[e]
[f 0 5 65278][f 2 1]Quit[e]

[msg TALK_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Doot de doo doo doot de doo doo...[n]Argh, it's on an endless loop![n][f 1 1][e]

[msg TALK_KUMA_MITSUO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Hmmph! I'll show you what I can do![n][f 1 1][e]

[msg TALK_KUMA_MITSUO2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Arrrgh... We need to hurry! I don't[n]know what'll happen if we don't![n][f 1 1][e]

[msg TALK_KUMA_MITSUO3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]What exactly are you doing...?[n]I won't be satisfied until I hear[n]it straight from you![n][f 1 1][e]

[msg TALK_KUMA_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Are we starting a new game again?[n][f 1 1][e]

[msg TALK_KUMA_NAMATAME [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Nana-chan...[n][f 1 1][e]

[msg TALK_KUMA_ADACHI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I don't smell Adachi's stink anywhere[n]around here.[n][f 1 1][e]

[msg TALK_KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]What a strange place this was...[n]Lots of memories here.[n][f 1 1][e]

[msg KUMA_NOT_RESCUE_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]I don't like this, Sensei...[n]Something's not right...[n][f 1 1][e]

[msg KUMA_NOT_RESCUE_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We shouldn't be here![n]Sensei! Hurry...![n][f 1 1][e]

[msg KUMA_NOT_CATCH_A1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We shouldn't be here![n][f 1 1][e]

[msg KUMA_NOT_CATCH_A2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We should be going after Adachi.[n]I'm picking up a dangerous scent...[n][f 1 1][e]

[msg KUMA_OUT_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Okie-dokie.[n][f 1 1][e]

[msg KUMA_OUT_TRY [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Roger, captain![n][f 1 1][e]

[msg KUMA_OUT_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mm, I understand... But is it okay[n]to go there...?[n][f 1 1][e]

[msg KUMA_OUT_MISSING_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...All righty.[n][f 1 1][e]

[msg KUMA_IN_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Leave it to me![n]...In moderation.[n][f 1 1][e]

[msg KUMA_IN_TRY [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You can count on Kuma![n]...But not too much.[n][f 1 1][e]

[msg KUMA_IN_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I understand... But is it okay?[n][f 1 1][e]

[msg KUMA_IN_MISSING_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Okay...[n][f 1 1][e]

[msg KUMA_CHANGE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whoa, it's a full house. You could[n]always switch someone out...[n][f 1 1][e]

[msg NAOTO_NOT_RESCUE_2 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 10 65535 1]Between the weather report and Kuma's[n]information... There is a time factor[n]here, [f 4 1]-san.[n][f 1 1][e]