[sel PARTY_SEL top]
[f 0 5 65278][f 2 1]Yosuke[e]
[f 0 5 65278][f 2 1]Chie[e]
[f 0 5 65278][f 2 1]Yukiko[e]
[f 0 5 65278][f 2 1]Kanji[e]
[f 0 5 65278][f 2 1]Naoto[e]
[f 0 5 65278][f 2 1]Kuma[e]
[f 0 5 65278][f 2 1]Quit[e]

[msg TALK_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]If we're going to train, then I better[n]do my best![n][f 1 1][e]

[msg TALK_KUMA_NAOTO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]The incidents are still happening...[n]I need to do my best![n][f 1 1][e]

[msg TALK_KUMA_NAOTO2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]We need to hurry and find Naoto...[n]But isn't the atmosphere here strange?[n][f 1 1][e]

[msg TALK_KUMA_NAOTO3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]If the fog clears...[n]Sensei, we need to hurry![n][f 1 1][e]

[msg TALK_KUMA_NAMATAME [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Nana-chan...[n][f 1 1][e]

[msg TALK_KUMA_ADACHI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I don't smell Adachi's stink anywhere[n]around here.[n][f 1 1][e]

[msg TALK_KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]This is...Nao-chan's place.[n][f 1 1][e]
[f 0 5 65278][f 2 1]At first I was like, "Huh?" but now[n]I'm glad that we all came here.[n][f 1 1][e]

[msg KUMA_NOT_RESCUE_1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]This is bad, Sensei...[n]At this rate...[n][f 1 1][e]

[msg KUMA_NOT_RESCUE_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]...Sensei! We need to hurry to where[n]Nana-chan is![n][f 1 1][e]

[msg KUMA_NOT_CATCH_A1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We don't have time to waste here![n][f 1 1][e]

[msg KUMA_NOT_CATCH_A2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]It'd be better if we went after Adachi.[n]I'm starting to catch wind of a[n]dangerous scent...[n][f 1 1][e]

[msg KUMA_OUT_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Okie-dokie.[n][f 1 1][e]

[msg KUMA_OUT_TRY [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You're the boss![n][f 1 1][e]

[msg KUMA_OUT_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mm, I understand... Is it okay to[n]go there, though?[n][f 1 1][e]

[msg KUMA_OUT_MISSING_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...All right.[n][f 1 1][e]

[msg KUMA_IN_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Leave it to me![n]...In moderation.[n][f 1 1][e]

[msg KUMA_IN_TRY [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'm ready to do this! Max power![n][f 1 1][e]

[msg KUMA_IN_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I understand... But is this okay?[n][f 1 1][e]

[msg KUMA_IN_MISSING_N [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Okay...[n][f 1 1][e]

[msg KUMA_CHANGE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whoa, it's a full house. You could[n]always switch someone out...[n][f 1 1][e]

[msg NAOTO_NOT_RESCUE_2 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 13 65535 1]Between the weather report and Kuma's[n]information... We are operating under[n]a deadline, [f 4 2]-san...[n][f 1 1][e]