[sel PARTY_SEL top]
[f 0 5 65278][f 2 1]Yosuke[e]
[f 0 5 65278][f 2 1]Chie[e]
[f 0 5 65278][f 2 1]Yukiko[e]
[f 0 5 65278][f 2 1]Kanji[e]
[f 0 5 65278][f 2 1]Naoto[e]
[f 0 5 65278][f 2 1]Kuma[e]
[f 0 5 65278][f 2 1]Quit[e]

[msg TALK_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...This place is really pretty.[n]It's like Nana-chan is here with us.[n][f 1 1][e]

[msg TALK_KUMA_NAMATAME [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]I'll do it... I'll find her! Count on it![n][f 1 1][e]

[msg TALK_KUMA_NAMATAME2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]I can't settle down... W-We've still[n]got time, right?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's save her, on the double![n][f 1 1][e]

[msg TALK_KUMA_NAMATAME3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]At this rate...[n][f 1 1][e]
[f 0 5 65278][f 2 1]What should we do?[n]The fog'll clear soon...[n][f 1 1][e]

[msg TALK_KUMA_ADACHI [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Nana-chan went through such horrible[n]things... And it's all his fault![n][f 1 1][e]
[f 0 5 65278][f 2 1]Look out, Adachi! I'm seeing red![n][f 1 1][e]

[msg TALK_KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]This place will always be here...[n]Forever. Not just hers, but[n]everyone's...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]It makes me kind of happy.[n][f 1 1][e]

[msg KUMA_NOT_CATCH_A1 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We're in the wrong place![n][f 1 1][e]

[msg KUMA_NOT_CATCH_A2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]We should go to Adachi's place.[n]I'm getting a whiff of something bad...[n][f 1 1][e]

[msg KUMA_OUT_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Okie-dokie.[n][f 1 1][e]

[msg KUMA_OUT_TRY [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]...Will do. Be careful, Sensei![n][f 1 1][e]

[msg KUMA_OUT_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mm, all right. Is it okay to[n]go there...?[n][f 1 1][e]

[msg KUMA_IN_NO [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You can depend on me![n]...But not too much.[n][f 1 1][e]

[msg KUMA_IN_TRY [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Let's go find Nana-chan! I'll do my best![n][f 1 1][e]

[msg KUMA_IN_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I understand... But is this okay?[n][f 1 1][e]

[msg KUMA_CHANGE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whoa, it's a full house. You could[n]always switch someone out...[n][f 1 1][e]

[msg RESCUE_NAMATAME_DAY2 [Rise]]
[f 0 5 65278][f 2 1][f 4 6 5 10 65535 1]I'm a little worried about the fog...[n]Kuma said so too, so I'm sure of it.[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Don't make that face. Nanako-chan[n]is waiting for you, you know.[n][f 1 1][e]
[f 0 5 65278][f 2 1]You have to meet her with a smile[n]on your face, right?[n][f 1 1][e]