[sel PARTY_SEL top]
[f 0 5 65278][f 2 1]Yosuke[e]
[f 0 5 65278][f 2 1]Chie[e]
[f 0 5 65278][f 2 1]Yukiko[e]
[f 0 5 65278][f 2 1]Kanji[e]
[f 0 5 65278][f 2 1]Naoto[e]
[f 0 5 65278][f 2 1]Kuma[e]
[f 0 5 65278][f 2 1]Quit[e]

[msg TALK_KUMA_NO_MISSING [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]This is the end... the end...[n]I won't be with Sensei anymore...[n][f 1 1][e]

[msg TALK_KUMA_LAST [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]This is the last one![n]I'm ready and rarin' to go![n][f 1 1][e]

[msg KUMA_OUT [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Okay... I understand.[n]Be careful, Sensei![n][f 1 1][e]

[msg KUMA_IN [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Leave it to me! I'll stick with Sensei[n]through thick and thin![n][f 1 1][e]

[msg KUMA_CHANGE [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whoa, it's a full house. You could always[n]switch someone out...[n][f 1 1][e]