[msg NAOTO_W_KUMA_LV0_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1]That's right! Nao-chan doesn't want to[n]talk to you, Sensei.[n][f 1 1][e]
[f 0 5 65278][f 2 1]She wants to talk to me![n][f 1 1][e]

[msg NAOTO_W_KUMA_LV0_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Heehee.[n][f 1 1][e]
[f 0 5 65278][f 2 1]You act like you're not interested, but [n]you're really head over heels about me, [n]aren't you?[n][f 1 1][e]
[f 0 5 65278][f 2 1]C'mon, you can feel my fur if you want.[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV1_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Mwahaha, my ears hear all![n][f 1 1][e]

[msg NAOTO_W_KUMA_LV1_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You shouldn't spread rumors about people[n]when they're standing right there![n][f 1 1][e]
[f 0 5 65278][f 2 1]If you love me, you should say it to[n]my face![n][f 1 1][e]

[msg NAOTO_W_KUMA_LV2_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Nao-chan, you're being too nice.[n][f 1 1][e]
[f 0 5 65278][f 2 1]You should go ahead and worry Sensei all[n]you want![n][f 1 1][e]

[msg NAOTO_W_KUMA_LV2_3 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 14 65535 1]I-I couldn't do something like that...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 7 11 65535 1]But... thanks, Kuma.[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV3_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]There's only one thing that could be[n]left in a shoe box, raawr![n][f 1 1][e]

[msg NAOTO_W_KUMA_LV3_3 [Naoto]]
[f 0 5 65278][f 2 1][f 4 6 7 14 65535 1]Huh!? Ah... Kuma!?[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV3_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Shoes.[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV3a_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh Nao-chan, why don't you tell him?[n][f 1 1][e]
[f 0 5 65278][f 2 1]The meaning of the umbrella drawing... Uh...[n]What was it? I forgot.[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV4_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Phantom Thief, burglary... "Thief in[n]the Night"!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Like a thief in the night...[n]It can't be right...[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV5_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]There's hair on Nao-chan's head,[n]so I think it's still soft.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Want me to feel it to make sure?[n]Hm? Want me to?[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV6_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I want my face and body to stay the same,[n]but with longer, skinnier legs![n][f 1 1][e]
[f 0 5 65278][f 2 1]Nice, thin ones like yours, Nao-chan.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh... but would that make me a little[n]less cute?[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV6_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Then never mind.[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV7_3 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Oh, come on, you can't hide cookies[n]from me! Sharing is caring![n][f 1 1][e]

[msg NAOTO_W_KUMA_LV8_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Hrmm, Nao-chan's been acting like this[n]the whole time.[n][f 1 1][e]
[f 0 5 65278][f 2 1]Her face is red too... [n]Maybe she caught a cold?[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV8a_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Don't worry. Sensei is a man's man who[n]can forgive anything.[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV9_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whoa, here comes the sugary atmosphere![n]I'm so embarrassed that I could die too,[n]raaawr![n][f 1 1][e]

[msg NAOTO_W_KUMA_LV9a_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Nao-chan's gotten even more marvelous[n]lately. Her smile's blinding like[n]the sun.[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV10_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Wh-What's this!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]*gasp* Could it be...? Does she have[n]feelings for me!?[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV10a_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]That's all well and good, Nao-chan, but...[n][f 1 1][e]
[f 0 5 65278][f 2 1]I wish you'd stop stuffing the things you[n]find inside me.[n][f 1 1][e]
[f 0 5 65278][f 2 1]It gets so heavy...[n][f 1 1][e]

[msg NAOTO_W_KUMA_LV10a_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Heehee, she complimented me![n]Feel free to stick in more stuff![n][f 1 1][e]