[msg H_RISE_KUMA_HPSP_1]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 64]Kuma's all worn out![n]Someone heal him![n][f 1 6 65535][e]

[msg H_RISE_KUMA_HPSP_2]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 65]Kuma's health and[n]energy are really low![n][f 1 6 65535][e]

[msg H_RISE_KUMA_HPSP_3]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 66]Be careful! Kuma can[n]barely move anymore![n][f 1 6 65535][e]

[msg H_RISE_KUMA_HP_1]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 85]Careful, Kuma![n]You're low on health![n][f 1 6 65535][e]

[msg H_RISE_KUMA_HP_2]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 86]Kuma! You should[n]have that looked at![n][f 1 6 65535][e]

[msg H_RISE_KUMA_HP_3]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 87]You all right, Kuma?[n]Your health's low...[n][f 1 6 65535][e]