[msg CHIE_W_KUMA_LV1_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Training?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Are you training to grow a new inside,[n]like me?[n][f 1 1][e]

[msg CHIE_W_KUMA_LV2_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Chie-chan and Sensei are training[n]together!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]C-Could it be...?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]The Divine Kuma Fist... An instant death[n]move passed down from father to son...[n][f 1 1][e]
[f 0 5 65278][f 2 1]The world was engulfed in nuclear flame,[n]and all had perished except for Kuma and[n]some other guys...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It is a dark age, where battles over limited[n]resources are neverending...[n][f 1 1][e]
[f 0 5 65278][f 2 1]But then, a bear descends upon the golden[n]fields, wrapped in a robe of blue...[n][f 1 1][e]

[msg CHIE_W_KUMA_LV2_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Right...[n][f 1 1][e]

[msg CHIE_W_KUMA_LV3_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]A moth? What's that?[n][f 1 1][e]

[msg CHIE_W_KUMA_LV3_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Does that mean you're gonna be my bride!?[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1]Kiss me, my love![n][f 1 1][e]

[msg CHIE_W_KUMA_LV4_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]Yep yep! That's our Yuki-chan.[n][f 1 1][e]

[msg CHIE_W_KUMA_LV4_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Nope nope. I understand everything[n]about you, Chie-chan![n][f 1 1][e]

[msg CHIE_W_KUMA_LV5_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]You just leave everything to me![n][f 1 1][e]
[f 0 5 65278][f 2 1]I'll go, like, raaaaawr and protect[n]Yuki-chan and Chie-chan![n][f 1 1][e]

[msg CHIE_W_KUMA_LV6_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Why're you apologizing to Sensei?[n][f 1 1][e]

[msg CHIE_W_KUMA_LV6_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Why are you apologizing to Sensei for[n]that then?[n][f 1 1][e]

[msg CHIE_W_KUMA_LV7_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1]Ahaaaa... Chie-chan, you're totally in[n]love with me, huh?[n][f 1 1][e]
[f 0 5 65278][f 2 1]When we're walking together like this...[n]your heart's about to skip a beat...[n]right?[n][f 1 1][e]

[msg CHIE_W_KUMA_LV8_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You drool if you like someone?[n]Alrighty, I'll try it out...[n][f 1 1][e]

[msg CHIE_W_KUMA_LV9_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]You don't have to worry so much.[n]You're as cute as ever, Chie-chan![n][f 1 1][e]
[f 0 5 65278][f 2 1]Your coat of fur is all nice and[n]slick too.[n][f 1 1][e]

[msg CHIE_W_KUMA_LV9a_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Chie-chan's totally on fire! A second[n]ago, she almost punched me too![n][f 1 1][e]

[msg CHIE_W_KUMA_LV9a_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]That wasn't an evil presence--it was my[n]love beams![n][f 1 1][e]

[msg CHIE_W_KUMA_LV10_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Wh-What's with this shyness ray!?[n][f 1 1][e]
[f 0 5 65278][f 2 1]C'mon, Sensei. Do something already![n]I'm gonna die of shyness if this[n]keeps up...[n][f 1 1][e]

[msg CHIE_W_KUMA_LV10a_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]That's fine, but you've been staring[n]at your wrist and grinning all this[n]time, Chie-chan.[n][f 1 1][e]

[msg CHIE_W_KUMA_LV10a_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]F-Friendship...!? I want one too![n]I want one too, raaaawr![n][f 1 1][e]