[msg YOSUKE_W_YUKIKO_LV3_1 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 13 65535 1]Hey, [f 4 2]... Even Yukiko[n]says I'm turning into Kuma...[n][f 1 1][e]

[msg YOSUKE_W_YUKIKO_LV3_4 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 24 65535 1]Huh, Kuma!? Was that you!?[n][f 1 1][e]

[msg YOSUKE_W_KANJI_LV3_1 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 13 65535 1]Hey, [f 4 2]... I'm not[n]turning into Kuma, am I?[n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV1_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I wanna go have fun too![n][f 1 1][e]
[f 0 5 65278][f 2 1]Not with Yosuke, though--I wanna go[n]play with Yuki-chan and Chie-chan![n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV1_3 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 10 65535 1]...You're not going anywhere, Kuma.[n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV2_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Daigaku... A college!? I wanna go too![n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV2_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]R-Really...!? That's even better![n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV3_1 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 13 65535 1]Hey, [f 4 2]... I'm not[n]turning into Kuma, am I?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I get anxious when I'm looking at[n]this dude...[n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV3_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whaaa!? What're you talking about!?[n]Kuma's cuteness is in a class of[n]its own! I'm the world champyon![n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV4_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Did you fight something huge?[n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV4_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Whaaa!? Wow! I wanna study its technique![n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV5_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]The best place to hide important stuff[n]is inside your body.[n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV6_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sheesh, Yosuke is totally useless[n]without Sensei around![n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV7_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yosuke... Does your tummy hurt?[n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV7_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]...Nothing.[n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV8_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yosuke! Crying at your age? That's why[n]the girls shun you.[n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV9_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I think Yosuke and Sensei are a[n]good match.[n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV9_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'm probably a better match for[n]Sensei, though.[n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV10_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I saw Yosuke getting all scolded.[n][f 1 1][e]
[f 0 5 65278][f 2 1]He was bowing his head over and over[n]at light-speed![n][f 1 1][e]

[msg YOSUKE_W_KUMA_LV10_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Yosuke... That smirk's creeping me out.[n][f 1 1][e]

[msg YOSUKE_W_FOX_LV3_1 [Yosuke]]
[f 0 5 65278][f 2 1][f 4 6 2 13 65535 1]Hey, [f 4 2]... I'm not[n]turning into Kuma, am I?[n][f 1 1][e]
[f 0 5 65278][f 2 1]To tell the truth, the other guys tell[n]me that too... What do you think, Foxy?[n][f 1 1][e]