[msg YUKIKO_W_KUMA_LV1_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]After high school...? I've been[n]thinking a lot about that![n][f 1 1][e]
[f 0 5 65278][f 2 1]One day, I wanna become your "after[n]high school," Yuki-chan... Squeeee![n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV2_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]You're doing part-time work, Yuki-chan?[n]I want to do it with you too![n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV2_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]...Ohhh, so that's what a part-time[n]job is... Never mind, then.[n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV3_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]I'm filled to the brim with meat![n]And I'm also a cute boy, so you[n]get double your money's worth.[n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV3_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]N-Noooo![n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV4_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Hrmm... Kuma Sensors activated![n][f 1 1][e]
[f 0 5 65278][f 2 1]I sense a faint, yet definite shyness[n]alert! R-Retreat![n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV4_3 [Yukiko]]
[f 0 5 65278][f 2 1][f 4 6 4 24 65535 1]K-Kuma!?[n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV5_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Inte... Ahh, have my intelligence[n]pheromones caught your attention?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Don't be ashamed. Your reaction[n]is normal.[n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV6_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Tell them this...[n][f 1 1][e]
[f 0 5 65278][f 2 1]"Kuma is a boy of shining beauty under[n]a fuzzy coat of fur. He combines the[n]best of both worlds..."[n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV7_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Kuma treats Yuki-chan kindly too.[n]That's why you can ask me anything,[n]Yuki-chan![n][f 1 1][e]
[f 0 5 65278][f 2 1]C'mon, give it a try.[n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV7_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]You have to put more passion into it![n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV8_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]That's marvelous, Yuki-chan! What a[n]reassuring smile...[n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV9_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 1 0 1]Sensei being Sensei, he's A-OK![n][f 1 1][e]
[f 0 5 65278][f 2 1]That's why Yuki-chan should be more[n]worried about stuff like me cheating[n]on you![n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV9_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 6 0 1]Heehee, but you're the only one for[n]me, Yuki-chan![n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV9_6 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Eek![n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV9a_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]Heavens will bless...? That sounds[n]really complicated.[n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV9a_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 2 0 1]...I'm sure Kanji doesn't know, so I[n]don't need to know either.[n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV10_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]Whoa, shyness beams headed this way...[n][f 1 1][e]
[f 0 5 65278][f 2 1][f 4 6 8 4 0 1]Oh...[n][f 1 1][e]
[f 0 5 65278][f 2 1]You don't need this bear anymore...[n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV10_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 6 65535 1]Then give me some heartbeat shyness love love[n]beams, too![n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV10a_2 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 5 0 1]...Are you and me just friends, too?[n][f 1 1][e]

[msg YUKIKO_W_KUMA_LV10a_4 [Kuma]]
[f 0 5 65278][f 2 1][f 4 6 8 3 0 1]N-Never mind, don't tell me! I've gotta[n]keep my hopes up![n][f 1 1][e]