[msg DEATH_KUMA [Kuma]]
[f 0 5 65278][f 2 1]*shudder*[n][f 1 1][e]
[f 0 5 65278][f 2 1]D-Don't open that![n][f 1 1][e]
[f 0 5 65278][f 2 1]That should never be opened![n][f 1 1][e]

[msg HELP_STAIR_KUMA [Kuma]]
[f 0 5 65278][f 2 1]I found the stairs![n][f 1 1][e]
[f 0 5 65278][f 2 1]I can lead you there anytime![n][f 1 1][e]

[msg FIND_KUMA_YOSUKE_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 445]Hey, Kuma![n]Same as always?[n][f 1 6 65535][e]

[msg FIND_KUMA_YOSUKE_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 446]Oh, Kuma![n][f 1 6 65535][e]

[msg FIND_KUMA_CHIE_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 459]Kuma![n]Keep up the good work![n][f 1 6 65535][e]

[msg FIND_KUMA_CHIE_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 460]Kuma![n][f 1 6 65535][e]

[msg FIND_KUMA_YUKIKO_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 473]Kuma, are you all right?[n][f 1 6 65535][e]

[msg FIND_KUMA_YUKIKO_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 474]Oh, it's Kuma![n][f 1 6 65535][e]

[msg FIND_KUMA_KANJI_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 503]Yo, Kuma![n][f 1 6 65535][e]

[msg FIND_KUMA_KANJI_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 504]Oh, it's just you, Kuma...[n][f 1 6 65535][e]

[msg FIND_KUMA_RISE_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 489]Kuma, still have[n]energy in you?[n][f 1 6 65535][e]

[msg FIND_KUMA_RISE_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 490]Ooh, I found Kuma![n][f 1 6 65535][e]

[msg FIND_KUMA_NAOTO_01]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 517]Kuma![n]You're here already?[n][f 1 6 65535][e]

[msg FIND_KUMA_NAOTO_02]
[f 0 5 65278][f 2 1][f 3 1 3 0 6 518]Oh, Kuma![n][f 1 6 65535][e]

[msg DOOR_KUMA [Kuma]]
[f 0 5 65278][f 2 1]I sense something beyond this door...[n][f 1 1][e]

[msg DOOR_CASTLE [Kuma]]
[f 0 5 65278][f 2 1]I sense someone beyond this door...[n][f 1 1][e]
[f 0 5 65278][f 2 1]It's that girl's scent![n][f 1 1][e]

[msg CASTLE_ENC_2 [Kuma]]
[f 0 5 65278][f 2 1]Gyaaaaaah! I've never seen such a[n]strong one before![n][f 1 1][e]
[f 0 5 65278][f 2 1]I-It's attacking us![n][f 1 1][e]

[msg CASTLE_ENC_WIN_2 [Kuma]]
[f 0 5 65278][f 2 1]I don't sense her anymore...[n][f 1 1][e]
[f 0 5 65278][f 2 1]......[n][f 1 1][e]
[f 0 5 65278][f 2 1]Oh! Are you okay, Sensei?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I'm sure we've got a long ways to go.[n]Don't push yourself too hard![n][f 1 1][e]
[f 0 5 65278][f 2 1]If you're tired, you should head back![n][f 1 1][e]

[msg DOOR_SAUNA [Kuma]]
[f 0 5 65278][f 2 1]Ooh, this presence...[n][f 1 1][e]
[f 0 5 65278][f 2 1]Could it be Kanji-kun...?[n][f 1 1][e]

[msg SAUNA_ENC_2 [Kuma]]
[f 0 5 65278][f 2 1]Ooh! Don't lose, Sensei![n][f 1 1][e]

[msg SAUNA_ENC_WIN [Kuma]]
[f 0 5 65278][f 2 1]That's our Sensei![n][f 1 1][e]
[f 0 5 65278][f 2 1]I knew you would win![n][f 1 1][e]

[msg DOOR_PLAYHOUSE [Kuma]]
[f 0 5 65278][f 2 1]The smell's coming from here![n][f 1 1][e]

[msg PLAYHOUSE_ENC_DOOR_3 [Kuma]]
[f 0 5 65278][f 2 1]*gulp*[n][f 1 1][e]
[f 0 5 65278][f 2 1]...Are you ready, Sensei?[n][f 1 1][e]

[msg PLAYHOUSE_ENC_2 [Kuma]]
[f 0 5 65278][f 2 1]Whooooooa!?[n][f 1 1][e]

[msg PLAYHOUSE_ENC_WIN [Kuma]]
[f 0 5 65278][f 2 1]What is this immense feeling[n]of... disappointment?[n][f 1 1][e]
[f 0 5 65278][f 2 1]I didn't even get a chance to choose![n]Have I been fooled?[n][f 1 1][e]
[f 0 5 65278][f 2 1]Let's just go home now, Sensei...[n][f 1 1][e]